### ISSUE TITLE
Use a role whitelist for calculating a domain from children

### ISSUE THREAD

**Issue by vijayvmenon** [FormidableLabs/victory#1075]
I have raised an issue in Stackoverflow, but thought would check here as well.

I have an Area chart in Victory where the x-axis has dates. I want to customize the x-axis Label and have created a CustomLabel component to calculate the x-axis scale and display "LABEL" below the ticks. But for some reason, the scale is not calculated correctly for the Date Object.

Please let me know what I am doing wrong here.

Code here - https://codesandbox.io/s/3203z3n7r6

Note: I tried changing the version number for Victory in the codesandbox above and it looks like its working for older versions(till 0.27.0.)

**Comment by boygirl** [comment]
@vijayvmenon 

I've modified your sandbox so that it's working. https://codesandbox.io/s/o793j1pnp6 The biggest problem was that `VictoryChart` tries to calculate a domain from its children, so it was incorrectly calculating a domain because of your custom label children. I've added a `static role = label` to your custom label component. I think the correct solution will be for me to change `VictoryChart` so that it has a whitelist of roles that it uses to calculate a domain. I will update the title of this issue to reflect that.

**Comment by vijayvmenon** [comment]
Thanks a lot @boygirl . Appreciate your help. Its fixed now .

**Comment by TRobinsonFT** [comment]
@boygirl Great solution to fix this. I came across an issue when I changed the chart from VictoryArea to VictoryLine the label position is then calculated incorrectly and its plotted far away from the chart. Is there a simple solution for this also?

**Comment by AnuMessi10** [comment]
@TRobinsonFT Were you able to figure out a fix with the VictoryLine chart? I am facing the same issue where the custom `tickLabelComponent` gets rendered far away on the left side of the chart.
