### ISSUE TITLE
Forcing chart to draw 0 label

### ISSUE THREAD

**Issue by fwielstra** [FormidableLabs/victory#1087]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I would like to always draw the '0' label in my chart. By default this does not seem to be the case; see [this example](https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-containers-in-victory) and [this example](https://formidable.com/open-source/victory/docs/victory-line/#samples). However, there are some examples such as [this one](https://formidable.com/open-source/victory/guides/custom-charts/) and [this one](https://formidable.com/open-source/victory/docs/faq/#how-can-i-change-the-position-of-my-axis) that do show it.

I've just not been able to figure out what makes it render or not render. I have a chart with a regular x (time) and y (value) axis, with a stacked bar chart and a line chart on it.

**Comment by boygirl** [comment]
@fwielstra `VictoryChart` sets the `crossAxis` prop on its axis children when they cross each other. This cases each axis to filter out zero values. To override this behavior, you can manually set `crossAxis={false}` on one of your axis children (but probably not both, because then you would have overlapping zeroes). You can read more about the `crossAxis` prop here: https://formidable.com/open-source/victory/docs/victory-axis/#crossaxis

Please also note that if you're not already supplying your own axis children for `VictoryChart` you may also run into this source of potential confusion: https://formidable.com/open-source/victory/docs/faq/#why-is-victorychart-rendering-only-one-axis
