### ISSUE TITLE
Support inverted axes for data components

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory#109]
Ability to swap `x` and `y` axes in a standard way for 
- victory-scatter
- victory-bar
- victory-chart
- victory-line

**Comment by Zerim** [comment]
It would be nice if once this is implemented in a standard way, inverting the axis could be be decoupled from the orientation of the VictoryBar as determined by the `horizontal` prop.

Currently it creates weird (broken) behavior when a horizontal VictoryBar is in a VictoryGroup with a non-VictoryBar component, and the primary axis is using a time scale... Because it inverts the axis as well as changes the orientation and there is no standard way for other components to do this (swapping the data accessors, for example, is insufficient).

**Comment by Zerim** [comment]
@boygirl I would be interested in helping out on this one if you can provide some guidance. I've had a hard time wrapping my head around what `horizontal` is doing when used with VictoryGroup, since it apparently does more than just change the orientation of the bars. 

If there was a standard way to express "inverting axis" for all chart components/ containers, then we could restrict `horizontal` to just referring to orientation of the bars.

For instance... it's not clear why this fiddle works: https://jsfiddle.net/zbzp26v9/
But this one does not: https://jsfiddle.net/ogsqttkh/
(Setting `horizontal` on VictoryBar vs on VictoryGroup).

I've also had instances (where I'm using HOCs), where I'm having to explicitly set `horiztonal` on both the VictoryGroup and the VictoryBar.

Furthermore the approach above requires manually inverting the VictoryVoronoi, but the (implicit or explicit) VictoryAxis is being inverted automatically. In general I think the API for `inverting` could be more straight forward.
