### ISSUE TITLE
is it possible to hide grid in material theme

### ISSUE THREAD

**Issue by mohan-m-u** [FormidableLabs/victory#1098]

**Comment by boygirl** [comment]
@mohan-m-u yes. You can add style props to each of your axes like `style={{ grid: { stroke: "none" } }}`

you could also extend the `material` theme to override the grid styles you don't like. The theme is just a big object. You would need to override this nested property: https://github.com/FormidableLabs/victory/blob/master/packages/victory-core/src/victory-theme/material.js#L82

Since the property is nested it might be easier to just change the styles via the style prop unless you are using it over and over for many charts.

**Comment by lewisjr** [comment]
So here is what I did:

```
export default function Elem() {
   VictoryTheme.material.axis.style.grid.strokeWidth = 0;
   ...

   return (
      <VictoryChart theme={VictoryTheme.material}>
         <VictoryBar data={barData} />
      </VictoryChart>
   )
}
```

This worked in my case because the `style={{ grid: { stroke: "none" } }}` was not working for me, and in my specific case I didn't need the grid for any of my charts.

**Comment by qryskalyst20** [comment]
I just change the stroke to transparent like this:
`grid: { stroke: "transparent" },`

```javascript
<View>
      <VictoryChart width={350} theme={VictoryTheme.material}>
        <VictoryArea
          style={{
            data: { fill: "rgb(39, 39, 42)", opacity: 0.9 },
            grid: { stroke: "transparent" },
          }}
          animate={{
            duration: 2000,
            onLoad: { duration: 1000 },
          }}
          data={chartData}
          x="date"
          y="price"
        />
      </VictoryChart>
    </View>
    ```
