### ISSUE TITLE
Fill value provided in data isn't being applied to chart components

### ISSUE THREAD

**Issue by tebs1200** [FormidableLabs/victory#1099]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When providing a `fill` property with a CSS colour in a data array, the fill values aren't being applied to data areas (columns, pie segments). Expected behaviour would be to have the fill applied as per the suggested technique on the FAQ page.

### Reproduction

The issue is visible on your [FAQ page](https://formidable.com/open-source/victory/docs/faq/#how-can-i-change-the-color-of-an-individual-point-or-bar) in the response to "How can I change the color of an individual point or bar"
<img width="450" alt="screen shot 2018-08-22 at 3 53 33 pm" src="https://user-images.githubusercontent.com/9997294/44445306-cbea5b80-a623-11e8-9250-1da4546569d2.png">

You can see that `fill` values are provided but the bars are all black.

**Comment by boygirl** [comment]
@tebs1200 my mistake. We need to update the docs. We made an intentional breaking change in version `0.26.0` to no longer support arbitrary styles on the data object. You can read about the change and a work around for it here: https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md#0260-2018-04-21

I will move this issue to `victory-docs` so I can address the mistake in the docs. Thank you for reporting this!

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory-docs#572
