### ISSUE TITLE
Make tooltips use y0 rather than y with VictoryBar

### ISSUE THREAD

**Issue by michaeljacobdavis** [FormidableLabs/victory#1103]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When using `y` and `y0` with `VictoryBar` the tooltip is aligned to `y` rather than `y0` (when positioned on top). I'm not quite sure how to have it be properly aligned above the bar.
![image](https://user-images.githubusercontent.com/916905/44631017-09e4c980-a91b-11e8-80d3-12c22264be57.png)

I've tried setting using `d => d.y0` however that doesn't seem to work either.

### Reproduction

https://codesandbox.io/s/42pn1lp5o0

**Comment by boygirl** [comment]
@michaeljacobdavis Having the tooltip aligned with `y` rather than `y0` is the expected behavior. `y0` usually indicates the baseline rather than the top of the bar. If your data is formatted opposite, you can use the `y` and `y0` data accessor props to flip it. You can read about those props here: https://formidable.com/open-source/victory/docs/victory-bar/#y

I'm going to close this issue, but please let me know if I'm not understanding something about what you need.
