### ISSUE TITLE
Bugs - Victory Line

### ISSUE THREAD

**Issue by Harsh1796** [FormidableLabs/victory#1110]
# Bugs and Questions
### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

###  Reproducing the issue: - 
<VictoryLine
  interpolation="natural"
  data={[
    {x: "JAN", y: 0},
	{x: "FEB", y: 0},
	{x: "MAR", y: 0},
	{x: "APR", y: 0},
	{x: "MAY", y: 0},
	{x: "JUN", y: 0},
	{x: "JUL", y: 0},
	{x: "AUG", y: 0},
	{x: "SEP", y: 100},
	{x: "OCT", y: 0},
	{x: "NOV", y: 0},
	{x: "DEC", y: 0}
    ]}
/>

![screenshot from 2018-09-05 17-50-59](https://user-images.githubusercontent.com/25709855/45092865-59ee3800-b134-11e8-8184-060d60d11992.png)

The line is going below axis however expected behaviour is correct when interpolation is set to "linear"

![screenshot from 2018-09-05 17-51-27](https://user-images.githubusercontent.com/25709855/45092916-7b4f2400-b134-11e8-986c-7a37abb17846.png)

**Comment by boygirl** [comment]
@Harsh1796 

Victory calculates a default domain based on data, and does not take the position of the interpolated path into account. 


The issue you're seeing can be addressed in a few ways:

1) choose a different interpolation method that creates a path that is more faithful to your data. (I suggest `monotoneX` It looks like this:

![screen shot 2018-09-11 at 12 12 00 pm](https://user-images.githubusercontent.com/3719995/45382072-09eff500-b5bc-11e8-937c-02c504d45da4.png)

instead of (`natural`): 

![screen shot 2018-09-11 at 12 13 29 pm](https://user-images.githubusercontent.com/3719995/45382114-2855f080-b5bc-11e8-93f9-6992f72fc525.png)


2) use `groupComponent={<g/>}` on `VictoryLine` so that the path is not clipped. (This method will not work if you have an animating line with changing numbers of data points)

3) set a `minDomain` that will accommodate the discrepancy between the points and the path.

**Comment by Harsh1796** [comment]
Changing "natural" to "monotoneX" works well!
