### ISSUE TITLE
Victory Area that has negative bottom values, places the x-axis in the incorrect y-offset

### ISSUE THREAD

**Issue by scottdickerson** [FormidableLabs/victory#1113]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I was expecting a VictoryArea's baseline value to influence the y-offset value of the x-axis, but it doesn't, so when the graph crosses the x-axis, the x-axis ends up in the middle of the graph, even though it's set to "bottom".  Can the automatically calculated y-offset take the baseline's minimum values into account in it's calculation of where to put the x-axis?

![image](https://user-images.githubusercontent.com/6663002/45563679-b7107a80-b813-11e8-9410-fe34d04f3795.png)

### Reproduction

Here's a sandbox that shows the issue
https://codesandbox.io/s/ojo86p97z9

**Comment by scottdickerson** [comment]
alternatively, if I could somehow get a callback with the calculated bottom domain of the y-axis, I could set the offset myself

**Comment by boygirl** [comment]
@scottdickerson This is a tricky one. `VictoryChart` automatically sets the `offsetY` prop on each of its axis components so that they cross at the origin of the chart. This is always set to zero if the `other axis` includes zero. I think this is generally the correct behavior, so I don't think anything should be changed in the library. You can manually set the `offsetY` prop on your `VictoryAxis` component to move the axis down. You can read more about the `offsetY` prop here: https://formidable.com/open-source/victory/docs/victory-axis/#offsety

Since it's relative to svg / pixel coordinates, you shouldn't require a callback with domain values if you always want your axis position to match the bottom of the y axis. Instead, you can calculated the desired position based on `height` and `padding`

**Comment by robinwkurtz** [comment]
I'm having the same issue however I cannot seem to solve the issue.

If I offset my Y by the height (no padding) it shows in a random place. Any advice?

Thanks

**Comment by hamishtaplin** [comment]
Same issue here. I don't understand how to guarantee the y-axis is at the bottom of the graph, regardless of the possible values?

**Comment by gucolin** [comment]
Same issue here. Don't think manually setting offsetY is the proper way.

**Comment by ColinMish** [comment]
I managed to get this working just by setting offsetY={50} on my X-axis. I had a bit of trouble with this due to a misunderstanding that the X offset actually uses the bottom of the VictoryChart as a baseline for X-axis offsets.

**Comment by Temzasse** [comment]
Any updates to this? It would be very useful to be able to force the x-axis to stay fixed to the top or bottom of the chart regardless of the data values. I got the x-axis to be at the top by setting the `offsetY` but now my problem is that the x-axis doesn't stay fixed if I start zooming in.
