### ISSUE TITLE
Visualizing Large Datasets With Stacked Grouped Bars

### ISSUE THREAD

**Issue by redixhumayun** [FormidableLabs/victory#1116]
# Bugs and Questions

### Checklist

* [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [X] I am using the latest version of Victory

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Visualising large datasets with stacked grouped bars is proving very difficult. Parts of the dataset disappear off the chart. How do I create responsive stacked bar charts that can handle large datasets? Can Victory JS handle cases like this? 

### Reproduction

Find the reproduced issue here
https://codesandbox.io/s/k2okxrzrnr

### Checklist

* [X] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

**Comment by boygirl** [comment]
@redixhumayun 

Thank you for the reproduction. That helps a lot! 

Unfortunately, this will be a bit manual. Since you have a set bar width and a set group offset, you will need to calculate domain padding to accommodate that. It should be something like `number of groups * (offset + width) / 2`. 

Looking at your example, though. it looks like the groups are not being correctly centered. That would be a bug in Victory. I will work on fixing that one, but in the meantime, you can use an asymmetric domainPadding like `domainPadding={{ x: [30, 120] }}` to keep everything on the chart

**Comment by redixhumayun** [comment]
@boygirl 

The bit about the set bar width and set group offset is interesting. I only have those set because I picked up this example from the docs. Its this example here: https://formidable.com/open-source/victory/gallery/stacked-grouped-bars/

So, how are the default values for those props calculated? 

Appreciate all the great work you're doing maintaining this library btw!

**Comment by BalalRaza** [comment]
![screenshot from 2018-10-22 17-41-03](https://user-images.githubusercontent.com/17193862/47291536-b42e5400-d621-11e8-80a8-ee3816dd458e.png)

I hope you resolve this issue soon. Offset is getting applied to both the stacked-groups.

Thanks for maintaining the amazing library!
