### ISSUE TITLE
Unable to fire onClick event on small bar

### ISSUE THREAD

**Issue by tschaka1904** [FormidableLabs/victory#1133]
# Bugs and Questions

### Checklist

* [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of Victory

* [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm implementing the `onClick` event for all my charts. In general it works perfectly fine, but there is a case where it becomes difficult to fire the event. Here is an example picture: 
<img width="266" alt="screen shot 2018-10-03 at 16 41 44" src="https://user-images.githubusercontent.com/5269116/46418308-d2dcb180-c72b-11e8-9c4d-aafc4c3642cb.png">

Firing the `onClick` event on the first and forth bar is almost impossible. I've looked through the docs and through the existing issues, but I couldn't find anything. Is there a way to deal with this?

**Comment by boygirl** [comment]
@tschaka1904 unfortunately Victory attaches events to the data svg, so for very small bars it will be unclickable. You can get around this by _also_ rendering a `VictoryVoronoi` with your same data and attaching your click handlers to that instead. This will give you larger target areas to click on. Just be sure to render `VictoryVoronoi` after `VictoryBar` so it will be on top. This will also introduce some mild complications into your event handlers which will now need to be added to `VictoryChart` and include a `childName` so that they are targeting the correct element

Hint: `VictoryVoronoi` renders with transparent styles by default, but you might want to give it some stroke styles so you can make sure your target areas are appropriate.

**Comment by tschaka1904** [comment]
Thanks for the answer! 👍 Is there an event I can catch from the label as this will always be visible.

**Comment by boygirl** [comment]
yes, label events use the `labels` namespace.
