### ISSUE TITLE
Feature Request: Pass chart datum into label component for axisLabelComponent/tickLabelComponent

### ISSUE THREAD

**Issue by tebs1200** [FormidableLabs/victory#1144]
# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

It would be valuable to have access to the actual chart datum in the labels generated within VictoryAxis to allow for conditional formatting/positioning.

The use-case that I have in mind is a VictoryBar chart where values can be both positive and negative. When a negative value is present, the column is rendered below the axis, covering the label. If the datum for the column was available to the label component, the y value could be checked and if it was below zero, the label could be offset to appear above the axis so it is still readable.

That's just one use-case, but I can see other scenarios where you may want to render labels differently depending on the data being charted at that point.

**Comment by boygirl** [comment]
hmm... Maybe the better solution would be to add the `data` prop to `VictoryAxis` as in the other components, and use that to assign ticks when it's present. Then things like `tickFormat` that can be called as functions would get `(datum, index, data)` as args rather than `(tick, index, ticks)`. That seems like the most straightforward implementation to me, but it would cause a bit of complexity...

Open questions:
- What happens when the user provides `data` and `tickValues` / `tickCount`? 
- How is the axis domain calculated? 
- Would `VictoryAxis` also need `x` and `y` data accessor props and `sortKey` / `sortOrder`? 

I think it would be potentially pretty handy. Folks creating bar charts very often want their axis ticks to exactly match their bars, and it's often a source of confusion when they don't.

@tebs1200 Would you be interested in writing a proof of concept for this feature?

**Comment by tebs1200** [comment]
Yes - I'd be happy to have a go at writing a POC for this. Not sure exactly when I'll be able to fit it in, but I'll chip away at it over the next week or so.

**Comment by owensco** [comment]
+1 for this. 

I'd like to position the axis label based on the min or max value in the dataset.

This use-case is already supported for [VictoryLabel](https://formidable.com/open-source/victory/docs/victory-label#datum).
