### ISSUE TITLE
Font size x-axis, y-axis too small

### ISSUE THREAD

**Issue by rweller59** [FormidableLabs/victory#1150]
# Bugs and Questions

### Checklist

* [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ x] I am using the latest version of Victory

* [x ] I've searched open issues to make sure I'm not opening a duplicate issue

Using the victory library with React Material-UI Components Library grid layout which uses CSS Flexible Box module.  I'm rendering graphs in fairly small flex box - graph looks ok but the axis label fonts are too small to read. Is there a way to prevent this?

**Comment by boygirl** [comment]
@rweller59 

You can change the font sizes by altering the `style` prop on `VictoryAxis`. Here's some more documentation on the style prop: https://formidable.com/open-source/victory/docs/victory-axis/#style

Unfortunately, because of how svg scales text, you wont be able to auto scale the text when your container size changes. To get around that you can add a resize handler and alter the fontSize accordingly.
