### ISSUE TITLE
How to change troke color in line chart  when y < 0?

### ISSUE THREAD

**Issue by Eric0201** [FormidableLabs/victory#1252]
Hello , how to change color troke line chart same picture? i try it but not working
![03-block-lifeplanchart](https://user-images.githubusercontent.com/38023513/52851155-f4bd5a80-3147-11e9-8e3d-0ec6fda35811.png)

**Comment by boygirl** [comment]
Since Victory renders a single element for areas and lines, it can't automatically color sections of a line or area differently automatically. Instead you can use a gradient fill or stroke. Here's a similar example: https://formidable.com/open-source/victory/gallery/stream-graph/

**Comment by karlvd** [comment]
See https://github.com/FormidableLabs/victory/issues/1242#issuecomment-495224922

**Comment by Justinohallo** [comment]
I have tried multiple implementations of this library to render a line, that will change colors above and below 0. 

Does anyone have a working example ? The gradient method will not work since the gradient only applies to the height of the VictoryLine being rendered, not the container. Therefore, the red / green line will not properly change colors above or below 0. It will change colors based on 50% of it's own height, which is often smaller than the container.

**Comment by tomskopek** [comment]
@Justinohallo : After running into the same issue as you with Gradient, the solution shown by @karlvd worked for me 😄 - feel free to share some code and maybe I can help you achieve what you're looking for
