### ISSUE TITLE
Moving Grid lines between the adjacent bars in Bar chart

### ISSUE THREAD

**Issue by js-jegan** [FormidableLabs/victory#1262]
Hi, I’m implementing charts for a react-native mobile app using victory charts. Wanted to know is there any tweaks available to move the grid between the bars of the bar chart rather than the grid like being on center of the bar. 
In d3, we can get the barStep using the axis scale. Lookingfor something similar so that I can move the linesegment of grid component accordingly. If needed I canupload image of my expectation.

**Comment by boygirl** [comment]
@js-jegan yes! You can manually set the `tickValues` on your `VictoryAxis` component so that they are offset from your bars like so: 
```
 <VictoryChart>
    <VictoryBar
      data={[{ x: 1, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 4 }]}
    />
    <VictoryAxis
      tickValues={[1.5, 2.5, 3.5]}
      tickFormat={["first", "second", "third"]}
    />
  </VictoryChart>
```
Here's more information on axis `tickValues`: https://formidable.com/open-source/victory/docs/victory-axis/#tickvalues

Or if you just want your bars set to one side or the other of the grid line you can use the `alignment` prop on `VictroyBar`:
https://formidable.com/open-source/victory/docs/victory-bar/#alignment

Or you can translate your bar components by a specific number of pixels, but this is not recommended in most cases as it will make your chart inaccurate and will need to be updated as the domain changes:

```
 <VictoryChart domain={{ x: [0, 5] }}>
    <VictoryBar
      data={[{ x: 1, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 4 }]}
      dataComponent={<Bar transform="translate(30)"/>}
    />
  </VictoryChart>
```
