### ISSUE TITLE
VictoryLine domainPadding does not pad the bottom of the y domain when given a positive lower bound

### ISSUE THREAD

**Issue by jorihardman** [FormidableLabs/victory#1269]
### The Problem

When using a positive integer as the lower bound of the y `domainPadding` parameter for `VictoryLine`, it does not increase the padding. This causes the line to be cut off at the bottom of the domain when you have a wide stroke width. 

### Reproduction

https://codesandbox.io/s/6xjnqx51vz

In this example, I have a very wide strokeWidth (10). Without domainPadding, the strokeWidth is cut off at the top and bottom like so:

![screen shot 2019-03-08 at 11 57 06 am](https://user-images.githubusercontent.com/99236/54046248-6746b680-4199-11e9-8eea-83cbc2ad5d9a.png)

If I specify a `domainPadding` of `{{ y: [10, 10] }}`, the top padding allows the whole line to be shown (notice it comes to a point now), but the bottom is still cut off:

![screen shot 2019-03-08 at 11 57 20 am](https://user-images.githubusercontent.com/99236/54046284-847b8500-4199-11e9-926a-3c003f1207fd.png)

I would expect padding to increase below the bottom of the y domain to allow the full stroke width to be seen.

**Comment by boygirl** [comment]
@jorihardman by default `domainPadding` is coerced so that it only pads within existing quadrants (i.e. it will never make you domain go negative because that can make your axes look strange). To turn off this behavior add the awkwardly named prop: `singleQuadrantDomainPadding={false}`. You can read more about it here: https://formidable.com/open-source/victory/docs/common-props/#singlequadrantdomainpadding
