### ISSUE TITLE
Stacked bar chart and cornerRadius

### ISSUE THREAD

**Issue by tremby** [FormidableLabs/victory#1289]
I have a stacked bar chart, and I want corner radius on the tops of each bar but not the bottoms.

This leaves little gaps between adjacent stacked bars, since the shapes are only rendered from the top of the previous bar rather than from the axis.

Here's an example in a sandbox:

https://codesandbox.io/embed/y2m2o2qzqv

I'd like some way to eliminate those little gaps.

I've tried playing with y0 but haven't had any luck with it. Is it possible right now? If not, this is a feature request!

**Comment by boygirl** [comment]
@tremby the `cornerRadius` prop on `VictoryBar` can take an object with values for each individual corner. Check it out: https://formidable.com/open-source/victory/docs/victory-bar#cornerradius

I think what you're saying, though, is that you'd like the top bar to extend a bit below and behind the bottom bar in your stack. Unfortunately this isn't going to be possible with `VictoryStack` since it calculates the `y0` and `y` values such that the bars stack cleanly on top of each other. I don't think it would be appropriate to alter the behavior of `VictoryStack` to fit this use case. You have a couple options:

1) compute your own stack layout and pass in data with the `y0` and `y` values that take an overlap into account

2) use a custom `dataComponent` that offsets the `y0` value of the `Bar` component that `VictoryBar` renders as in this example: https://codesandbox.io/s/ovnp6w6lyz 
This is probably the easiest solution, but it currently only works for two bar stacks since the render order of the bars is from bottom to top. The example above uses `VictoryPortal` to move the bottom bar to a higher zindex container than the top one, but that solution wont work for several bars. Looking at this example makes me want to reverse the default render order for `VictoryStack`, though, since examples like this make much more sense with taller bars "behind" shorter ones.

**Comment by tremby** [comment]
I understand. Yes, the actual real-world application has three bars stacked so I guess option 2 won't work for me.

Can you tell me more about what would be involved in option 1?

> Looking at this example makes me want to reverse the default render order for `VictoryStack`, though, since examples like this make much more sense with taller bars "behind" shorter ones.

Sounds like a good idea to me!

**Comment by boygirl** [comment]
@tremby I just released `victory@32.2.0` with the render order reversed for children of `VictoryStack` so you should be able to use solution 2 described above.  The other option would be computing your own stack layout which would mean doing some math to alter the y and y0 values of each point to account for the data stacked below it. You could use `d3.stack` to compute it for you: https://github.com/d3/d3-shape/blob/master/README.md#stack

**Comment by tremby** [comment]
Thanks! I see 32.2.0 on Github but not yet on NPM. Are the wheels in motion?

**Comment by tremby** [comment]
I see it now!

**Comment by tremby** [comment]
That's working; thank you very much. https://codesandbox.io/s/lr2zy0r59m

**Comment by tremby** [comment]
Edited the example a bit to max y0 out at scale(0), which means the custom bar can be used for all parts of the stack without worrying about it overhanging the x axis. This also fixes issues where the bottommost bar of the stack is of 0 value or very short (shorter than the corner radius).

```js
class CustomBar extends React.Component {
  render() {
    const y0 = Math.min(this.props.scale.y(0), this.props.y0 + cornerRadius);
    return <Bar {...this.props} y0={y0} />;
  }
}
```

Thanks again for your help.
