### ISSUE TITLE
How to disable grouping on axis tick values

### ISSUE THREAD

**Issue by gabrielhpugliese** [FormidableLabs/victory#1311]
# Question

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I want to have an axis with day name ('Mon', 'Tue', 'Wed'...) but they should be continuous and not be grouped. What is happening now is that when I have two entries with same "x", two  different points on "y" are created.

### Reproduction

I think this shows quite clear what I am trying to fix. I want that day names "Mon", "Tue"... continuously after "Sun" (it's localized in German):
![image](https://user-images.githubusercontent.com/1252818/58246068-6f54d200-7d56-11e9-802c-3ef2c28be9a4.png)

The data as json: https://gist.github.com/gabrielhpugliese/19d40780db238a260e8b34f0386b71ef

**Comment by boygirl** [comment]
Thanks for your patience! I think you are misunderstanding the distinction between [tickFormat](https://formidable.com/open-source/victory/docs/victory-axis/#tickformat) and  [tickValues](https://formidable.com/open-source/victory/docs/victory-axis/#tickvalues). Since `tickValues` refer to _position_, specifying duplicates will not result in multiple ticks.
