### ISSUE TITLE
How to avoid labels overlapping?

### ISSUE THREAD

**Issue by MiloVahos96** [FormidableLabs/victory#1316]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Hi, I have a graph with multiple victory area and victory scatter inside a victory chart, the problem is that when I have to graphs with the same point, the labels are overlapping as it is showed in the following figure.

![image](https://user-images.githubusercontent.com/22629572/59067213-9cd16d80-8876-11e9-9268-9db35a0889b8.png)

Any idea of how to avoid this behaviour? I tried Victory Portal but it didnt work.

**Comment by boygirl** [comment]
Unfortunately there isn't a built in solution to this issue. Victory doesn't use a constraint based layout and doesn't have any concept of overlap detection. You could design your chart differently to use a legend, or use tooltips instead of labels. Tooltips using `VictoryVoronoiContainer` would best for nearly overlapping data) Depending on your data, it might also work to alternate between showing labels above and below your points for each series (you can change the padding on your labels to do this). I hope one of those ideas helps! I'm going to close this issue, since there isn't a fix that would make sense to add to the library.
