### ISSUE TITLE
Is there an undocumented throttle/ debounce for VictoryVoronoiContainer?

### ISSUE THREAD

**Issue by gajus** [FormidableLabs/victory#1318]
There appears to be some logic throttling rendering of `VictoryVoronoiContainer` `labelComponent`.

![ScreenFlow 2019-06-10 13_19_16](https://user-images.githubusercontent.com/973543/59194899-6bacb200-8b82-11e9-9de8-a984321eb2a0.gif)

Where is this documented/ how to disable this?

Possibly related to:

* https://github.com/FormidableLabs/victory/issues/537
* https://github.com/FormidableLabs/victory/issues/873

**Comment by boygirl** [comment]
`VictoryVoronoiContainer` works by splitting the entire active area of the chart into regions where each region is optimized for the nearest data point. What you're seeing isn't throttling, it's your mouse moving into new regions and triggering different elements (that's my guess anyway, but it's difficult to tell with the zero / undefined data). Unfortunately this isn't something that can be disabled, because it is how the feature is built, and how it associates mouse position to nearest data.

I think the you might be looking to create a mouse following tooltip. This is something that is enabled for multi-point tooltips on `VictoryVoronoiContainer`, but I can add it as an option for all tooltips. Does that sound like it would solve your problem?

**Comment by gajus** [comment]
> What you're seeing isn't throttling, it's your mouse moving into new regions and triggering different elements (that's my guess anyway, but it's difficult to tell with the zero / undefined data)

That is not the case.

The chart is produced by creating a data bucket for every hour displayed on the chart, i.e.

```js
const fromDate = moment(props.eventFilterInput.changeFromDate, 'YYYY-MM-DD').toDate();
const toDate = moment(props.eventFilterInput.changeToDate, 'YYYY-MM-DD').add(1, 'day').toDate();

const dateRange = timeHours(
  fromDate,
  toDate,
  1
);

const x = scaleTime()
  .domain([
    fromDate,
    toDate
  ])
  .nice(timeHour, 1)
  .range([
    0,
    dateRange.length
  ]);

const chartData = dateRange.map((date) => {
  return {
    date,
    sales: data.getSalesVolumeReports.reduce((accumulator, currentValue) => {
      if (x(currentValue.changeTime) === x(date)) {
        return accumulator + Math.max(currentValue.seatSoldCountChange, 0);
      }

      return accumulator;
    }, 0)
  }
});

```

Filling the empty data gaps with 0.

Here is a GIF first proving that the datapoints do exist followed by showing that the tooltip for them is not rendered if the mouse cursor is moved fast.

![ScreenFlow 2019-06-11 08_14_22](https://user-images.githubusercontent.com/973543/59251119-efb57700-8c20-11e9-8103-c3df2deb0b75.gif)

That said, I cannot replicate the same behaviour in codesandbox.io.

https://codesandbox.io/s/custom-baseline-for-stacked-areas-e1fbw

Perhaps this is performance issue when running in development mode?

> I think the you might be looking to create a mouse following tooltip. This is something that is enabled for multi-point tooltips on VictoryVoronoiContainer, but I can add it as an option for all tooltips. Does that sound like it would solve your problem?

What I want to achieve is a tooltip that would display the selected time and any data points at that time bucket, e.g.

![ScreenFlow 2019-06-11 08_29_08](https://user-images.githubusercontent.com/973543/59252094-2d1b0400-8c23-11e9-8f0f-454059375dcf.gif)

(screenshot from https://www.fusioncharts.com/fusiontime)

Would it solve my problem?

**Comment by boygirl** [comment]
There is throttling for all the `onMouseMove` events on Victory's evented containers (like `VictoryVoronoiContainer`), but it's set to 32ms, so that seems really unlikely to be the cause of your problem. I would guess what you're seeing is due to performance in general, so removing that throttle could potentially make it worse.

**Comment by boygirl** [comment]
@gajus I have a PR open that I expect to improve perf for `VictoryVoronoiContainer`: https://github.com/FormidableLabs/victory/pull/1322

I'm also working on a few features that will go out in `v33.0.0` that will be relevant to your use case: 
https://github.com/FormidableLabs/victory/issues/1319
https://github.com/FormidableLabs/victory/issues/899

**Comment by gajus** [comment]
Sweet. #1319 #899 should be enough to solve my use case.

**Comment by elderferreiras** [comment]
@gajus Were you able to get to this result in your research?

![Image of Yaktocat](https://user-images.githubusercontent.com/973543/59252094-2d1b0400-8c23-11e9-8f0f-454059375dcf.gif)
