### ISSUE TITLE
No delaunay triangulation exists for this input exception

### ISSUE THREAD

**Issue by jayasivabaskar** [FormidableLabs/victory#1341]
No delaunay triangulation exists for the input

Problem description
Entering the chart area for a candle series chart is throwing this exception
Entering the chart area in case of charts which have the all y dimensions values as zero throws the above exception

**Comment by boygirl** [comment]
@jayasivabaskar thanks for the issue. I think I was a little premature in my change from voronoi diagrams to delaunay diagrams for finding the nearest point. The delaunay diagram is faster, but it doesn't handle sparse datasets correctly. I'm going to revert this change. Thanks for your patience.

**Comment by boygirl** [comment]
fixed by https://github.com/FormidableLabs/victory/pull/1343

**Comment by dvonlehman** [comment]
@boygirl We recently upgraded to the version of Victory with the Delaunay diagrams specifically to address
an "Out of memory" crash on Chrome. The crash we were experiencing is identical (same breakpoint/call stack) to the one in this issue: https://github.com/d3/d3-voronoi/issues/28. Since upgrading to victory@32.3.0, we have not seen the crash at all. We have intermittently seen the "no triangulation exists" error, but that is a lesser evil than a full browser crash. Obviously, we can stay at `32.3.0` for now, but it'd be great to know if there are plans to re-visit switching from Voronoi to Delaunay or addressing the "out of memory" vulnerability some other way?

**Comment by boygirl** [comment]
Yes, I looked into upgrading to the latest version of `delaunator`, and was able to solve the no triangulation error, but the behavior for multiple datasets with collinear points is different from `voronoi` in undesirable ways. I will revisit this with my next planned breaking change, since I fear some differences in behavior between voronoi and delaunay might be unavoidable.

**Comment by dvonlehman** [comment]
Perhaps some way to pass a prop to opt-in to delaunay to avoid breaking changes?

**Comment by boygirl** [comment]
That's a possibility. The behavior I'm hung up on looks broken to me, but it won't impact everyone

**Comment by boygirl** [comment]
![delaunay](https://user-images.githubusercontent.com/3719995/60535309-a8b72080-9cb8-11e9-9c40-7f88f222c826.gif)

This is the undesirable behavior I'm seeing

**Comment by dvonlehman** [comment]
We are also having some issues with hovering, though not quite as extreme as your example. On a histogram component, sometimes the hover fails to trigger, and sometimes it triggers for a different datum than where the mouse is actually located. Internally, we are relying on the `onActivated` prop of the `VictoryVoronoiContainer` to `setState` which will then display a hover card in the re-render. We use `onDeactivated` to clear the state.  I'll do some more debugging and report back here if I find anything potentially valuable.

**Comment by boygirl** [comment]
@dvonlehman I spent a bit of time looking into this more closely.  Since I'm already using a forked and altered version of `d3-delauany` (because their version requires polyfills), I went ahead and altered the behavior for collinear points so it would match more closely to voronoi behavior. I have a PR out now, and I'll publish a patch once CI passes. I would be grateful if you could test out the patch I publish and let me know if you are seeing any weird behavior.

**Comment by boygirl** [comment]
@dvonlehman released as `victory@32.3.2`

**Comment by dvonlehman** [comment]
@boygirl I haven't had a chance to test this out yet, but will report back here once I do. Thanks for such a rapid response on this.
