### ISSUE TITLE
Add possibility to have a linear grid for polar charts

### ISSUE THREAD

**Issue by madmed88** [FormidableLabs/victory#1353]
Is it possible to have a linear grid instead of the circular grid for polar charts?
The same thing is available in nivo using the gridShape property https://nivo.rocks/radar/

**Comment by boygirl** [comment]
Unfortunately this is not currently supported. VictoryAxis components are pretty independent of each other, and only held together by a few props that `VictoryChart` controls, like `domain`. The circular gridlines are easy, because the axis rendering them is the _radial_ axis, and it just needs to know at which radius to draw each gridline, and then it draws a circle. The linear gridlines would need to know both the radius, and the where all of the angular ticks should be, so it can form the path. The angular ticks are controlled by the angular axis, so adding this feature would require `VictoryChart` to know about the tickValues of all of its axes. so that it can share that information between axes.

**Comment by LaylaCsAvila** [comment]
As a possible workaround, you can remove the original round grid and use area charts without color filling to make a fake one:
 
This will remove the original grid
```
<VictoryPolarAxis dependentAxis style={{ grid: { strokeWidth: 0 } }} />
```

And you can draw a new one:
```
<VictoryGroup style={{ data: { fillOpacity: 0, strokeWidth: 1, stroke: gray, strokeOpacity: 0.5 } }}>
   {sqrAxis.map((data1, i) => {
      return <VictoryArea key={i} data={data1} />;
   })}
</VictoryGroup>
```

For the fake data used for the grid, you need to pass an array for each "level" of grid you want. Each array should be filled with objects that have your axis as x values, and for every array all objects should have the same y value. An example:
```
const sqrAxis = [
    [
      { x: 'charisma', y: 100 },
      { x: 'uniqueness', y: 100 },
      { x: 'nerf', y: 100 },
      { x: 'talent', y: 100 },
      { x: 'superstardom', y: 100 },
    ],
    [
      { x: 'charisma', y: 200 },
      { x: 'uniqueness', y: 200 },
      { x: 'nerf', y: 200 },
      { x: 'talent', y: 200 },
      { x: 'superstardom', y: 200 },
    ],
    [
      { x: 'charisma', y: 300 },
      { x: 'uniqueness', y: 300 },
      { x: 'nerf', y: 300 },
      { x: 'talent', y: 300 },
      { x: 'superstardom', y: 300 },
    ],
    [
      { x: 'charisma', y: 400 },
      { x: 'uniqueness', y: 400 },
      { x: 'nerf', y: 400 },
      { x: 'talent', y: 400 },
      { x: 'superstardom', y: 400 },
    ],
  ];
```

This code will render this graph:
![Screenshot from 2020-03-05 15-50-40](https://user-images.githubusercontent.com/29239502/76016588-d9acbc80-5efb-11ea-9320-73faa3b677fe.png)
That has a domain from 0 to 400.


Maybe something like that could be implemented inside VictoryPolarAxis or VictoryChart?

**Comment by Codesleuth** [comment]
I think a better solution would be to provide more props to the `circularGridComponent` (of `VictoryPolarAxis`) so that we can determine the lower bound of the segment. Currently, `cx` and `cy` are "zero", but we cannot determine the offset of this segment, so we must always render trapezoids from the centre.

Actually, rendering without knowing the lower segment might be OK in some scenarios if the render order of the components was reversed. The segments are rendered outward, meaning layering the paths will implicitly overlap, with fills hiding lower segments.

@LaylaCsAvila's suggestion for a workaround is fine, but in the end I would prefer the implementation to manage this as a grid component alternative to `<Arc />`.

On a side note, the number of `<Arc />` being rendered is wasteful. There are `tickValues.length` number of arcs being drawn per axis. For a chart with 6 entries and 3 tick values each, there are 18 arcs, with 6 overlapping at each tick. Possibly suggesting that the `circularGridComponent` prop is in the wrong place, and should be defined higher up?

**Comment by lishaoxin123** [comment]
> ```
> <VictoryPolarAxis dependentAxis style={{ grid: { strokeWidth: 0 } }} />
> ```

Hello, can you provide the complete code? I used the following code, but it didn't work
`  const sqrAxis = [
    [
      { x: 'charisma', y: 100 },
      { x: 'uniqueness', y: 100 },
      { x: 'nerf', y: 100 },
      { x: 'talent', y: 100 },
      { x: 'superstardom', y: 100 },
    ],
    [   
      { x: 'charisma', y: 200 },
      { x: 'uniqueness', y: 200 },
      { x: 'nerf', y: 200 },
      { x: 'talent', y: 200 },
      { x: 'superstardom', y: 200 },
    ],
    [
      { x: 'charisma', y: 300 },
      { x: 'uniqueness', y: 300 },
      { x: 'nerf', y: 300 },
      { x: 'talent', y: 300 },
      { x: 'superstardom', y: 300 },
    ],
    [
      { x: 'charisma', y: 400 },
      { x: 'uniqueness', y: 400 },
      { x: 'nerf', y: 400 },
      { x: 'talent', y: 400 },
      { x: 'superstardom', y: 400 },
    ],
  ]

    <VictoryChart
      polar
      theme={VictoryTheme.material}
    >
      <VictoryGroup style={{ data: { fillOpacity: 0, strokeWidth: 1, stroke: 'gray', strokeOpacity: 0.5 } }}>
      <VictoryPolarAxis dependentAxis style={{ grid: { strokeWidth: 0 } }} />

   {sqrAxis.map((data1, i) => {
      return <VictoryArea key={i} data={data1} />;
   })}
</VictoryGroup>
      {/* <VictoryPolarAxis labelPlacement="perpendicular" tickValues={[1]} style={{axis: {stroke: "#fff"},}} />
      <VictoryGroup  style={{ data: { fillOpacity: 0, strokeWidth: 1, stroke: 'gray', strokeOpacity: 0.2 } }}>
        {sqrAxis.map((data1, i) => {
            return <VictoryArea key={i} data={data1} />
        })}
      </VictoryGroup> */}
 
    </VictoryChart>`
