### ISSUE TITLE
figure out an update and release system for components

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#14]
It should:

- check for version updates to the `package.json` either with something like [npm-check-updates](https://github.com/tjunnone/npm-check-updates) or by matching to the top-level victory repo `package.json`

- bump and commit each component version, and publish the new version to the npm registry

- top level victory repo should depend on other victory components at "latest"

- run from one place and update all the components

**Comment by Gastove** [comment]
Yesssssssss. I like this a lot -- I'm just not tooling-conversant enough to know how to do it. One idea: a sort of meta-repo (probably this one) that contains all other modules as git submodules. From there, _so much scripting_.

**Comment by colinmegill** [comment]
@ryan-roemer Could you chime in here?

**Comment by ryan-roemer** [comment]
From slack convo, here's where we ended up:

1. [ ] fmd-boilerplate add an `update-deps` script command with `npm-update-whatever-that-script-is` added as a `devDependency` and mutate `package.json`, `npm install` again, and `npm run check`. Add docs saying "pull a branch", run `update-deps`, if it passes, commit the result, push branch and open PR.
2. [ ] Automate that in a meta repo or in a not-passed-to-the generator directory in boilerplate -- automation code be programmatic to the GH API or with local checkouts of components...  Either way, will be a little wonky, because automagic bulk updates in code rarely work reliably and consistently ;)  Often will need manual tweaks

**Comment by coopy** [comment]
Closed - we have [builder](https://github.com/formidablelabs/builder) ;]
