### ISSUE TITLE
axisLabelComponent is not displayed

### ISSUE THREAD

**Issue by Jackloktiev** [FormidableLabs/victory#1463]
I'm trying to add a label to the chart that will be explaining what this chart is about. Reading through the docs I've figured out that proper element for that would be axisLabelComponent on the x-axis. However, when I've tried to add it to the VictoryAxis element it is not displayed. I can't see it even in React developer tools. Not sure if this is a bug or I'm doing something wrong. I wasn't able to find the solution neither in docs nor in the Internet. Please advise how to fix it. Below is the code to reproduce the issue (from sandbox https://codesandbox.io/s/basic-victory-example-iok0h)

`import React from "react";
import ReactDOM from "react-dom";
import {
  VictoryBar,
  VictoryChart,
  VictoryAxis,
  VictoryLine,
  VictoryLabel
} from "victory";

function Chart() {
  const norm = [{ x: 1, y: 1000 }, { x: 2, y: 1000 }, { x: 3, y: 1000 }];

  const consumption = [{ x: 1, y: 0 }, { x: 2, y: 2000 }, { x: 3, y: 0 }];

  return (
    <div>
      <VictoryChart
        domainPadding={10}
        style={{
          parent: { backgroundColor: "black" }
        }}
      >
        <VictoryAxis
          dependentAxis
          crossAxis
          orientation="left"
          style={{
            axis: { stroke: "white" },
            tickLabels: { fill: "white" }
          }}
        />
        <VictoryAxis
          crossAxis
          orientation="bottom"
          tickFormat={() => ""}
          style={{
            axis: { stroke: "white" },
            axisLabelComponent: { fill: "white" }
          }}
          axisLabelComponent={<VictoryLabel text="Label text" dx={20} />}
        />
        <VictoryLine
          data={norm}
          style={{
            data: { stroke: "red" }
          }}
        />

        <VictoryBar
          data={consumption}
          barWidth={30}
          domainPadding={0}
          style={{
            data: { fill: "rgb(241,155,92" }
          }}
        />
      </VictoryChart>
    </div>
  );
}

ReactDOM.render(<Chart />, document.getElementById("root"));
`

**Comment by boygirl** [comment]
@Jackloktiev Thanks for the codesandbox reproduction! That makes it much earier to help. It looks like the styling for the axis label was incorrect. The correct namespace is `axisLabel` instead of `axisLabelComponent`. It is also necessary in later versions of Victory to define a `label` prop when you want to render labels to save a bit of performance. In your case, you could either define your label to be `label="Label Text"` or just `label`, and let your `axisLabelComponent` continue providing its own text. I've forked and edited your sandbox to demo the changes I describe:
https://codesandbox.io/s/basic-victory-example-z1w7c
