### ISSUE TITLE
Custom Grid for Axis

### ISSUE THREAD

**Issue by ramilexe** [FormidableLabs/victory#1464]
Hello, I am trying to build the chart like this 
![image](https://user-images.githubusercontent.com/1008882/71372703-26078200-25c6-11ea-9fa4-c5bf72d4f579.png)
Everything is ok except vertical grid lines and highlighting part of `x` axe. 
My data is like this:
```js
const data = [
  {x: 1, y: 5, week:1, phase: 1},
  {x: 2, y: 7, week:1, phase: 1},
  {x: 3, y: 10, week:1, phase: 1},
  {x: 4, y: 15, week:2, phase: 1},
  {x: 5, y: 15, week:2, phase: 1},
  {x: 6, y: 12, week:3, phase: 2},
  {x: 7, y: 17, week:3 phase: 2},
];
```
I have value for each day and also groups for weeks and phases. I successfuly draw line but have no idea how to build Axis Grid. When I enable it it shown for each day, but I need to group it by week and by phase (also be able to hightlight phase (P3 on picture). I tried to use parameters `tickValues`, `tickFormat`, `categories`, nothing works for me.

Could you give me direction on how to implement that?

Thank you!

**Comment by boygirl** [comment]
@ramilexe This one is a little tricky. `VictoryAxis` does not know anything about the data that is plotted next to it, except for the overall domain. In order to make gridlines that spot cleanly at your line data, it would be much easier to plot these as a `VictoryBar` data set, and make the barWidth very small. As for the axis highlight, the easiest way to accomplish that would be to add an annotation to your chart. Here's an example: https://formidable.com/open-source/victory/docs/faq/#how-can-i-annotate-my-charts-with-lines-and-markers
You could use a VictoryLine component for your annotation. If you need something more custom, though, any child of `VictoryChart` will be provided with a `scale` prop with `domain` and `range` applied. This can be used to convert from data coordinate to svg coordinate space. I hope that helps.
I'm going to close this issue now, but please reach out if you have additional questions.
