### ISSUE TITLE
Use Proptype.Array as Events targets ?

### ISSUE THREAD

**Issue by jotak** [FormidableLabs/victory#1470]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ ] I am using the latest version of Victory
No: 33.1.2 - but it doesn't seem different in latest

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am using events to target both labels and data. As such: ` target: ['data', 'labels'] `. This event object is then being passed to the `VictoryChart` component. And ... it works as intended. The event being triggered both on data and labels.

However the documentation, as well as the Proptypes definition, says the events target should be String and not Array. I'm getting console error because of that.

So, does it work just coincidentally, and I should *not* be doing this? (because for instance it could be broken in a future release - or maybe there's other bad side effects I'm not aware of?)

Or is it intended, in which case I guess the doc & proptypes ( https://github.com/FormidableLabs/victory/blob/master/packages/victory-shared-events/src/victory-shared-events.js#L31 ) should be updated to allow arrays?
The array notation is more convenient than having to duplicate event registration per target, so it's quite nice that it works.

**Comment by alexhuitan** [comment]
Ran into this issue as well. There's a mismatch between the expected behavior in event assignment versus the proptype shapes.

Here, we see that the targeting accepts both array and string (at least in function).

https://github.com/FormidableLabs/victory/blob/c6229753ec1766519bff9da01db5a4c78c2e7fc3/packages/victory-core/src/victory-util/events.js#L17

And here, we see that the expected proptype is a string with some expected values.

https://github.com/FormidableLabs/victory/blob/master/packages/victory-legend/src/victory-legend.js#L72

Luckily, this doesn't block the desired behavior, but it's a slight nuisance seeing the proptype errors.
