### ISSUE TITLE
Line Chart is broken when Y values are the same

### ISSUE THREAD

**Issue by BrunoQuaresma** [FormidableLabs/victory#1471]
I'm using `victory@^34.0.0` and when I try to create a Line chart where the `y` values are the same I see the following image:

<img width="495" alt="Screen Shot 2020-01-19 at 16 32 37" src="https://user-images.githubusercontent.com/3165839/72687119-ae9c1400-3ad9-11ea-893e-a57fd58cb24e.png">

```
const data = [
  { x: Date('01/18/20'), y: 47 },
  { x: Date('01/17/20'), y: 47 },
  { x: Date('01/16/20'), y: 47 },
  { x: Date('01/15/20'), y: 47 },
  { x: Date('01/14/20'), y: 47 },
  { x: Date('01/13/20'), y: 47 },
  { x: Date('01/12/20'), y: 47 }
];

return (
  <VictoryChart domainPadding={10} height={300}>
    <VictoryLine data={data} />
  </VictoryChart>
)
```

If I change `VictoryLine` by `VictoryBar` I get the expected view:

<img width="504" alt="Screen Shot 2020-01-19 at 16 31 21" src="https://user-images.githubusercontent.com/3165839/72687178-3c77ff00-3ada-11ea-9c05-2b35b987db72.png">

An interesting thing, If I change one of the `y` values to be different it works and displays the expected view:

<img width="500" alt="Screen Shot 2020-01-19 at 16 32 15" src="https://user-images.githubusercontent.com/3165839/72687198-5580b000-3ada-11ea-9374-be901b818b5e.png">

```
const data = [
  { x: Date('01/18/20'), y: 46 },
  { x: Date('01/17/20'), y: 47 },
  { x: Date('01/16/20'), y: 47 },
  { x: Date('01/15/20'), y: 47 },
  { x: Date('01/14/20'), y: 47 },
  { x: Date('01/13/20'), y: 47 },
  { x: Date('01/12/20'), y: 47 }
];

return (
  <VictoryChart domainPadding={10} height={300}>
    <VictoryLine data={data} />
  </VictoryChart>
)
```

Thanks,

**Comment by boygirl** [comment]
@BrunoQuaresma This is actually expected behavior. When you don't provide an explicit domain, Victory tries to calculate a domain for your chart based on any available data. In your case, you only have a single y value (47), so Victory is calculating your y domain as 47 +/- a very small number. `VictoryBar` looks different, because it uses a baseline (y0 = 0), so Victory calculates the domain as [0, 47]. To fix the behavior, you can either set an explicit `domain` prop on `VictoryChart`, or try the `minDomain` prop, to set only a lower bound. Something like this:

```
<VictoryChart minDomain={{ y: 0 }} domainPadding={{ y: 20}}> 
        <VictoryLine
          data={[
            { x: 1, y: 47 },
            { x: 2, y: 47 },
            { x: 3, y: 47 }
          ]}
        /> 
      </VictoryChart>
```

You can read more about the `minDomain` prop here: https://formidable.com/open-source/victory/docs/common-props/#mindomain

**Comment by BrunoQuaresma** [comment]
Ahh ok I gotcha, thanks @boygirl
