### ISSUE TITLE
VictoryLegend doesn't render when placed inside a Fragment element. 

### ISSUE THREAD

**Issue by nvolungis** [FormidableLabs/victory#1498]
### The Problem

I'm looking to conditionally render a legend in a standard `VictoryChart`. The thing is I also want to render a dividing line in this case, so the conditional contains two elements. Normally this could be accomplished with a `Fragment` component (as there's no logical parent node for these two components), but when I stick a fragment in there the legend doesn't render while the line does. This makes me think it has something to do with victory props not getting passed through the fragment, but I'm not sure how to accomplish that. 

### Reproduction
https://codesandbox.io/s/fragment-example-gy3vf

**Comment by narinluangrath** [comment]
Hi @nvolungis! 🎉 

I haven't had a chance to dig into the code, but I suspect the reason is that `VictoryChart` is trying to pass props via `React.cloneElement`, and unfortunately the props are getting pass to the `React.Fragment` instead of to your `VictoryLegend`. You can solve this pretty easily with a wrapper component that passes props.

```
const VerticalLine = ({ x, y, length }) => (
  <line
    vectorEffect="non-scaling-stroke"
    x1={x}
    x2={x}
    y1={y}
    y2={length}
    stroke="black"
    strokeWidth={1}
  />
);

const shouldShowLegend = true;

const LegendWithLine = props => (
  <Fragment>
    <VictoryLegend {...props} />
    <VerticalLine x={10} y={0} length={100} />
  </Fragment>
);

class App extends React.Component {
  render() {
    return (
      <VictoryChart>
        <VictoryLine />
        {shouldShowLegend && <LegendWithLine />}
      </VictoryChart>
    );
  }
}
```

## CodeSandbox Solution
https://codesandbox.io/s/issue-1498-solution-2ilkl

Let me know if this doesn't solve your problem!
