### ISSUE TITLE
Cannot zoom in <div><svg>...</svg></div>

### ISSUE THREAD

**Issue by 6axter82** [FormidableLabs/victory#1513]
# Bugs and Questions
Why I can"t do any zoom or use brush in a case when my Charts are within div and svg?

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I can't zoom or do anything on charts when inside an svg tag. I need to use div and svg as I want to calculate the width of the div on changing the window width and give it back to charts. It looks like resizing works if I put the charts into the svg. But than the zoom and brush are not working within the svg. And the placement of charts is misaligned.
Commenting the svg out, brings the placement and allows zoom with brush. But the resizing is gone.
  
### Reproduction

[https://codesandbox.io/s/floral-field-7ozn0?file=/src/App.js](https://codesandbox.io/s/floral-field-7ozn0?file=/src/App.js)

removing the svg solves the zoom and brush but the responsiveness of the page is gone. But I need it.

**Comment by 6axter82** [comment]
removing the svg solves the zoom and brush but the responsiveness of the page is gone.

**Comment by boygirl** [comment]
It looks like you have `standalone={false}` set on your `VictoryChart` When this is the case, Victory will render its `groupComponent` (usually <g>) rather than its `containerComponent`, so it won't be rendering those evented containers (brush, zoom, etc). You can leave it as `standalone={true}`, but then you will end up with nested svgs.  Evented containers rely on finding the first parent svg of any events, and using that for correlating event coordinates to svg coordinates, so they need to be rendered within an svg that is exactly the same size as the chart. For this reason, we only render them when Victory also renders its own top level svg, since they would be incredibly error prone otherwise.

The sandbox you linked to had errors, so I wasn't able to test the effect of changing the `standalone` prop. I'm going to close this issue, since it is more of a limitation in how the library works, but please do open another one if you can't find a workaround for what you're trying to do. 

One of my colleagues created a write up about dynamic svgs with victory. Maybe this will help you: https://codesandbox.io/s/keen-spence-ofh53

**Comment by 6axter82** [comment]
@boygirl try running it again pls: [https://codesandbox.io/s/floral-field-7ozn0?file=/src/App.js](https://codesandbox.io/s/floral-field-7ozn0?file=/src/App.js)
