### ISSUE TITLE
change font size in VictoryGroup

### ISSUE THREAD

**Issue by qwwwpp** [FormidableLabs/victory#1561]
# Bugs and Questions

### Checklist

- [ x ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x ] I am using the latest version of Victory

- [ x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I am having trouble changing the font size of the labels on the y axis (eg. "xxxx1" "xxxx2" in codesandbox.io  example).
`style={{ data: { width: 6 }, labels: { fontSize: 5 } }}` doesn't work in VictoryGroup or VictoryBar

### Reproduction

https://codesandbox.io/s/basic-victory-example-bj529?file=/index.js
# Feature Requests

**Comment by NgoKnows** [comment]
I believe in order to style the axes, you will need to explicitly render <VictoryAxis />, which <VictoryChart> does automatically if none are passed to it as children. You're also looking for `tickLabels` not `labels`.

I've updated your example:
https://codesandbox.io/s/basic-victory-example-p12s0?file=/index.js
