### ISSUE TITLE
High Cpu usage even when a victory dependency is not displayed

### ISSUE THREAD

**Issue by klima-markus** [FormidableLabs/victory#1659]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
A react application:
* has a high cpu usage when importing (**NOT** using) a victory chart
* gets re-drawn even only by importing a victory chart
### Reproduction
Use the following example
```
import {
  VictoryChart,
} from "victory";

function App() {
  return <div className="App">victory bug</div>;
}
```
The `VictoryChart` is only imported, not used, BUT: this still triggers a redraw and a higher cpu usage (its 5-7% within chrome instead of < 1% without the import)
If you remove the import, this won't happen.

When you use chrome and monitor the app, this happens when you import something from victory:
<img width="528" alt="import" src="https://user-images.githubusercontent.com/66319019/89400858-c2753380-d714-11ea-8b4c-5030db917d62.png">

It looks like this, if you don't import it:
<img width="526" alt="no-import" src="https://user-images.githubusercontent.com/66319019/89400866-c43ef700-d714-11ea-8d28-dd027f78bb2b.png">

The issue is getting bigger, if you have a more complex application. In our single app application, the cpu usage is getting up to 30%, even if we won't show any chart

**Comment by toshok** [comment]
Noticed this locally as well, although the CPU % was lower (10% in my case.)

This is happening because of the following construct: https://github.com/FormidableLabs/victory/blob/ec6ebc9642a9ba4adc1e82c683d078ffaf98b66f/packages/victory-core/src/victory-util/timer-context.js#L9

the two `new Timer`'s there each create a d3-timer here: https://github.com/FormidableLabs/victory/blob/ec6ebc9642a9ba4adc1e82c683d078ffaf98b66f/packages/victory-core/src/victory-util/timer.js#L8

d3-timers start in an "on" state, and (given that there's no delay specified), the callbacks are invoked every frame.

my suggestion would be to either (if this is possible) start the timers in an _off_ state until there are subscribers, or change the `createContext` to not actually create timers for the defaults.

**Comment by hrspandya** [comment]
Hey Guys any update on this issue? Can we please prioritize this?

**Comment by beccanelson** [comment]
A few of us have tried to reproduce this, and so far we haven't seen this performance impact with the current release. Is this still happening? If so, a sandbox link or any other details you can provide such as Chrome version, etc. would be helpful!

**Comment by hrspandya** [comment]
We are using "victory": "^35.0.8", and chrome Version 87.0.4280.67 (Official Build) (x86_64)

For above configuration, we are able to reproduce this issue.

**Comment by boygirl** [comment]
@hrspandya Can you try using `victory@35.3.4` or later? That version includes an improvement to how animation timers are stopped and cleared: https://github.com/FormidableLabs/victory/pull/1738.

**Comment by hrspandya** [comment]
Seems to be working fine now after updating to later version. Will do more testing.
