### ISSUE TITLE
Setting state in createContainer combination of zoom with either brush or cursor causes issues

### ISSUE THREAD

**Issue by craigericlewis** [FormidableLabs/victory#1660]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Setting component state in a `createContainer` combination of `zoom` and either `brush` or `cursor` causes issues with the scaled value of the cursor position.

### Reproduction

[Example](https://codesandbox.io/s/cocky-moon-t54zg)
Brushing works fine prior to zooming. Zooming into the graph and attempting to brush causes issues. Setting `changeState` to false and attempting to zoom and then brush works perfectly fine.

**Comment by Codesleuth** [comment]
I am experiencing this same issue with a custom container component:

```ts
const ContainerComponent = createContainer<
  VictoryZoomContainerProps,
  VictoryCursorContainerProps
>('zoom', 'cursor');
```

With the above component, setting the `zoomDomain` prop causes any state updates within `onCursorChange` to flow through a complete cycle but then move the cursor when the container is re-rendered. Removing the `zoomDomain` prop fixes the issue, but in my case it's a blocker.

Things I've tried that do not work:
* Memoizing the value for the `zoomDomain` prop
* Change the order of the `createContainer` (e.g. `'cursor', 'zoom'`)
* Storing the cursor value and setting it with `defaultCursorValue`

Any insight or workarounds for this issue would be a great help. If there's a way to use events directly and draw my own cursor, rather than use the cursor container, I would appreciate any guidance.

**Comment by justindomingue** [comment]
Bump. Is there a workaround for this?
