### ISSUE TITLE
VictoryTooltip doesn't expand to label component size

### ISSUE THREAD

**Issue by furysheep** [FormidableLabs/victory#1681]
Thanks for making a great library. I'm going to customize the tooltip text in the chart while mixing the y values.

```
<VictoryChart
        height={450}
        padding={{ top: 100, bottom: 20, left: 50, right: 50 }}
        // style={chartStyle}
        containerComponent={
          <VictoryVoronoiContainer
            voronoiDimension="x"
            labels={({ datum }) => datum.y}
            labelComponent={
              <VictoryTooltip
                labelComponent={
                  <VictoryLabel
                    text={({ activePoints }) => {
                      return activePoints.map(({ y }) => y).join(" - ");
                    }}
                  />
                }
              />
            }
          />
        }
      >
```

But tooltip area doesn't expand as the label grows. How can I fix this?

![Screen Shot 2020-09-09 at 11 31 50 PM](https://user-images.githubusercontent.com/36306764/92633682-f1269100-f2f4-11ea-8092-46c7c151a920.png)

https://codesandbox.io/s/basic-victory-example-forked-vbl4r

**Comment by boygirl** [comment]
It looks like the size of the label is based on the labels defined by `labels={({ datum }) => datum.y}` rather than taking your custom `text` into account. I see that you've defined the `text` prop on the tooltip's `labelComponent` rather than directly on `VictoryTooltip`. I'm guessing because `VictroyVoronoiContainer` is overriding the `text` prop on `VictoryTooltip` when it's given. I will fix that bug, which should let you define `text` directly on `VictoryTooltip`, where it will correctly influence the dimensions of the tooltip.
