### ISSUE TITLE
Add a Vertical Line to Bar Chart -using VictoryCharts as script tag 

### ISSUE THREAD

**Issue by iwannabetall** [FormidableLabs/victory#1682]
How do I add a vertical line to a custom graph?  specifically a bar chart?  

I'm using the not using the Victory Chart wrapper so I can build a custom chart.   I'm using the CDN for a script tag in my pug template (not using webpack or typical create-react-app set up) like this : script(src="https://unpkg.com/victory@35.0.9/dist/victory.min.js"), so I had to create the VictoryLine and VictoryBar components like this before rendering them later (if there's an easier way, please let me know because I haven't figured out an easier way to use the components)

    function DottedLine(props) {
        console.log(props)  // prints repeatedly 
	    var Line = React.createElement(Victory.VictoryLine, 
		{data: props.data, 
			style: 
			{ parent: {border: '1px dashed #ccc'},
				data: { stroke: '#c43a31'},
				x: props.x,  // data accessors
				y: props.y,  // 
			},			
			standalone: props.standalone == 'merge' ? false : true,
		}
	    )
	return Line
}

    function DataViz(props) {
	   return (
		<div className='svg-container'>
			<svg className='svg-content' id='lead-tracker' preserveAspectRatio='xMidYMid meet' viewBox='0 0 500 300'>
				{props.data.map((row)=> (
					<DottedLine data={row} x='elapsedSeconds'  standalone={'merge'}/>	
					))}				
				<VictoryBar shots={shots} x='elapsedSeconds' y='margin' standalone={'merge'}>
				</VictoryBar>
				
			</svg>
		</div>
		)
}

I can get one vertical line plotted, but I can't figure out from the console if it's located on the x axis where I wanted it or if it's a random vertical line in the middle.  The console log in DottedLine runs multiple times, but I only see one line, and my only guess is that it's just on top of each other.  The data is an array of arrays (length 2 to get several vertical lines) and I even tried renaming the attributes w/in the objects so I wouldn't need a data accessor, and still no luck.

**Comment by boygirl** [comment]
Sorry for the delay. It looks like you have your data accessor props mixed into your style prop accidentally. Another issue you are likely having is that your `VictoryLine` components and `VictoryBar` components have no guarentee of using the same domain and scale, so depending on your data, they may not appear together. Even for a custom chart, I would recommend using the `VictoryChart` (style the axis invisible) or `VictoryGroup` (no axes at all) wrappers so that all your children will be using the same domain and scale. Then you will be able to do something easy like `<VictoryLine x={() => 0.5} />` to create a vertical line.
