### ISSUE TITLE
Making graph fill 100% width and height of parent element?

### ISSUE THREAD

**Issue by fdb15180** [FormidableLabs/victory#1684]
I understand changing the height and width attributes sets the aspect ratio of a victory component's svg container. How is this done dynamically to adjust to the parent? 

I have decided to resort to using refs in React to get the parent container dimensions.

**Comment by boygirl** [comment]
@fdb15180 that's an interesting question. The best way to do it is how you are already going about it, by adjusting the height and width to match the parent dimensions. This way, the aspect ratio is always correct in your svg. Based on this issue, however, I'm adding an optional `preserveAspectRatio` prop to `VictoryContainer` that will take a string. This will allow you to set your own `preserveAspectRatio` for the svg that `VictoryContainer` renders, so you will be able to use `preserveAspectRatio="none"` if you want. The text may end up looking strange because of the possibility for stretched scaling, but the chart will always fill its container. This might be the right thing for some dashboards.
