### ISSUE TITLE
Tooltip orientation and pointerOrientation adjust to nearest point on chart

### ISSUE THREAD

**Issue by jjoselv** [FormidableLabs/victory#1694]
# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

It would be awesome if there would be an option on the tooltip/voronoi where both the tooltip pointer and the tooltip itself will follow the mouse position inside a victory bar and the tooltip orientation and pointerOrientation would change to prevent the tooltip from overlapping the cursor position, maybe pointing to nearest point on chart (sorry if I don't explain myself very well)

**Comment by boygirl** [comment]
@jjoselv I'm not sure exactly what you're looking for, but I think something similar already exists:

![mouseFollowTooltipsGif](https://user-images.githubusercontent.com/3719995/94881608-c7a3e580-041a-11eb-8914-c8f0d5b9026f.gif)

Is that the behavior you're looking for? Or maybe approximately that but with an offset added so that the pointer is just outside the tooltip rather than centered in it.

**Comment by jjoselv** [comment]
It is similar to that, bit not quite, could you apply that to a bar chart instead of a scatter? Maybe that way you can see what I mean.
