### ISSUE TITLE
VictoriyArea does not support style prop as function

### ISSUE THREAD

**Issue by miaowang** [FormidableLabs/victory#1700]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When you use a VictoryArea with a style prop as function, the data style function is not working.
Same is working for VictoryScatter. See Reproduction.

### Reproduction

Does not work
```
<VictoryArea
    style={{
    data: { fill: ({ datum }) => datum.x > 3 ? "green" : "red" }
	}}
    data={sampleData}
    labels={({ datum }) => datum.x}
  />
```

with error `TypeError: Cannot read property 'x' of undefined`

Following does work
```
  <VictoryScatter
    style={{
    data: { fill: ({ datum }) => datum.x > 3 ? "green" : "red" }
	}}
    data={sampleData}
    labels={({ datum }) => datum.x}
  />

```

**Comment by boygirl** [comment]
@miaowang `VictoryArea` renders just a single path element for the entire dataset rather than individual elements for each data point like `VictoryScatter`. Because of this, `VictoryArea` doesn't pass any `datum` to the element it renders, but instead passes `data` the entire dataset. So, the style function does work, but doesn't have access to `datum`. What you're seeing is the expected behavior for the component. I'm apologize for the confusion. I will work on explaining this better in the documentation.
