### ISSUE TITLE
Tooltips don't work in React strict mode

### ISSUE THREAD

**Issue by smashercosmo** [FormidableLabs/victory#1702]
### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Labels don't work in React strict mode with react@17.0.0-rc.2

### Reproduction

If you remove StrictMode, labels start working

https://codesandbox.io/s/icy-architecture-z2q6i?file=/index.js

**Comment by boygirl** [comment]
@smashercosmo thanks for this issue. Based on the updates we have already made, I would expect Victory to work in strict mode (no unsafe lifecycle methods or legacy api use), so that just leaves potentially some side effect in a render lifecycle method, which is going to be quite a bit harder to track down and address. I've changed the title of your issue, since it does seem to only impact tooltips, not static labels, and I would guess is related to Victory's event system.

**Comment by boygirl** [comment]
As a temporary measure, it looks like `VictoryVoronoiContainer` works.

https://codesandbox.io/s/boring-wozniak-c8r8i?file=/index.js

**Comment by boygirl** [comment]
Also it looks like this is related to https://github.com/FormidableLabs/victory/issues/1511. I'm going to keep this issue open and close the others as duplicates since this one has the most straightforward reproduction.

**Comment by smashercosmo** [comment]
Updated React to 17.0.0-rc.3 and Victory to the latest version in reproduction template. Problem still exists.

**Comment by boygirl** [comment]
@smashercosmo we figured out what's causing this: 

Strict mode double invokes all it's render lifecycle methods twice in development. https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects 

Victory's event system uses a `shouldComponentUpdate` to prevent unnecessary renders when new props wouldn't cause an updated event state. Invoking it twice means the second invokation _always_ returns `false` because we cache the event state for comparison. This should only happen in development, not production, but even so, it needs to be fixed. I'm going to see what the perf implications are to removing that check, and look for work arounds.

**Comment by smashercosmo** [comment]
Oh, yeah, that famous double render 🙂 Some much confusion is has caused already
