### ISSUE TITLE
VictoryLine overflow halves strokeWidth

### ISSUE THREAD

**Issue by Leelu55** [FormidableLabs/victory#1735]
- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))
- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question
- [x] I am using the latest version of Victory
- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

![image](https://user-images.githubusercontent.com/7963034/97859194-8d22b680-1d00-11eb-8eb0-aeb2dd3b3120.png)

Using VictoryLine component there seems to be an overflow problem as the strokeWidth of horizontal strokes at top and bottom of the chart is halved. How can I prevent this from happening? 

You can reproduce the problem here:
https://codesandbox.io/s/strange-sid-mp0je?fontsize=14&hidenavigation=1&theme=dark

Thanks!

**Comment by boygirl** [comment]
@Leelu55 `VictoryLine` renders into a clipped `groupComponent` by default. This is what enables it's curtain style entrance animations. If you're not animating `VictoryLine` you can replace its `groupComponent` with a plain `<g />`. If you do need the entrance animation, you can use the `clipPadding` prop on `VictoryClipContainer` so that it doesn't cut into your stroke. 

example:
```
<VictoryLine
  groupComponent={<VictoryClipContainer clipPadding={{ top: 5, bottom: 5 }} />
  ...
/>
```

**Comment by Leelu55** [comment]
@boygirl Thank you very much! 
Setting the ```clipPadding``` on the ```VictoryClipContainer``` worked. 
Problem solved. 

The solution to reuse: 
https://codesandbox.io/s/flamboyant-moon-nm8k3?fontsize=14&hidenavigation=1&theme=dark
