### ISSUE TITLE
How to achieve the following chart?

### ISSUE THREAD

**Issue by appjitsu** [FormidableLabs/victory#1759]
Please ignore the middle portion. What I'm most concerned with is the gauge portion with the colored segments and the circle signifying the exact value. Thanks.

<img src="https://i.ibb.co/yRdv8gs/Screen-Shot-2020-12-14-at-1-50-37-PM.png" alt="Screen-Shot-2020-12-14-at-1-50-37-PM" border="0">

**Comment by boygirl** [comment]
@appjitsu apologies for the delay. You can do something like this with polar charts using `VictoryBar` for the gauge portion and `VictoryScatter` for the dot. You will make use of the `startAngle` and `endAngle` props so that only a portion of the circle is rendered. Here's an example that should help you:

https://codesandbox.io/s/polar-bar-gauge-chart-8b1ew
