### ISSUE TITLE
How canI have a default data on y axis

### ISSUE THREAD

**Issue by mingbackmountain** [FormidableLabs/victory#1768]
<img width="327" alt="Screen Shot 2564-01-05 at 10 05 22" src="https://user-images.githubusercontent.com/25886138/103602168-e5af4380-4f3d-11eb-9d5d-b24665734a18.png">

Before my data come from API, the default data is 0. However, the display on the graph seems wrong. How can I fix this problem?

**Comment by boygirl** [comment]
@mingbackmountain In Victory it's not possible to have a single point for a domain, so by default, Victory will use `[0, VERY_SMALL_NUMBER]` when there isn't data. If you'd like to do something different, you can set the `domain` prop manually until your data loads, or change the `tickFormat` on your dependent axis so that it returns an empty string when values are less than a certain threshold.

**Comment by mingbackmountain** [comment]
@boygirl Can you give me some guidelines to provide a control tickFormat on your dependent axis so that it returns an empty string when values are less than a certain threshold.

Here is my code:

<img width="654" alt="Screen Shot 2564-01-05 at 14 49 49" src="https://user-images.githubusercontent.com/25886138/103620021-5b7ad580-4f65-11eb-8998-d2348f286477.png">

**Comment by boygirl** [comment]
You would add something like this to your dependent axis
```
tickFormat= {(t) => t < 0.1 ? "" : t}
```
Here's more documentation about the `tickFormat` prop:
https://formidable.com/open-source/victory/docs/victory-axis#tickformat
