### ISSUE TITLE
Can not  fill Area graph by using data.fill

### ISSUE THREAD

**Issue by mingbackmountain** [FormidableLabs/victory#1786]
<img width="229" alt="Screen Shot 2564-02-03 at 01 20 45" src="https://user-images.githubusercontent.com/25886138/106644889-458d1e80-65be-11eb-8363-1448d6438635.png">

I'm using typescript and try to fill my area graph with a particular colour base on the data, However, after applying the code like this

<img width="257" alt="Screen Shot 2564-02-03 at 01 20 08" src="https://user-images.githubusercontent.com/25886138/106645037-6fdedc00-65be-11eb-9c4e-7b727ba19bca.png">

The colour of my graph is turning black

<img width="1286" alt="Screen Shot 2564-02-03 at 01 20 50" src="https://user-images.githubusercontent.com/25886138/106645097-7ff6bb80-65be-11eb-871b-f6b81ebc84c8.png">

Can anyone please point out where I was wrong?

**Comment by boygirl** [comment]
Hi @mingbackmountain! The props supplied to the primitive components that `VictoryArea` uses to render includes `data` with is an array of `datum` objects. It looks like you have a fill set on individual `datum`, but you are trying to access it like `data.fill` which is a property that does not exist. You could try `data[0].fill`. Since you're adding `fill` to individual `datum`, though, I expect you might be trying to have your area render with multiple colors. Unfortunately, `VictoryArea` renders just a single path for an entire data set, so you can't do this as easily as you could for a component like `VictoryBar` that renders a an individual element for each `datum`. Check out this guide for using gradient fills for a work around: https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory
