### ISSUE TITLE
Extended Domain

### ISSUE THREAD

**Issue by han-yan-ds** [FormidableLabs/victory#1791]
# Bugs and Questions

### Checklist

- [X ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X ] I am using the latest version of Victory

- [X ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

How do I allow an "extended domain"?  For example, in this screenshot, I want the auto-generated domain to include a tick for 20%
![image](https://user-images.githubusercontent.com/5281743/107568588-74018f80-6ba4-11eb-882d-a8b12554ece8.png)

I'm preferably not looking to hardcode domains because that'll involve rewriting domain-auto-generation logic that's already in the code (and most likely better written).

**Comment by boygirl** [comment]
@han-yan-ds you have a couple options. You can explicitly set the `tickValues` on your dependent `VictoryAxis` component so that they always include 20%. The domain will automatically adjust to include it if you do. You might also try using the `tickCount` prop if you're not sure what your `tickValues` might be, but you're wanting more ticks to show.  Or if you just want to give a bit more space above your bars, but the values are variable, you can use the `domainPadding` prop of your parent Victory component (probably `VictoryChart`).
