### ISSUE TITLE
Time series scaling on independent axis doesn't work when defining dependent axis

### ISSUE THREAD

**Issue by evrom** [FormidableLabs/victory#1801]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

The time series scaling doesn't work when 

### Reproduction

Working time series scaling on independent axis, but bad scaling on dependent axis (also the `1` in `12,000` is cut off from the view)

https://codesandbox.io/s/relaxed-river-7o580?file=/index.js

Working dependent axis using numeral.js to scale. But independent axis is missing:

https://codesandbox.io/s/wonderful-lake-rtzk0?file=/index.js

Add component for independent axis without props. Now time scaling and display is broken:

https://codesandbox.io/s/naughty-fermi-gvdgz?file=/index.js

**Comment by boygirl** [comment]
Hi there!  Thank you for including codesandbox reproductions. That helps a ton!

In https://codesandbox.io/s/relaxed-river-7o580?file=/index.js I don't see any issue with your y axis scaling. If your tick labels are being cut off by the edge of your chart, you can try altering the  `padding` prop on your chart, or one of the other strategies here: https://formidable.com/open-source/victory/docs/faq/#my-axis-labels-are-cut-off-how-can-i-fix-them

in https://codesandbox.io/s/wonderful-lake-rtzk0?file=/index.js  The issue is that you have defined a single axis. You can correct this by adding a second `VictoryAxis` child component. More explanation here: https://formidable.com/open-source/victory/docs/faq/#why-is-victorychart-rendering-only-one-axis

In https://codesandbox.io/s/relaxed-river-7o580?file=/index.js I think there is a little bug. Victory should be automatically inferring the scale of your independent axis. Since it isn't doing this automatically, you can tell it to use a time scale axis by setting `scale={{ x: "time" }}` on `VictoryChart`
