### ISSUE TITLE
[Question]How to add custom component in VictoryAxis (x, y axis)

### ISSUE THREAD

**Issue by catmans1** [FormidableLabs/victory#1817]
# Bugs and Questions

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Thank you for awesome library.
I have a question:
How can we implement the custom component in VictoryAxis (x, y axis) like this:

<img width="607" alt="Screen Shot 2021-04-09 at 4 17 19 PM" src="https://user-images.githubusercontent.com/9440600/114143436-1e9cf100-994f-11eb-9c21-40d48e65d37f.png">

Thank!

**Comment by boygirl** [comment]
@catmans1 it looks like you want shapes or icons in place of tick labels.  In this case, you would provide a custom `tickLabelComponent` that renders an svg path or similar element instead of a text element. `VictoryAxis` will pass several props into its `tickLabelComponent` including `x` and `y` coordinates, and it wil be up to your custom component to figure out how to use them. 

Here's an example to help you get started:
https://codesandbox.io/s/custom-tick-label-ukvoz

note that any elements you use in your custom component will be rendered inside of an `svg` element, so they need to be compatible with svg, or use the `foreignObject` tag.

**Comment by vfa-khuongdv** [comment]
@boygirl : I want to custom VictoryAxis like example below, but it not working on react-native
Ex: https://codesandbox.io/s/custom-tick-label-ukvoz
