### ISSUE TITLE
unminified distribution file uses evals

### ISSUE THREAD

**Issue by privatenumber** [FormidableLabs/victory#1818]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

It was brought up [here](https://github.com/privatenumber/minification-benchmarks/issues/10#issuecomment-817172732) that the victory non-minified distribution was built using Webpack in development mode and hence puts every module in `eval`s: https://unpkg.com/victory@35.4.13/dist/victory.js

I understand this isn't the main entry-point for apps/bundlers, but just want to point out that although this is fine for local development of the library, it's not good for consumers if accidentally used in production.

Instead, I recommend building it in Webpack's "production mode" and turning off minification, and also putting sourcemaps in a separate file. That way, if imported by an app, it can be bundled and minified properly. If loaded via HTTP, I would also imagine this will be a smaller size as other optimizations would be enabled, and the source map would be much more accurate and only loaded when dev tools is open.

**Comment by ryan-roemer** [comment]
Thanks @privatenumber !

Oh my, yep -- we need to adjust that. @boygirl suggest we do something like:

```js
config.devtool = false
```

in https://github.com/FormidableLabs/victory/blob/main/config/webpack/webpack.config.dev.js#L11

While we're there, I think we can probably remove the `SourceMapDevToolPlugin` in https://github.com/FormidableLabs/victory/blob/main/config/webpack/webpack.config.dev.js#L20-L22 since we don't actually publish source maps...
