### ISSUE TITLE
styled-components Bar has generated classes overridden by default styles

### ISSUE THREAD

**Issue by tvsmk** [FormidableLabs/victory#1849]
### The Problem

When using styled-components for a `Bar` component, the styles in the generated class are overridden by the default bar styles.

### Reproduction

Sandbox created here: https://codesandbox.io/s/cool-lumiere-gdqnj?file=/index.js

### Description

When styled-components is used for a custom `Bar` component, the styles that are generated by styled-components get overridden by the default styles applied to `Bar`.

If you inspect the bar elements in the sandbox you can see that the styled-components class is being applied to it, but the properties that are also defined in the default styles are being overridden, such as `fill` and `stroke`.

I have seen a similar issue was raised about disabling default styles (https://github.com/FormidableLabs/victory/issues/559) and the workaround is to supply a style object to the custom component with the affected properties set to null e.g. `style={{ fill: null }}`. This does work, however I would have expected the `Bar` component not to supply the default styles if the properties are covered by classes. Perhaps I am missing something, thanks for your time.

**Comment by boygirl** [comment]
Hi @tvsmk, 

Victory uses inline svg styles because they are unopinionated, the same on native and web, and straightforward to use as a default. Victory is also built around the idea of sensible defaults, and one of the things this means is that we want components to render _something_ reasonable even when very few props are provided. For most elements this means giving them a default stroke / fill. Unfortunately this creates a specificity for users like yourself who want to use something like styled-components (which I personally adore). Your solution of nulling out the inline styles you don't want is a workable one. Victory is not really clever enough to know when a className implies styles, but I would be open to adding a `disableInlineStyles` prop to components and primitive components.  It could be used like so:

inline styles disabled for both data and labels
```jsx
<VictoryBar
  disableInlineStyles
  ...
/>
```
or disable inline styles only for the data component
```jsx
<VictoryBar
  dataComponent={<Bar disableInlineStyles />}
  ...
/>
```

What do you think? Also, would you be interested in giving it a shot?

**Comment by tvsmk** [comment]
Hi @boygirl, thanks for your quick response!

I completely understand that you would want to render at least something if not much is provided. The `disableInlineStyles` prop sound like it would do the trick for what I need.

I can have a go at making the change, although I'll be honest in that I've never tried putting anything on GitHub before. That and work commitments might delay it somewhat, so please bear with me! I'll let you know if I get anything working.

**Comment by tvsmk** [comment]
Hi @boygirl ,

I had a go at making the change, forking the repository and doing it there. I added the prop and the logic to return an empty object for the style to the `Bar` render method. However it still renders with default styles. The prop on the `VictoryBar` component doesn't get passed down either, I'm probably missing something. Here is the link to the branch with my attempted fix on it (https://github.com/tvsmk/victory/tree/feature/disable-inline-styles). I added a storyboard and a bit on the Bar demo page. I'm in a little over my head so any advice would be appreciated. Thanks

**Comment by boygirl** [comment]
@tvsmk actually, I think it works! But also, I think this points out that we can get by with fewer default styles since paths render with black fills by default. `Bar` does have a default `stroke` that is set to match the fill, but if no fill is given, we can skip that too. Let me do a bit of investigation to see which of the default styles we can just drop.

**Comment by tvsmk** [comment]
@boygirl that's good! Sorry about this, but I have had to re-make the forked repository as I accidentally committed using my work git account which had personal details on it. If you could use a fresh pull that would be great. Thanks https://github.com/tvsmk/victory/tree/feature/disable-inline-styles

**Comment by boygirl** [comment]
Hi there! Would you mind opening a draft PR against the upstream victory repo to make it easier to to review your changes?

**Comment by tvsmk** [comment]
I have created it here:  https://github.com/FormidableLabs/victory/pull/1856.

I don't think the prop on `VictoryBar` works, could you point me in the right direction as to where I can pass it down to the `Bar` component?
