### ISSUE TITLE
Use `theme` instead of `style` prop

### ISSUE THREAD

**Issue by nikgraf** [FormidableLabs/victory#185]
This would be breaking change. The reason for this is that style already has a meaning for React elements and many React components follow the same pattern. Having a property `style` that behaves differently for victory components than the established standard your life as a developer gets harder.

Why `theme`? The original proposal came from @markdalgleish here: [react-themeable](https://github.com/markdalgleish/react-themeable).

originally created here: https://github.com/FormidableLabs/builder-victory-component/issues/33

**Comment by mxstbr** [comment]
I think that semantically, `theme` makes more sense. It makes it clear that this is a non-standard prop that the component will take care of, instead of a default prop that can only be passed js styles. Even though it might support CSS Modules, inline styles and everything else that will come.

It's an abstraction worth having for future proofing ui components, so your users won't have to worry about compatibility when the new-hot-thing-for-styling-of-React-Components™ comes around. We should abstract that away and take care of supporting it quietly.
