### ISSUE TITLE
Problem rending constant line in time charts

### ISSUE THREAD

**Issue by franjorub** [FormidableLabs/victory#1887]
# Bugs and Questions

### Checklist

- [ x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [ x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [ x] I am using the latest version of Victory

- [ x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

hi I had been helped with #1884 and worked awesomely but if the victory lines are just numbers

for example, I have this chart in x 'time' and y 'linear'

![image](https://user-images.githubusercontent.com/24401350/123040248-74ffc480-d3c1-11eb-8ba7-c3300ca1c333.png)

this is the VictoryLine

```jsx
<VictoryLine
          data={data}
          x="date"
          y="value"
          style={{
            data: {
              stroke: '#94ABFF',
              strokeWidth: 2,
            },
          }}
        />
```

now when I want to add just a line to make a range 

```jsx
<VictoryLine
          y={() => 1.2}
          style={{
            data: {
              stroke: '#FF4C00',
              strokeDasharray: '5 1',
              strokeWidth: 1,
            },
          }}
        />
```

the chart gets broken: 

![image](https://user-images.githubusercontent.com/24401350/123040478-ce67f380-d3c1-11eb-8a6e-24c13e72228c.png)

removing the constant line makes the Line with data render properly again.

thanks for your help

**Comment by boygirl** [comment]
@franjorub Oh, I see what you mean! The domain for the y function data turns out incorrect. It looks like it's including zero in unix time. Definitely a bug. I'll work on fixing this, but in the mean time, you can get around the issue by explicitly setting an x `domain` for your chart or even setting only an x `minDomain`.

Here's an example:
https://codesandbox.io/s/time-scale-annotations-fixed-zwigl

and more information on `domain` and `minDomain` props can be found here:

https://formidable.com/open-source/victory/docs/common-props/#domain
https://formidable.com/open-source/victory/docs/common-props/#mindomain

**Comment by franjorub** [comment]
thank you @boygirl! that worked perfectly
