### ISSUE TITLE
Different data visualization in case of string or number  data input types

### ISSUE THREAD

**Issue by SergiuszMinsk** [FormidableLabs/victory#1888]
### The Problem

In case if I have a large difference between data values and If I pass my data as strings instead of numbers, the visualization works fine, otherwise I have the opposite result.

### Reproduction

https://codesandbox.io/s/interesting-germain-8ny4i?from-embed=&file=/src/App.js (try to change data values 1000, 15, 25 from numbers to strings, we'll see the different data visualization)

**Comment by boygirl** [comment]
@SergiuszMinsk this is expected behavior. Victory does not interpolate strings to numbers, so changing your data to strings will result in a categorical bar chart. 

These two data sets will result in similar charts
```
data={[{ x: 1, y: "red" }, { x: 2, y: "green" }, { x: 3, y: "blue" }]}

data={[{ x: 1, y: "1" }, { x: 2, y: "22"}, { x: 3, y: "3.333" }]}
```
For each of these, Victory will create a stringMap that will map your string values (in the order they are given in your dataset excluding duplicates) to integers starting at 1 and then plot them, If you include axes, the `tickValues` will be the integers in your string map, and the labels will be the strings that correspond to the strings in your stringMap for a given integer tickValue.

If you use numeric values rather than strings, they will behave as numeric values, and their relative sizes will be reflected in your chart. So a y value of 1000 will look much larger than a y value of 10. If you have very different values, and you want to show differences in numeric data without having very large values totally overwhelm small values, you might consider using a log scale. for your chart.

I hope that explanation helps. I'm going to close this issue, but let me know if you have more questions.

**Comment by SergiuszMinsk** [comment]
@boygirl , thanks for the detailed answer. I'll try to explore the log scale possibility to fix my problem.
