### ISSUE TITLE
VictoryBar is not displaying first bar when data series X-value starts with 0

### ISSUE THREAD

**Issue by elderferreiras** [FormidableLabs/victory#1890]
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm setting up a VictoryBar chart where the data series starts at x=0. The data series is posted below.

```javascript
[
  { label: "0", x: 0, y: 10000 },
  { label: "1", x: 1, y: 5000 },
  { label: "2", x: 2, y: 1000 },
  { label: "3", x: 3, y: 500 },
  { label: "4", x: 4, y: 250 },
  { label: "5+", x: 5, y: 100 }
]
```

I'm using the `label` property in the data series to create the tickValues for the independent axis by setting the `tickValues` as `data.map((datum) => datum.label)`.

When I do that, the first item in the data series does not show up in the chart at all.

If I change the tickValues function to `data.map((datum) => datum.x)` instead, then the first item, the one that contains the `0` x value, shows up, but that's an undesired behavior because I need the last item to display a tick value such as "5+".

What is the underlying cause for the chart to behave this way?

### Reproduction

This is the sandbox with the odd behavior: https://codesandbox.io/s/gallant-firefly-kss0h?file=/src/App.js:919-951

The line with the `tickValues` prop in the VictoryAxis is `40.`

**Comment by boygirl** [comment]
@elderferreiras Hi there! I think the confusion is between `tickValues` and `tickFormat`. In your case, you are plotting numeric bars (i.e. 1, 2, 3, 4, 5), so your `tickValues` should be numeric. They could be the same values like `[1, 2, 3, 4, 5]` or something different like `[2.5, 5, 7.5, 10]`. The value would determine their _positions_ on the axis. The `tickFormat` will determine how they are displayed, so this is where you would want to use your strings.

Your particular case is confusing, because Victory computes a mapping for any strings it encounters (in `data` or `tickValues`) to integer values starting at 1 so that it can try to plot them on a linear, numeric scale. For folks working with categorical data like `["rent", "groceries", "utilities"]` this is desirable because it prevents their first data point from having a zero value which would cause it to overlap their y axis.

To prevent this you can do something like

`tickValues={data.map(d => d.x)}` and `tickFormat={data.map(d => d.label)}`
