### ISSUE TITLE
Custom CursorContainer labels positions

### ISSUE THREAD

**Issue by franjorub** [FormidableLabs/victory#1891]
Hi, it's possible instead of rendering the label next to the cursor render them in the axis as such. ?

![image](https://user-images.githubusercontent.com/24401350/123561615-780b0400-d777-11eb-9e85-5f559af04cf3.png)

thank you

**Comment by franjorub** [comment]
Also another question, its possible to render the same date format around the points as the time axis does? 
![image](https://user-images.githubusercontent.com/24401350/123562260-95da6800-d77b-11eb-851e-db5062826bd8.png)

**Comment by boygirl** [comment]
Hi @franjorub 

Yes, you can create a custom `cursorLabelComponent` for `VictoryCursorContainer` to use and provide it with the `y` value you want rather than having it match the cursor position. You can also use a custom formatter for your axis tick values, and use the same one for your cursor labels. 

here's a quick demo: 
https://codesandbox.io/s/cursor-label-position-and-formatting-12gwi?file=/index.js

**Comment by franjorub** [comment]
> Hi @franjorub
> 
> Yes, you can create a custom `cursorLabelComponent` for `VictoryCursorContainer` to use and provide it with the `y` value you want rather than having it match the cursor position. You can also use a custom formatter for your axis tick values, and use the same one for your cursor labels.
> 
> here's a quick demo:
> https://codesandbox.io/s/cursor-label-position-and-formatting-12gwi?file=/index.js

Hi related to the formatter, no, I don't want to use a custom formatter, I want instead get the already formatted value from the axis, or in other instance, use the same formatter that the axis uses. because the ranges can change to often (can be dates in weeks, days, months)
