### ISSUE TITLE
change behavior merging VoronoiContainer and CursorContainer

### ISSUE THREAD

**Issue by franjorub** [FormidableLabs/victory#1894]
Hi following the docs at https://formidable.com/open-source/victory/docs/create-container I created a new VictoryVoronoiCursorContainer, but it doesn't work as expected or as I would like, the reason is that the cursor is still free-floating instead of being attached to each Voronoi point, for example: 
![image](https://user-images.githubusercontent.com/24401350/124521804-df036b00-ddbe-11eb-8223-0f7dcef78494.png)

if I put the cursor on a point the cursor lines match the exact point, but I can still move the cursor around and the lines will follow it 

![image](https://user-images.githubusercontent.com/24401350/124521854-05c1a180-ddbf-11eb-8533-091a2d57dba3.png)

instead, I would like that the cursor lines to always matches the Voronoi coordinates 

![image](https://user-images.githubusercontent.com/24401350/124522052-cd6e9300-ddbf-11eb-8a7f-ff28ac6da6c3.png)

**Comment by boygirl** [comment]
@franjorub Hi there! If you'd like your cursor to stick to existing points rather than following the mouse position, the best way to do it would be to use `VictoryVoronoiContainer` by itself, and create a custom `labelComponent` that displays your tooltip and a cursor line. Your label should have access to the chart's scale and the current point, so you should be able to figure out from there the props your lines will need. Let me know if you need an example to help you get started.

**Comment by franjorub** [comment]
> @franjorub Hi there! If you'd like your cursor to stick to existing points rather than following the mouse position, the best way to do it would be to use `VictoryVoronoiContainer` by itself, and create a custom `labelComponent` that displays your tooltip and a cursor line. Your label should have access to the chart's scale and the current point, so you should be able to figure out from there the props your lines will need. Let me know if you need an example to help you get started.

hi @boygirl thank you always for your help, yes please, I have been using the library but go more in deep to things really custom I lost a little bit

**Comment by boygirl** [comment]
@franjorub here's an example that should help: 

https://codesandbox.io/s/voronoi-tooltip-with-cursor-line-r8si3
