### ISSUE TITLE
TextSize is not adapt with Chinese/Japanese characters

### ISSUE THREAD

**Issue by kunyan** [FormidableLabs/victory#1903]
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

The Chinese/Japanese characters are more wide than English characters. It can not display well in victory chart
<img width="1262" alt="Screen Shot 2021-07-15 at 1 09 28 PM" src="https://user-images.githubusercontent.com/752130/125752993-8cc2d3fe-7ebd-4137-bf2e-2a4da3a5105c.png">

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

Test characters: `我是一段测试文字`

https://codesandbox.io/s/mystifying-mendeleev-qzwub?file=/index.js

I found the all font width are calculated by https://github.com/FormidableLabs/victory/blob/main/packages/victory-core/src/victory-util/textsize.js

Looks it can not adapt with Chinese/Japanese characters width

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

**Comment by beccanelson** [comment]
Thanks for calling out this issue! @boygirl this might be a good one for us to look into, since the helpers in `textsize.js` have a lot of hard-coded spacings for various common fonts in the English alphabet, but there's no support for other alphabets. 

In the past, I have solved this in a pretty hacky way by hiding the svg initially via CSS, measuring the labels with `element.offsetWidth`, and then re-rendering the SVG with the updated spacing. Perhaps we can brainstorm some other ideas as well so we don't have to hard-code spacings for every international character set.

**Comment by beccanelson** [comment]
Related issue: https://github.com/FormidableLabs/victory/issues/1622

**Comment by becca-bailey** [comment]
Closing in favor of #2108
