### ISSUE TITLE
Top and bottom cornerRadius support for pie charts

### ISSUE THREAD

**Issue by edreyyo** [FormidableLabs/victory#1918]
I noticed support for this was added to bar charts [about 3 years ago](https://github.com/FormidableLabs/victory-core/pull/372).

Is it possible to add this support to [pie charts](https://formidable.com/open-source/victory/docs/victory-pie#cornerradius), too?

As posted in the [original issue](https://github.com/FormidableLabs/victory/issues/867), I'm hoping to achieve something similar to this:

![cornerRadius](https://user-images.githubusercontent.com/6125211/127625170-7fbda3c3-f2d8-4205-9275-0c64c4708184.png)

Many thanks 🙏

**Comment by beccanelson** [comment]
Both `VictoryPie` and `Slice` support a `cornerRadius` prop, as documented here. https://codesandbox.io/s/victory-pie-loader-example-4mp40

You might need to mess around with the `sliceStartAngle` and `sliceEndAngle` props for the pie slices to get them to overlap like they do in your example, but I think it is doable! Here's a quick codesandbox example. 

https://codesandbox.io/s/victory-pie-loader-example-4mp40

I'm closing this issue for now, since this appears to be supported already. But let me know if you have any other issues!

**Comment by edreyyo** [comment]
Belated thank-you for the reply, @beccanelson. Your suggestion works like a charm.

**Comment by edreyyo** [comment]
A belated thanks for the reply, @beccanelson. Your suggestion works like a charm!
