### ISSUE TITLE
VictoryTooltip not respecting theme styles when it is called in VictoryVoronoiContainer

### ISSUE THREAD

**Issue by becca-bailey** [FormidableLabs/victory#1984]
I am using a VictoryTooltip component for all the charts in my example app, found [here](https://victory-testing-dashboard.netlify.app/). I am giving each chart the same theme config, but the tooltip font is not updating in any charts where the `labelComponent` prop is in the `VictoryVoronoiContainer` component. (This pattern is documented [here](https://formidable.com/open-source/victory/guides/tooltips#multi-point-tooltips-with-victoryvoronoicontainer)). 

Current behavior: The tooltip has default styles even when I update the `tooltip` property in the theme
Expected behavior: The tooltip styling changes when I update the tooltip styles in the theme.

Reproduction: https://codesandbox.io/s/tooltip-theme-bug-fmlis

**Comment by beccanelson** [comment]
After a bit of initial investigation, I believe this is related to rendering the tooltip in the `VictoryPortal` component. `renderInPortal` defaults to true, but in the examples where the tooltip is inside the VictoryVoronoiContainer, it is rendering in the top SVG component rather than the portal SVG component.

This one is correct:

<img width="975" alt="Screen Shot 2021-10-05 at 11 01 35 AM" src="https://user-images.githubusercontent.com/13334214/136078342-32fe45b6-0ad8-4614-986d-256665a15295.png">

This one is incorrect: 

<img width="989" alt="Screen Shot 2021-10-05 at 11 03 09 AM" src="https://user-images.githubusercontent.com/13334214/136078337-f395c7e4-8ee0-46ff-8894-429dbc36d69e.png">
