### ISSUE TITLE
VictoryZoomContainer passive event listener issue

### ISSUE THREAD

**Issue by erbdani** [FormidableLabs/victory#2004]
When I'm using a VictoryZoomContainer whit touch control, I get a lot of `Unable to preventDefault inside passive event listener invocation.` errors.

I use the latest Victory, React and Chrome browsers.

Reproduce:
1. Click the codeSandbox 'Open in new window' button
2. Open Chrome responsive view.
2. Select a phone or iPad.
2. Touch the chart and the error is presented in the console.

https://codesandbox.io/s/kind-mccarthy-duxgu

**Comment by beccanelson** [comment]
@erbdani Thanks for flagging this issue! It seems to be related to the `onTouchMove` function in `VictoryZoomContainer` and passive event listeners, which don't allow `preventDefault`. More info [here](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md). I'll do a little more digging to see if there's a quick fix.

**Comment by becca-bailey** [comment]
Since we have had a few bug reports related to VictoryZoomContainer, I'm including them in this larger issue. #2111

**Comment by stevgouws** [comment]
Fwiw, in our case the issue only cropped up once we'd set

```js
<VictoryZoomContainer  style={{ touchAction: 'auto' }}>
```

as per https://github.com/FormidableLabs/victory/issues/1430, so that you could still scroll the page on mobile while when pressing on the chart.

Since we don't actually need the events I've just turned them off with the disable prop. So the listener never fires and we don't get the error anymore.

```js
<VictoryZoomContainer disable>
```
