### ISSUE TITLE
Cannot use custom font from Expo

### ISSUE THREAD

**Issue by CarlosHdez** [FormidableLabs/victory#2024]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I'm using a configuration for the `VictoryAxis` to use a custom font that wast loaded from expo, using `useFont`, I made sure the chart is rendered after the font has been loaded but I get an error on iOS indicating the font is not recognized
![Screen Shot 2021-11-17 at 14 50 39](https://user-images.githubusercontent.com/5401623/142280349-4a200741-f4e8-4281-b439-db9f5a2a7f65.png)

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

**Comment by zibs** [comment]
Hey @CarlosHdez this should already be possible, and I've made a small example repo for your [here](https://github.com/zibs/mvce-custom-fonts-native). I think your issue might've been around font naming, and you might want to just double check you were using the correct font name. Otherwise it will throw an error. 

I did notice that these custom fonts did not seem to work on snack, so I had to run it on the simulators/on device to actually see it work, just fyi!

Gonna close this out, but can re-open if you can provide a more detailed example for me to run!
