### ISSUE TITLE
Pan chart without redrawing everything

### ISSUE THREAD

**Issue by noisyscanner** [FormidableLabs/victory#2029]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When panning across a chart, I notice in dev tools that the SVG children are being redrawn constantly when the domain changes.
For our use case, we have 5 charts which will stack on top of each other and share the X axis. When panning one, the others should move in sync.

It would be great if instead of constantly redrawing the chart, it could just draw once and pan across with the browser. Is this possible within Victory?

The only alternate solution I could come up with, that I am trying right now, is drawing the graphs in a container with `overflow-x: scroll`, a width wide enough to include all data points, and having the axes fixed on the right. It does not seem like a great solution however.

### Reproduction

See [CodeSandbox](https://codesandbox.io/s/stupefied-murdock-u27c9?file=/src/App.js).

**Comment by becca-bailey** [comment]
Hi @noisyscanner, this isn't currently possible in Victory, but preventing these re-draws is on our roadmap for larger scale architectural improvements that we hope to address this year. Thanks for bringing this to our attention - I'm going to close this specific issue since we have other issues around this, but we will make sure this is addressed in a future release.
