### ISSUE TITLE
Cannot add data-testid or id for tests

### ISSUE THREAD

**Issue by RobelTekle** [FormidableLabs/victory#2040]
- Victory version 36.1.0
- React version 17.0.2

I'm trying to add some `data-testid` to Victory components in order to do some tests with Cypress. I have tried with several components: VictoryChart, VictoryBar, VictoryContainer. They never pass down the `data-testid` even if this prop is accepted by TypeScript. 

Could be very useful to have this feature, or at list to be able to passe down an `id`

**Comment by becca-bailey** [comment]
Hi @RobelTekle ! Victory currently only passes expected props down to child components from the top-level components. If you want a way around this, you can use component props like this:

```jsx
<VictoryBar dataComponent={<Bar pathComponent={<path data-testid="bar" />} />} />
```

It's a bit annoying, and we should investigate passing arbitrary props down so you don't have to use this workaround.

**Comment by pranay101** [comment]
Hi, I am new to open source and I would like to work on this issue. Please guide me further on what needs to be done.

**Comment by becca-bailey** [comment]
Hi @pranay101, I believe this issue is being worked on by another contributor, but feel free to check out our good first issues board if you would like to find a different issue to work on. Feel free to tag me directly if there are specific things you need help with! https://github.com/FormidableLabs/victory/projects/2
