### ISSUE TITLE
@types in victory-native

### ISSUE THREAD

**Issue by pedrocardoz0** [FormidableLabs/victory#2046]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm having issues to access type on victory-native, there are no @types available on npm

### Reproduction
![Captura de Tela 2021-12-28 às 15 56 43](https://user-images.githubusercontent.com/24881317/147598098-0c9042ee-b478-47c8-ae3a-9baa9cc0666b.png)

**Comment by becca-bailey** [comment]
Thanks for reporting this! There was an initiative a couple years ago to add type definitions to Victory, but I don't think that included Victory native. We will add this to the backlog, and we also will welcome help if you have time to contribute.

**Comment by zibs** [comment]
Hey @pedrocardoz0,

I've just taken a look at this, and it looks like there are typings for victory-native already exposed from within this package.

I've made a repro repo you can look at here: https://github.com/zibs/mvce-victory-native-ts. It's a simple expo app w/ TypeScript which then adds victory-native/deps and adds a few charts. I can see in my editor (vs-code) that the typings all seem to come through.

You can see the types of the victory-native lib [here](https://github.com/FormidableLabs/victory/blob/main/packages/victory-native/src/index.d.ts), although you can see a few remain untyped!

Let me know if this still doesn't work for you!

**Comment by pedrocardoz0** [comment]
@zibs

Indeed it has types inside the repo of victory-native, my case is a bit different, I'm working in a monorepo where the types are installed inside `node_modules` of a folder called `mobile`, and my problem is only when I'm working in another folder where it doesn't have the same `node_modules`.

![Captura de Tela 2022-01-18 às 19 04 31](https://user-images.githubusercontent.com/24881317/150026092-17e89a24-6f09-408d-86fb-eaef022b495d.png)

In this case, my types are living inside the `node_modules` in the `mobile` folder. And the problem is when I'm doing something in the `shared` folder, that has another `node_modules`. I thought that creating a new `@types` in DefinitelyTyped would solve my issue.

**Comment by zibs** [comment]
@pedrocardoz0 There's probably a way to configure the monorepo so that it can still pull the types without having to put things on `DefinitelyTyped`. If you can provide me a [mvce](https://stackoverflow.com/help/minimal-reproducible-example) of how you've set things up, I'd be happy to keep digging, but otherwise I'm not sure I can advise much further!

@becca-bailey What do you think about this? This issue seems to be more about a monorepo configuration rather than the types themselves. Is publishing to `@types` as well something we'd consider?

**Comment by becca-bailey** [comment]
I remember it being an intentional choice to maintain our own types here rather than pushing them to DefinitelyTyped. In this case, I would recommend updating the monorepo configuration. If it's not possible to add an alias pointing to the types, you could probably add your own .d.ts file for victory-native and pull in the existing types.
