### ISSUE TITLE
Investigate state management libraries

### ISSUE THREAD

**Issue by becca-bailey** [FormidableLabs/victory#2076]
In order to simplify Victory's state logic, we should add a shared state container. This could be a simple React context provider, or we could explore a solution like Recoil (which would require something like a `mapStateToProps` function to use with class components).

Requirements
- Easier to use than the current solution (passing state into nested components through props)
- Works with both function and class components
- Modular - easy to break apart and add to over time as new values are moved into shared state

**Comment by becca-bailey** [comment]
A few options for state management have been proposed, and these are currently the top two options (for me).
2. Redux
3. React context with `use-context-selector`. 

The advantage of something like Redux would be familiarity for contributors, dev tools, and a structured way to access data. Redux already provides a wrapper for class components. Possible downsides include bundle size and boilerplate. 

Context with `use-context-selector` would provide a bit more structure on top of React context. This would provide a bit more structure than context alone, but wouldn't affect the bundle size as much as Redux. 

As a part of this ticket, I think we should spike out each of these approaches, possibly choosing a single state value (like theme) to start with to avoid getting in too deep. This will help us to know whether there are any Victory-specific gotchas.

**Comment by matt-hernandez** [comment]
@becca-bailey Have you cracked any ground on this? Curious to know if you've got a gut feeling so far

**Comment by becca-bailey** [comment]
This is still in-progress! I'm hoping to make a little more headway this week with both of these spikes. Once these ideas are a  little more fleshed out, I'll open up a discussion thread to talk about some of the pros and cons of each.

**Comment by becca-bailey** [comment]
To repeat the suggestion from #1421, no matter what solution we use under the hood we should export some hooks that allow the consumer to access the state from any custom component.

**Comment by becca-bailey** [comment]
Another goal here should be to remove the static `role` property. This has created a lot of confusion when someone creates a custom wrapper component, and suddenly isn't receiving the same props. We should remove this property and access the shared state directly from the child component.

**Comment by matt-hernandez** [comment]
I want in on this! Lol

I have to explore the repo to get a sense of Victory's internals, but having been a Victory fan for years, and having used Redux for pretty much every project in my career, I'm down to help in any way. No problem if it's small exploratory stuff for either Redux or use-context-selector.

**Comment by matt-hernandez** [comment]
@becca-bailey So I've been poking around the code base and just trying things out and I had a few thoughts. I'm speaking as an outsider, so feel free to correct me on anything below.

If Redux is the attempted state management solution for Victory, the concerns about bloat from boilerplate are real. Some of that may be mitigated by using the new createSlice API in Redux. And if most or all of the Redux code is kept inside `victory-core`, it may be okay from a code organization standpoint. The only caveat I can think of which component is going to own the `Provider` component that will provide the store to any children. I could see `VictoryContainer` or `VictoryChart` doing that, but I also wonder whether this will have an impact on standalone components. Since most visualizations can be used standalone without a wrapper, if there is no wrapper on them to provide the store, they could break immediately when `connect` is called or if a redux hook is used.

As for using any variation of Context, that has the potential to bring less boilerplate. And with Context, standalone components won't break if they don't have a `Provider` wrapper for that context. They will always have _something_, even if it's the default value for the Context. The big caveat here is that using Context would be a custom solution, thus requiring a lot of effort with organization and management. Not saying it can't be done, but it may require a whole README of recommended steps and practices for how to use it and modify it.

Thoughts? I haven't attempted to implement either Redux or use-context-selector. Just spending most of my time trying to understand the workings of Victory as well as the issues that have lead up to this feature request. Appreciate any info.

**Comment by becca-bailey** [comment]
Just as an update on this - I have been doing some work in a separate repo to test out some general Victory improvements, including a shared state provider.

https://github.com/becca-bailey/victory-beta

Initially I used Redux for state management, but I didn't love it. I'm still open to suggestions here, but I personally found it easier to wrap my head around how to get and set shared state through context. I am using `use-context-selector` here, but I'm not sure whether I'm getting the performance benefits when it is wrapped in another custom hook. 

Currently, I have a `VictoryStateProvider` component that contains a lot of shared state.

https://github.com/becca-bailey/victory-beta/blob/main/packages/victory-core/src/state/victory-state-provider.tsx#L86

One of the challenges I encountered was the separation of concerns between state for the entire visualization, such as domain and scale, and state for a single chart such as the data and transition state for a single line. This solution includes two hooks for accessing this state - one for the overall state (`useVictoryState`) and one that accepts a chart ID and gets state for a single chart (`useChartState`). 

A real implementation would be more complex, as this beta repo doesn't currently include any event handling, and cut down a lot of the other complexity. 

My next step here will be to create a feature branch where we can begin to map out what a real re-write might look like for a single chart type. I'm going to continue with this approach that uses context and hooks, but perhaps we can also create a comparison branch for a side-by-side comparison if there are performance or syntax benefits of Redux or another more structured approach.

**Comment by matt-hernandez** [comment]
That makes sense. Redux is great when it's absolutely needed. But it's big and bloaty, and over time becomes an entirely separate initiative in a code base that needs constant care and maintenance. Personally, I favor your approach. State management with Context is more than possible, so long as it has guidelines and good docs. I will clone your beta repo soon when I have time.
