### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#208]
Some methods will stay like `defaults` but most will be replaced with JS built-ins to reduce package size.

- [ ] remove lodash from `victory-core`
- [ ] remove lodash from `victory-chart`
- [ ] remove lodash from `victory-pie`

consider adding specific util methods to replace commonly used lodash methods like `flatten`, `defaults` etc. so that we can optimize perf in one place.

**Comment by dpastoor** [comment]
given the potential for tree shaking in webpack 2 and/or the fact that you can create custom lodash builds via their cli, why don't you just pull the lodash functions you need rather than rewriting your own util methods? I would expect that it would be difficult to (significantly) beat the lodash methods given the amount of optimization that has gone in already, if any optimization was going to make a substantial different I'd expect you'd need to resort to directly replacing them with hand-tuned for/while loops directly in the code. 

Also, just food for thought, given larger datasets the 10-30% performance boost of lodash vs native may be a reasonable trade-off for size, especially if cherry-picking only the specific functions needed.

**Comment by ryan-roemer** [comment]
@dpastoor -- We were already doing one off imports of "just what we need". We did a by hand audit of our full JS bundles and it turns out that there is a _lot_ of the _base methods_ needed for top-level API functions that contributed to the massive size.

Thus, we're going to try and strike a balance of honing down our dependencies on lodash to "exactly what we need" in consideration of the core use cases, our browser support matrix (aka what React supports), and the flexibility we need in the future.

And don't get us wrong, we :heart: lodash and all the amazing work JDD and the rest of the contributors have done there!

**Comment by ryan-roemer** [comment]
Here's a demo of what the full bundle for a simple file like:

```js
import memoize from "lodash/memoize";

const foo = _.memoize((x) => "foo");

foo();
foo();
```

looks like: https://gist.github.com/ryan-roemer/12dcf16efe85f3a28588

Note that not all lodash functions have as much "base stuff" as `memoize`. But, we're trying to be judicious in what the full "cost" of each lodash function we use is.

**Comment by dpastoor** [comment]
@ryan-roemer  - thanks for the knowledge drop :-) 

Makes more sense too as to why you'd want some custom utils - esp for something like memoize where you may only need a specific subset of functionality.
