### ISSUE TITLE
Release docs appear to be stale

### ISSUE THREAD

**Issue by dlabrecq** [FormidableLabs/victory#2087]
We would like to know if there are breaking changes in the v36.x packages. However, https://github.com/FormidableLabs/victory/releases shows v35.9.0 as the latest release. Should the release docs reflect the change log?

**Comment by becca-bailey** [comment]
@dlabrecq Thanks for calling this out! We have had a bit of contributor turnover here recently, which means that some things have been falling through the cracks here a little more than usual. I'm adding an issue to add the [changesets release](https://github.com/changesets/action) github action to our codebase so that we can more easily keep our releases up to date with our changelog.
