### ISSUE TITLE
x axis label not showing completely even after applying angle in VictoryLabel

### ISSUE THREAD

**Issue by deepnrng** [FormidableLabs/victory#2110]
<img width="1792" alt="Screenshot 2022-02-15 at 9 47 18 PM" src="https://user-images.githubusercontent.com/91666873/154103242-4d72f0a5-1690-4d2b-a512-a376df289e90.png">

**Comment by becca-bailey** [comment]
Hi @deepnrng, because Victory renders in an SVG it has a size-constrained container that can cut off text if it overflows and and the container size itself hasn't been adjusted. Typically when this happens, you need to adjust the padding and the size of the SVG container. Adding this `padding` prop to the `VictoryChart` container should help resolve this issue. https://formidable.com/open-source/victory/docs/common-props#padding
