### ISSUE TITLE
Figure out how to safely update d3 packages

### ISSUE THREAD

**Issue by becca-bailey** [FormidableLabs/victory#2124]
We have had some repeated issues around upgrading d3 packages in Victory. For now, we have downgraded our `d3` packages and have them pinned at `^1.0.0` to resolve the issues that have come up, but it would be good for us to dive into this a little more, since these outdated packages put us at risk of security vulnerabilities. 

Related issues: #1595, #1970, #1963

**Comment by pgbradbury** [comment]
Any movement on this as the outdated packages have a security hole in them for denial of service via d3-color

[SNYK-JS-D3COLOR-1076592](https://app.snyk.io/vuln/SNYK-JS-D3COLOR-1076592)

**Comment by ryan-roemer** [comment]
We've discussed this in more detail in https://github.com/FormidableLabs/victory/issues/1957 but the issue is that packages like:

- https://unpkg.com/browse/d3-interpolate@3.0.1/package.json
- https://unpkg.com/browse/d3-color@3.1.0/package.json

etc. are now ESM only, and given that we import at the top of our files for like `d3-interpolate` that means that we either:

1. Have to fully drop supporting CommonJS in Node.js environments and force all consumers to be in ESM mode. This is difficult because CJS mode is still overwhelmingly the normal way to run Node.js apps.
2. Refactor all our consuming code in the library to lazy dynamically `import("d3-interpolate")`, which means that any use of *any* of functions from these d3 libraries have to also become `async` if they were not before.

At the end of the day, I'm not really sure if there is even an attack vector in most or even any cases as an offending string would:

1. Have an application that accepts it from the user and then runs server side
2. That is passed to `d3-interpolate`
3. That is further passed to `d3-color`
4. Than then hits the magic regex badness in `d3-color` in the CVE

We **definitely do** want to get all our dependencies upgraded, but the above situation illustrates the complexity and difficult choices we have for us given d3's unfortunate choice to go ESM-only for its newest packages.

**Comment by pgbradbury** [comment]
Thanks for the explanation.

A couple of points though.

1. ESM is supported from Node.js version 12
2. Node.js version 12 is [end of life](https://endoflife.date/nodejs) in just over a week. This means it and CommonJS are effectively deprecated.

So while I understand the point of view, no one needs to be running that at this point and if they are they can use a previous (or the current) version of Victory. The code base can move on and drop support for technology that is end of life, to enable it to support users who are concerned about security and patching their systems correctly.

**Comment by ryan-roemer** [comment]
ESM being "supported" is unfortunately far different than "I can just run my existing Node.js app as ESM" for the broad base of Node.js applications out there in use, irrespective of version.

And CommonJS is very much not deprecated, just also supported along with ESM

We've written a blog post at https://formidable.com/blog/2021/node-esm-and-exports/ that discusses the pitfalls and challenges to the broader Node.js ecosystem as some authors (like Bostock and Sindre Sorhus) start switching over to ESM-only. In all likelihood, we're looking at a potentially "long" to "never" phasing out of CommonJS in Node.js applications. And for the present, supporting CommonJS on Node.js is overwhelmingly needed over ESM.

**Comment by pgbradbury** [comment]
Thanks for that, the blog is helpful. However, as you say you are stuck now with the old versions of d3. If a bigger defect is found how will you be able to resolve? If d3 is core to your library it would seem the decision has been made.

As you say you have two options (I would posit a third which is to replace or replicate the functionality in the d3 modules, although I suspect this is not worth it). Have you picked which one you are going to do? And if so do you have an ETA? Or are you just going to ignore the issue for now until it becomes more of a manifest issue for you?

**Comment by ryan-roemer** [comment]
We have various options like:

- Refactor our API to be async on any `import()` of a d3 library.
- Transpile our dependencies and vendor them in.
- Look to replace d3 libraries with something more compatible.
- ... possibly others? (That's why this is is a discussion and brainstorm issue -- to come up with a best approach!)

Upgrading deps to silence security warnings is definitely a high priority for us, but as there is a large development / end user cost to many of the available options so we have to triage our available developer resources, what's best for our broad user base, and limits actual, exploitable security risks.

We don't have a present ETA, but are open to community suggestions in addition to our ideas and community volunteers for implementations.

**Comment by ryan-roemer** [comment]
@pgbradbury so we went the vendor path (just for CommonJS stuff and leave ESM as using the real underlying package). Would love your feedback on this from the CI/CD-complaining-about-stuff perspective after we release. Thanks for your patience! (And this one was, as expected, a real pain 😛 )
