### ISSUE TITLE
Tooltip performance is poor on medium/large data sets

### ISSUE THREAD

**Issue by mattbadley** [FormidableLabs/victory#2210]
I have noticed that when using data sets of 100+ items, with tooltips, rollovers start to chug quite a lot.

At first I thought it might be my own implementation, but after using the example provided in the docs and passing it more data, I still observe the same issues.  Here's the example that I used -

https://formidable.com/open-source/victory/gallery/voronoi-tooltips-with-grouped-components/

Here's the code -

```
const getTestData = (amount: number) => {
  const dataPoints: { x: number; y: number }[] = []
  for (let i = 0; i < amount; i++) {
    dataPoints.push({ x: i, y: i })
  }
  return dataPoints
}

export const Chart: React.FC<Props> = (props) => {
  return (
    <VictoryChart height={400} width={400} containerComponent={<VictoryVoronoiContainer />}>
      <VictoryGroup
        color="#c43a31"
        labels={({ datum }) => `y: ${datum.y}`}
        labelComponent={<VictoryTooltip style={{ fontSize: 10 }} />}
        data={getTestData(200)}
      >
        <VictoryLine />
        <VictoryScatter size={({ active }) => (active ? 8 : 3)} />
      </VictoryGroup>
    </VictoryChart>
  )
}
```

The code is the same as in the example, except I've removed the 2nd line graph (which should improve performance anyway) and supplied many more data points.

Things start to slow down significantly at over 100 points.  In my real implementation there might be 300-400 data points, which makes the chart tooltips unusable.

If I remove `VictoryScatter` completely it helps, however things slow down again after around 200 data points.

I have seen this previous thread around performance (where a fix was introduced) so I'm not sure what's going on or if I'm missing something - https://github.com/FormidableLabs/victory/issues/1669

Could someone please try the example above and take a look?

**Comment by mattbadley** [comment]
It seems to be to do with `VictoryGroup` - if I don't wrap it in that then performance improves drastically.  Why would this be the case?

**Comment by becca-bailey** [comment]
We have done pretty extensive work to look into this performance issue, and we're aware of issues with interactivity with large datasets. We have added some small fixes like this one (https://github.com/FormidableLabs/victory/pull/1901) to reduce re-rendering time, but there are still some performance bottlenecks caused by repeated re-rendering and re-calculating of props and state, which is documented in this milestone. https://github.com/FormidableLabs/victory/milestone/3

Components like `victory-group` re-calculate the props and map through the children and assign props to each child, which can be expensive with large datasets. Ideally we would handle this differently, and I hope to start work on this soon.

**Comment by mattbadley** [comment]
Thanks for the update!
