### ISSUE TITLE
time scale reverts to number labels when paired with dependent axis

### ISSUE THREAD

**Issue by pgraham** [FormidableLabs/victory#2364]
**Describe the bug**
I have a chart that uses Dates along the xaxis with a defined domain. Setting `scale={{x: 'time'}}` creates an x-axis with readable date labels. However, if I add a second axis with `dependentAxis`, the labels on the x-axis revert to timestamp numbers.

**Victory version**
36.5.0

**Code Sandbox link**
https://codesandbox.io/s/unruffled-hellman-1hy52e?file=/src/App.tsx

**To Reproduce**
1. Create a VictoryChart with VictoryBar which uses Date values along x-axis
2.  Add _VictoryAxis_ with `scale={{ x: 'time' }}`
3. Notice labels along x-axis
4. Add second _VictoryAxis_ with `dependentAxis` property

**Expected behavior**
Labels along x-axis should be formatted as readable dates (as observed in step 3).

Actual: Labels along x-axis are formatted as unix timestamp numbers

**Desktop (please complete the following information):**
 - OS: MacOs 12.4
 - Browser: Chrome
 - Version 103

**Comment by KevinElberger** [comment]
In case someone is still struggling with this and comes across this issue:

My issue was due to wrapping my chart in a `<VictoryStack />` which, [per the docs](https://commerce.nearform.com/open-source/victory/docs/victory-stack), should not be used in conjunction with `<VictoryAxis />` children. Once I removed the `<VictoryStack />` component and swapped it for a `<VictoryChart />` component, this issue was resolved. Hope this helps!
