### ISSUE TITLE
VictoryGroup breaks when a VictoryBar has y={(datum)=>null} inside a victoryStack and has large X values

### ISSUE THREAD

**Issue by sergeykimaia** [FormidableLabs/victory#2446]
**Describe the bug**
VictoryChart no longer displays correct x values when what i wrote in the title happens

**Victory version**
36.6.0

**Code Sandbox link**
[Please include a code sandbox link or a similar reproduction if possible.](https://codesandbox.io/s/affectionate-liskov-1ipyxs)

**To Reproduce**
1. go to click on the sandbox link
2. see all the bars in the chart are aligned to the right
3. remove y={(datum)=>null} and see it fix itself

**Expected behavior**
one part of the group disappears while the other works normally

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome 
 - Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by vozaldi** [comment]
Try to return a number instead of `null`.

```
<VictoryBar
  y={(datum) => 0}
  ...
/>
```

The [`y`](https://github.com/FormidableLabs/victory/blob/fb7eba3cdc84722287629606ff5e698daab12755/packages/victory-core/src/victory-util/common-props.tsx#L32) prop should return type of [`DataGetterPropType`](https://github.com/FormidableLabs/victory/blob/fb7eba3cdc84722287629606ff5e698daab12755/packages/victory-core/src/types/prop-types.ts#L139) which is `string | string[] | number | number[]`.

**Comment by sergeykimaia** [comment]
in the chart im using i want 0 to be a legitimate value that appears while hovered, while null to be like missing data in victoryLine
