### ISSUE TITLE
Add default aria roles for every component

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#263]
- what roles should data elements have. Should the roles be different if there are events attached to elements
- What else needs roles?

**Comment by paulathevalley** [comment]
I did some initial research here: https://github.com/FormidableLabs/formidable-landers/issues/84 
 
The minimum is to set up the `<svg>` so it is read by screen readers as an image, with `role="img"` and `aria-labelledby="title desc"` as long as there are corresponding `<title>` and `<desc>` tags to describe the chart. This option means the data itself will not be read.

The second, more involved, option is to create a (visually hidden) corresponding `<table>` with the data that the chart is using. The screen reader will read this data, because it seems `<table>` are very accessible. The axes would be column and row headers, perhaps, and the data would be in cells. I do not know a lot about the details of going with this option, particularly showing: animation, functions, differentiating bar, area, scatter, et al chart types, differentiating styles depending on the data, and potentially many other use cases.

**Comment by boygirl** [comment]
It seems like things that get event handlers are expecting an aria role 
![image](https://cloud.githubusercontent.com/assets/3719995/15225990/ba594d46-1835-11e6-9dac-5ab34ec8221f.png)

**Comment by paulathevalley** [comment]
Hmm, I see. Those warnings make sense if we don’t have roles anywhere yet. Do those warnings occur with `role="img"` on `svg`? The [`img` role spec](https://www.w3.org/TR/2011/CR-wai-aria-20110118/roles#img) shows "Children Presentational: true" so if this means what I think it means, then children should get `role="presentation"` and screen readers would ignore them completely. If we go with this option, we would leave accessibility as a responsibility to the consumer.

If we do want to tab through the elements, then we will have to consider going with the involved option. The data should drive the accessibility, and it will be incredibly difficult to add default roles without being able to make assumptions on the data and any interactivity that’s being added. 

I found more examples:

[Accessible D3/C3 Chart Demo](http://codepen.io/joe-watkins/pen/engts?editors=1010) using `<table>`

[Authoring Accessible SVG](http://schepers.cc/authoring-accessible-svg) with Data Visualization example by adding readable `<text>` elements, e.g. `<text>Total declaring one or more disabilities 18.6%</text>`

[Describler](http://describler.com/) is an experimental screen reader for SVG and is actually really cool. If we go with the involved option, we will probably want to mimic this as much as possible. I downloaded one of the examples here: https://gist.github.com/paulathevalley/0668eeb719be392a6ac87df18299f586?short_path=49e022c

None of these examples have interactivity, unfortunately.

**Comment by ebrillhart** [comment]
@boygirl are we just going with the more basic aria roles for now and not doing the hidden table thing?
