### ISSUE TITLE
Debounce built-in events

### ISSUE THREAD

**Issue by tquetano-r7** [FormidableLabs/victory#269]
I was just curious if it was possible to manage some of the built-in render triggering events. I have a resizable div that contains a `VictoryChart`, and it is rendering hundreds of times with a simple resize, causing a noticable degredation in render performance. I am hoping to find a way to debounce the render events for a visual performance increase (or obviously open to any ideas that can reduce the number of render cycles). Any ideas?

**Comment by boygirl** [comment]
@tquetano-r7 
As of  `victory@0.6.0` all Victory components render responsive svgs by default. This works via the `viewBox` attr. If you render a victory component into a resizable div, you should not need to pass it new `width` and `height` props (which will cause a re-render). It should resize with the container automatically without re-rendering and the associated perf hit. The improvements in svgs support in react 15 will also allow us to add the `vectorEffect` attr to the svgs victory renders, so that the text etc will remain readable at small sizes. Look for this improvement in `victory@0.8.0`

**Comment by tquetano-r7** [comment]
Appreciate the info! Closing this guy.
