### ISSUE TITLE
Deprecated minimatch@2.0.10

### ISSUE THREAD

**Issue by cocacrave** [FormidableLabs/victory#286]
npm install --save victory gives npm warning:
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

I tried npm install minimatch (which was @3.0.0) to v3.0.2 but it still gives same warning.
npm list shows that victory is still using minimatch@2.0.10.

Is this a problem only for me?

**Comment by boygirl** [comment]
@cocacrave thanks for pointing this out. I'll track down where that's coming from.

**Comment by ebrillhart** [comment]
@boygirl as far as I can tell, there are several dependencies (and dependencies of dependencies) that need to upgrade in order to make this error go away. let me know if I should submit pull requests updating to any/all of these repos. they are as follows:

Mocha needs to update to glob 7.0.5
https://github.com/mochajs/mocha/blob/master/package.json
Chokidar needs to update to readdirp 2.1.0
https://github.com/paulmillr/chokidar/blob/master/package.json
builder-victory-component needs to update to babel-core 6.10.4
https://github.com/FormidableLabs/builder-victory-component/blob/master/package.json
istanbul needs to update to fileset 1.0.0
https://github.com/gotwarlost/istanbul/blob/master/package.json
wd needs to update to archiver 1.0.0
https://github.com/admc/wd/blob/master/package.json
ecology needs to update to babel-core 6.10.4
https://github.com/FormidableLabs/ecology/blob/master/package.json
react-docgen needs to update to node-dir 0.1.14
https://github.com/reactjs/react-docgen/blob/master/package.json
html needs to update to glob 7.0.5
https://github.com/maxogden/commonjs-html-prettyprinter/blob/master/package.json
kadira storybook needs to update to babel-core 6.10.4
https://github.com/kadirahq/react-storybook/blob/master/package.json

**Comment by boygirl** [comment]
@ebrillhart can you start with the babel upgrades to ecology and builder-victory-component?

**Comment by chrisbolin** [comment]
`minimatch@3.0.4` is now installed, so we don't get this warning anymore :1st_place_medal:
