### ISSUE TITLE
Horizontal Bar X Values

### ISSUE THREAD

**Issue by kig-rob** [FormidableLabs/victory#289]
Horizontal bar charts break when the x values are not sequential (1, 2, 3, etc)

`<VictoryBar horizontal
        data={[
          {x: 1, y: 'Label 1'},
          {x: 7, y: 'Label 2'},
          {x: 3, y: 'Label 3'},
          {x: 4, y: 'Label 4'}
        ]}
      />`

See fiddle:
https://jsfiddle.net/5g20p8vd/15/

**Comment by coopy** [comment]
It also breaks when there's a gap in the data:
```
        data={[
          {x: 1, y: 'Label 1'},
          {x: 3, y: 'Label 3'}
        ]}
```

https://cloudup.com/chyEW_ggZZ2

**Comment by ebrillhart** [comment]
@kig-rob is this the desired behavior? or are the labels meant to be along the vertical axis?

<img width="730" alt="screen shot 2016-06-30 at 2 49 15 pm" src="https://cloud.githubusercontent.com/assets/13110279/16505456/ed3f8c4e-3ed1-11e6-8ca2-d0db97152f04.png">

the underlying issue comes from the helper methods scaling the axis, which I would need to dig into, possibly with @boygirl's help. if this is the desired behavior, though, a workaround is the following code:

```
<VictoryChart>
          <VictoryStack horizontal>
            <VictoryBar
              data={[
                {x: 1, y: "Label 1"},
                {x: 7, y: "Label 2"},
                {x: 3, y: "Label 3"},
                {x: 4, y: "Label 4"}
              ]}
            />
          </VictoryStack>
          <VictoryAxis
            tickValues={["Label 1", "Label 2", "Label 3", "Label 4"]}
          />
          <VictoryAxis dependentAxis/>
      </VictoryChart>
```

**Comment by kig-rob** [comment]
Thanks for the response Emma!

The desired behavior would be having text labels on the y-axis and number values on the x-axis. I would expect it to work just like a vertical bar chart does. The x values in the data object should appear on the x-axis and the y values on the y-axis.

This is what I want the chart to look like in the end, but with x values equaling whatever they want, rather than 1,2,3,4,etc:
![screen shot 2016-06-30 at 3 20 47 pm](https://cloud.githubusercontent.com/assets/7051813/16506297/5add7f6e-3ed6-11e6-902e-8c67ce1b57e9.png)

We are already using VictoryStack for these bar charts, and when doing so, it appears the x and y values get flipped. So x values appear on the y-axis. We are still running into the issue where having non-sequential x values breaks the layout. To over come this for now we are forming our data like so:
`[
{name: "Label 1", x: 1, y: 752.68},
{name: "Label 2", x: 2, y: 432.43},
...
]`
Trying to use the tickValues prop to bring in the text from the name key right now.

**Comment by ebrillhart** [comment]
@kig-rob oh! okay. I wasn't sure if you wanted to maintain the x-value spacing that the chart would have in a normally-oriented chart. but yes, expected behavior would be equivalent to a vertical bar chart. I'll see what I can do about that. let me know if you need help with getting the workaround formatting in the meantime and I can try to figure that out as well.
