### ISSUE TITLE
Translating regular d3 code into victory

### ISSUE THREAD

**Issue by dagda1** [FormidableLabs/victory#321]
I am experimenting with Victory.

I have original code like this which is not great because it outside of the react reconciliation process:

```
    const xAxis = axisBottom()
            .scale(state.xScale)
            .tickSizeInner(-state.dimensions.height)
            .tickFormat(timeFormat("%b %Y"));

    const yAxis = axisLeft()
            .scale(state.yScale)
            .tickFormat((d) => {
              return format(".2f")(d);
            });

    const xAxisGroup = svg.append("g")
      .attr('class', 'x axis')
      .attr("transform", `translate(${0}, ${state.dimensions.height})`)
      .call(xAxis);

    const yAxisGroup = svg.append("g")
      .attr('class', 'y axis')
      .call(yAxis);

    const lineGenerator = line()
            .x(d => state.xScale(d.jsDate))
            .y(d => state.yScale(d.value));

    const g = svg.append('g')
            .attr('class', 'line');

    g.append('path')
      .datum(data)
      .attr("class", "line")
      .attr("d", lineGenerator);

    g.selectAll('circle')
      .data(data)
      .enter().append('circle')
      .attr('cx', d => state.xScale(d.jsDate))
      .attr('cy', d => state.yScale(d.value))
      .attr('stroke-width', '3')
      .attr('fill', '#fff')
      .attr('r', 6);
```

I can see how I can create the axis with VicotryAxis:

```
<svg style={style.parent} viewBox={viewBox}>
  <VictoryAxis
     style={xAxisStyle}
     padding={padding}
     orientation="bottom"
     scale="time"
     tickValues={data.map((d) => d.jsDate)}
     tickFormat={timeFormat("%b %Y")}
     standalone={false}
     />

  <VictoryAxis
             dependentAxis
     style={yAxisStyle}
     padding={padding}
     orientation="left"
     domain={yDomain}
     standalone={false}
  />
</svg>
```
But I am not sure how to create the path of points.  The scale appears to be encapsulated inside the axis and I would like to use to create the VictoryLIne.

Is this possible?

**Comment by boygirl** [comment]
@dagda1 you can pass a scale function into any victory component that work inside chart (VictoryLine, VictoryAxis, VictoryBar...). Each VictoryAxis takes only a single scale, but the others can take a scale object like `scale={{x: "time", y: "linear"}}` but the component will try to set the domain and range based on other props provided to the component. You can't provide range directly, but it will be set correctly so long as all the components use the same width / height / padding props, which they should anyway to line up correctly in the parent svg. You can set the domain explicitly via props (like scale, just a single domain for axes, and x / y for others). 
Here's an example of composing a chart manually: https://formidable.com/open-source/victory/recipes/multiple-axes

Or if you use the VictoryChart wrapper most of this will just be taken care of for you. Scale can be set on the chart wrapper, and it will be passed down to all children. Domain can also be set on the chart wrapper, or it will be automatically calculated based on the props given to your components, and reconciled for the maximum extent within VictoryChart so that everything fits. The dimensions of the chart will also be enforced on the children so that the range is correct. 

Here's more information on the chart wrapper https://formidable.com/open-source/victory/docs/victory-chart

Based on your d3 code above, I would guess your VictoryLine component would look something like 
```
<VictoryLine
  scale={{ x: "time", y: "linear" }}
  data={yourDataSource} // some JSON blob
  x={"jsDate"}  // this is a data accessor prop, it can take a string corresponding to property name
  y={(d) => d.value} // or it can be expressed as a function of data
/>
```

**Comment by boygirl** [comment]
@dagda1 you can also always ask questions in the [gitter channel](https://gitter.im/FormidableLabs/victory). I'm around a lot for support. I'm going to close this issue, but let me know if anything still needs more explanation or if you have other questions.

**Comment by dagda1** [comment]
@boygirl thanks for the detailed answer
