### ISSUE TITLE
Check for changes when animating 

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#339]
_From @boygirl on August 5, 2016 18:15_

Currently VictoryAnimation does not check whether values have changed when animating, because the expensive equality check for deeply nested objects would slow down animation. This could be a problem for people depending on the recently added `animating` argument passed with victory-animation. Is the expensive check worth adding?

_Copied from original issue: FormidableLabs/victory-core#95_

**Comment by kenwheeler** [comment]
@boygirl what kind of impact are you seeing after adding the change? How many child components made frames drop before and after? What is perf like on reasonable numbers of child components before/after?

**Comment by kenwheeler** [comment]
I guess the biggest thing is, what kind of overhead does the check add and does that overhead scale proportionally to the tree

**Comment by nfcampos** [comment]
I've been thinking a better approach to animation/transition would be to do it on the leaf components (eg. `dataComponent`), since at least from my benchmarks most of the js time is spent re-evaluating the helper methods of the top-level component (re-creating the objects that represent each data point and its respective `style`). Doing animation further down the tree would avoid re-evaluating this. I realise this might perhaps make animating some props more difficult? but it seems like it would make the ones that are possible much more performant... this make sense for anyone else?

**Comment by boygirl** [comment]
@nfcampos I'm worried about how that would scale with many nodes, but it's worth investigating.

**Comment by nfcampos** [comment]
it already doesn't scale with many nodes, because `datum` and `style` objects are created for each, right? would this be any worse in per-node cost?

**Comment by boygirl** [comment]
I'm worried about kicking off a ton of `requestAnimationFrame`

**Comment by nfcampos** [comment]
what if updates in the leaf nodes use `batchedUpdates` to make that a single update?

**Comment by nfcampos** [comment]
(although using `batchedUpdates` would I think require some parent component to keep track of the timer and let all of its animation-enabled children know they should now update to the next frame) this part I don't like too much, making animations a labyrinth of parent-child callbacks, hmm
