### ISSUE TITLE
Performance Issues with Victory Voronoi Tooltip

### ISSUE THREAD

**Issue by chriskurzeja** [FormidableLabs/victory#373]
We've been using the voronoi tooltip and noticed a performance gotcha. 

If you pass in a function as labels prop to VictoryVoronoiTooltip and the function is expensive (i.e. in our case we do formatting on raw data) then this makes the rendering unperformant - this is used to determine whether to render the voronoi point or not which means this function is being called each time we render. 

Ideally - you would only want to invoke that function when the tooltip is to be displayed and have an alternative way to determine if we should create the point. We've managed a workaround which is to pass a dummy function into the tooltip and then make the actual tooltip object calculate it's text.

``` javascript
labels={p => "text"}
```

This addresses our performance issues but isn't ideal - should there be a function we can supply to indicate a label exists at a point or not - separate the concern away from the actual content of the label?

**Comment by Zerim** [comment]
Any update on this? I'm also seeing poor performance while using tooltips.

Actually, after seeing the bad performance using VictoryVoronoiTooltip I attempted to implement my own Tooltip simply using the VictoryPortal primitive and attaching events to the VictoryVoronoi component. It seems like the bad performance is actually stemming from the events API.

Looking at Chrome Debugger Profile, my program seems to spend a lot of time here: https://github.com/FormidableLabs/victory-core/blob/9f6099a661ae4008e41dd4a7cd951b115361ab4a/src/victory-util/data.js#L67

It seems like maybe getting the props/ data to supply to the higher level events API on each event firing is too expensive. This would align with what @chriskurzeja was seeing above where he could improve performance by making his accessors less expensive.

In my case, my accessors are already as cheap as they can get, so my next attempt is to apply DOM events directly and throttle the events in my custom Tooltip implementation. Any thoughts on this  approach appreciated.

Not sure what the fix is with respect to the core library, since throttling the higher level events API would seem to defeat the purpose. Maybe some combination of memoization/caching to avoid running the accessors every time.

**Comment by boygirl** [comment]
@Zerim @chriskurzeja 

One thing that can be done is to add simple events to the data components that would bypass Victory's event system entirely. 

In this scenario the voronoi and the tooltip would be need to be rendered by the same component in order for the triggers to work without Victory's event system. It will also be less flexible in that you won't be able to add events that trigger mutations on other elements. Even so, I think this is a good solution for people wanting very simple tooltips, and better performance. I'll continue trying to improve the performance of the existing situation, but I'll build this too.

**Comment by Zerim** [comment]
Thanks @boygirl for the reply. I did a little bit more playing around, and actually it turns out that using the higher level events API is still fairly performant. The perceived lack of performance with that test actually seems to have to do with my layout, and VictoryVoronoi not being placed in the foreground so only some portions of my chart would trigger events.

However, even after making that fix the VictoryVoronoiTooltip performance still seems to be fairly slow. So I'm going to stick with the higher level events API for now, as it seems the performance bottleneck is actually probably somewhere in the logic for how VictoryVoronoiTooltip is responding to those events. Will update this thread with any new findings one I complete my custom tooltip implementation.

**Comment by Zerim** [comment]
**Update**
I was able to get a fairly high performant tooltip working. My tooltip also had performance issues initially, which were due to calling `this.setState` too high up in my component tree, resulting in expensive renders at too high a frequency.

Using an Observable to treat the event stream as first class object, I pass the observable into my custom tooltip, and subscribe to it inside of the tooltip, only setting the state of that specific component.

**Comment by erikreppen** [comment]
Try setting a custom dataComponent And observe the number of times it fires. I saw it hitting each datapoint nine times for VictoryScatterGraph but haven't had a chance to verify whether that was something we were doing wrong on our end.

**Comment by boygirl** [comment]
`victory@0.18.0` includes `VictoryVoronoiContainer` which has much better performance than `VictoryVoronoi` and `VictoryVoronoiTooltip` because it doesn't actually render any voronoi polygons.
