### ISSUE TITLE
filter data to fit within explicit domain

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#386]

**Comment by nfcampos** [comment]
filter by x domain or both domains?

**Comment by boygirl** [comment]
both domains. What do you think?

**Comment by nfcampos** [comment]
filtering by y domain would make this render differently
<img width="404" alt="screen shot 2016-10-10 at 21 40 14" src="https://cloud.githubusercontent.com/assets/56902/19250442/3f7bb86a-8f32-11e6-9d3f-3f2b51fa91c1.png">
since the points outside of the domain wouldn't be rendered then the path would interpolate differently, is this expected or unexpected? 
I dont think something like this can happen when filtering only by the x domain, but maybe it is and Im not thinking of it

**Comment by boygirl** [comment]
This would happen if an explicit domain were set, either on a parent like `VictoryChart` or directly on `VictoryLine`. The standard behavior would still be to include all the data. So this might be a feature rather than a flaw? Admittedly it's a little strange for the scenario you describe above, plotting a sine wave, but it will make a pretty nice way zoom in on a chart section.

**Comment by nfcampos** [comment]
that's the thing, the current behaviour is usable for zoom-in, because it doesn't change the chart, just "hides" a part of it, this new one with filtering wouldn't be, because it could potentially change the chart as you zoom in, right?

**Comment by boygirl** [comment]
no, depending on how much padding you have around your chart it may not hide all the data you intend to hide.

**Comment by nfcampos** [comment]
oh, i see. then I'm not sure

**Comment by boygirl** [comment]
hmm... maybe data filtering should only happen for discrete data types like VictoryScatter. VictoryArea and VictoryLine could clip instead.

**Comment by nfcampos** [comment]
I definitely agree with the clipping, actually filtering for discrete data types would then be no more than an optimisation I assume?

**Comment by boygirl** [comment]
yeah, otherwise you would also have to clip the labels etc, or the whole rendered group... which I suppose I did just build the ability to do. But you would end up in the weird spot of wanting the data to not show up, but not wanting to clip off labels and tooltips from nearby data.
