### ISSUE TITLE
strokeWidth as a function of x

### ISSUE THREAD

**Issue by jefffriesen** [FormidableLabs/victory#406]
I'm trying to make a stream graph. I see it's on the list (https://github.com/FormidableLabs/victory/issues/341) but I think I can do it if I can make strokeWidth a function of the x value. But I ran into something that I don't know if it's a bug or a feature.

In your bar graph documentation, you have the bar fill as a function of y:
```js
  <VictoryBar
    style={{
      data: {
        width: 15,
        fill: (data) => data.y > 3 ?
          "gold" : "orange"
      }
    }}
    data={[
      {x: 1, y: 1},
      {x: 2, y: 2.5},
      {x: 3, y: 4},
      {x: 4, y: 2.5},
      {x: 5, y: 1},
    ]}/>
```

The `data` passed as an argument isn't the entire dataset, a `data` object is passed for every x value:
```js
Object {eventKey: 0, x: 1, y: 1}       // data passed for iteration 1
Object {eventKey: 1, x: 2, y: 2.5}     // data passed for iteration 2
```

But for line graphs, we get the whole `data` array passed every time. So in this example in your documentation:
```js
 <VictoryLine
   style={{
    data: {
      stroke: (data) => {
        const y = data.map((d) => d.y);
        return Math.max(...y) > 2 ?
          "red" : "blue";
      }
    }
   }}
   data={[
     {x: 0, y: 1},
     {x: 1, y: 3},
     {x: 2, y: 2},      
     {x: 3, y: 4},
     {x: 4, y: 3},
     {x: 5, y: 5}
   ]}
 />
```

the `data` passed into stroke is the entire data array on every iteration. In fact, I don't think that example works. The entire line is red and from your code, I think your intention is that some sections are blue.

For generating a streamgraph by varying the strokeWidth, I would pass in a data structure like this:
```js
const data = [{a: 1, b: 5, c: 7}, {a: 2: b: 6, c: 10}, ...]

// style of VictoryLine:
data: {
  strokeWidth: (data) =>  data.c - data.b
}
```

But that won't work if the entire data set is passed in. Maybe I could make it work if there were additional arguments passed into the function. If I had a x-axis index or x-axis value I could look up the values I need based on that. But I only see 1 argument available (the entire dataset). Is this a bug or intentional?

It may be nice if that function got passed multiple arguments like this:
```js
strokeWidth: (dataObjectForThisX, index, dataArray) =>  dataObjectForThisX.a - dataObjectForThisX.b
```
If you don't need `index` or the entire `dataArray` the users doesn't need to list them as arguments but they would be available if they did. Just a thought.

Back to the original issue - is the entire data array being passed in for VictoryLine intentional? It seems to break from how other charts work. 

Thanks

**Comment by boygirl** [comment]
@jefffriesen the entire data array is passed to VictoryLine and VictoryArea styles because only one element is rendered for the entire data series. It wouldn't make sense to pass individual datum to functional styles for these data types because we are not rendering one element per datum. The example you mention above is intentionally just one color. Imagine having a defined set of styles for a whole group of lines, and automatically coloring just those with values above a certain amount, or with an average above a certain value. I should probably change that example to something with multiple lines to make it clearer. 

Also, unfortunately, variable stroke width is not possible in SVG. You might be better off manually altering the `y0` of `VictoryArea` data for now. Check out my faked stream graph https://jsfiddle.net/boygirl/Lpahqd4u/

**Comment by jefffriesen** [comment]
@boygirl That makes sense now. Thanks for the response and for the stream graph example.
