### ISSUE TITLE
Labels overlaps on Pie Chart

### ISSUE THREAD

**Issue by lucas-aragno** [FormidableLabs/victory#414]
So I'm getting this result from rendering  a couple of pie charts: 
<img width="703" alt="screen shot 2016-10-28 at 10 35 55 am" src="https://cloud.githubusercontent.com/assets/5210254/19808260/64758314-9cfa-11e6-955e-acb29a345ee2.png">

I've been checking the source code but maybe you could help me to find a way to avoid this behavior

e.g there is any way for me to add "references" at the side of the chart so I can delete the labels?

**Comment by boygirl** [comment]
@lucas-aragno We haven't finished a legend component yet, but you can switch out the labels for tooltips, or style the labels to be smaller and have line breaks. I apologize if neither of these is ideal for your use case.

**Comment by OzoTek** [comment]
Hi @boygirl I'm trying to use `VictoryLegend` with `VictoryPie`, but I'd need the props passed from the Pie to the Legend, in order to get the color of the data. Basically I'm looking for a `legendComponent` as common prop.

Is it something that's possible without having to set manually the color in the `data` array?

**Comment by Otoris** [comment]
Any updates as I'm trying to solve a similar problem.
