### ISSUE TITLE
Get an original data point inside onClick event handler

### ISSUE THREAD

**Issue by iurii-kondratiuk** [FormidableLabs/victory#421]
Hi everyone,

Is there a possibility to access an original data point inside onClick event handler? 

```
  <VictoryBar
    data={[{ x: 1, y: 2 }, { x: 2, y: 1 }, { x: 3, y: 4 }]}
    events={[{
      eventHandlers: {
        onClick: () => {
          // get the point like { x: 1, y: 2 } 
        },
      },
    }]}
  />
```

Thank you in advance for your help.

**Comment by iurii-kondratiuk** [comment]
I think I found a solution: 

```
<VictoryBar
  data={[{ x: 1, y: 2 }, { x: 2, y: 1 }, { x: 3, y: 4 }]}
  events={[{
    target: 'data',
    eventHandlers: {
      onClick: (event, data) => {
        // it's in data object
      },
    },
  }]}
/>
```

Anyway, thank you. I'll close an issue.

**Comment by redzacool** [comment]
how do you get data.x or data.y?? i only got x that pointing the x mouse pointer, not data.x

**Comment by Ctorum** [comment]
> how do you get data.x or data.y?? i only got x that pointing the x mouse pointer, not data.x

there is an object named "datum" inside data object. e.g., data.datum.y //48.276752291209505

**Comment by letvigna** [comment]
For anyone else having trouble like me, the `datum` property will only show up for charts which render separate elements for each data point, unlike [VictoryArea](https://formidable.com/open-source/victory/docs/victory-area) for example, which "renders only a single element to represent a dataset rather than individual elements".

So for charts that are visually continuous, I still haven't found away to get this data point upon click without the use of VictoryVoronoiContainer which is extremely inconvenient as I didn't want tooltips to be activated upon hover, forcing me to have to completely rewrite native lib event handling to get it to function the way I wanted.
