### ISSUE TITLE
Tooltip cannot render text with function

### ISSUE THREAD

**Issue by danielepolencic** [FormidableLabs/victory#450]
I have the following code copied from the guide where I customised the prop `text` for `<V.VictoryTooltip>`.

```js
<V.VictoryChart
  domain={{ x: [0, 11], y: [-10, 10] }}
>
  <V.VictoryBar
    labelComponent={<V.VictoryTooltip text={(d) => 2}/>}
    data={[
      {x: 2, y: 5},
      {x: 4, y: -6},
      {x: 6, y: 4},
      {x: 8, y: -5},
      {x: 10, y: 7}
    ]}
    style={{
      data: {fill: "tomato", width: 20}
    }}
    x="x"
    y="y"
  />
</V.VictoryChart>
```

When I try to run the code I get the following errors:

![image](https://cloud.githubusercontent.com/assets/1130499/21159984/2a654eb6-c17b-11e6-99fd-93fc208c2a14.png)
 
I investigated and looks like the `datum` prop is not pre populated (indeed it's `undefined`). I assume this prop should come from the parent component?

I'm on `"victory": "^0.14.0"`

**Comment by boygirl** [comment]
@danielepolencic I believe this is happening because Victory components do not create label elements for data points that don't have labels to cut down on the number of nodes rendered. So you're getting into the situation where the label components are being created (because you've manually added a text prop to VictoryTooltip) but they are not being given the rest of the props they need to render.  This is definitely an edge case I need to figure out how to handle (without calculating unnecessary props and creating unnecessary elements). In the meantime, you'll have much better luck defining your labels like so: 
```
<V.VictoryChart
  domain={{ x: [0, 11], y: [-10, 10] }}
>
  <V.VictoryBar
    labelComponent={<V.VictoryTooltip />}
    labels={(d) => d.y + 2}
    data={[
      {x: 2, y: 5},
      {x: 4, y: -6},
      {x: 6, y: 4},
      {x: 8, y: -5},
      {x: 10, y: 7}
    ]}
    style={{
      data: {fill: "tomato", width: 20}
    }}
    x="x"
    y="y"
  />
</V.VictoryChart>
```
