### ISSUE TITLE
Data accessors not evaluated independently

### ISSUE THREAD

**Issue by Zerim** [FormidableLabs/victory#451]
I came across this issue while attempting to reverse the axis for the chart shown [here](https://jsfiddle.net/wrkd9qnm/).

The VictoryBar can have it's axis reversed by setting the VictoryGroup `horizontal` prop to true. The VictoryVoronoi, however, needs to manually modified by switching it's x and y accessors.

As you can see from opening up the console on[ this fiddle](https://jsfiddle.net/qfr7eaco/), the x accessor is actually mutating the input to the y accessor. The behavior is quite confusing upon first encounter.

The workaround, as shown [here](https://jsfiddle.net/zbzp26v9/), is to create an intermediate value in the data set, using a key that does not have special meaning such as 'x' or 'y'. 

I imagine this was done for performance reasons.  At the very least it seems worth documenting, as I'm sure others may get tripped up on this as well.

Thanks for the great library!

**Comment by boygirl** [comment]
@Zerim Thanks for this issue. I've been thinking for a while that Victory should use a more careful internal namespace for the x and y values it actually plots. Something like `xVictory`, `yVictory` so that it doesn't get muddied with the very common `x`, `y` data keys. This will be an annoying bit of work, but I think this issue is the tipping point for me.

**Comment by Zerim** [comment]
@boygirl No problem, glad it was helpful. Maybe you could prefix whatever the new variables names are with underscores, to add an extra level of clarity that these are for internal use.
