### ISSUE TITLE
Victory Calls Arbitrary Functions/Methods of Data Prop

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory#459]
If I pass in `data` that has a function on one (or all) of the sub-objects, Victory calls it. This could be really bad, if that function has external effects! It doesn't seem to matter what the function is called, victory invokes them all. It also doesn't matter which victory component I use (`VictoryScatter` and `VictoryBar` both do it).

Here's a quick and dirty reproduction, based off of the [Data Accessors Guide](http://formidable.com/open-source/victory/guides/data-accessors)

```jsx
<VictoryBar
      data={[
        { experiment: "trial 1", expected: 3.75, actual: 3.21, _danger: () => console.error("!!!") },
        { experiment: "trial 2", expected: 3.75, actual: 3.38 }
      ]}
      x="experiment"
      y={(d) => (d.actual / d.expected) * 100}
    />
```

When Victory renders, it will execute `data[0]._danger()` (and print to the console).

**Comment by DerekMaffett** [comment]
@chrisbolin This is happening because additional fields on `data` objects are automatically considered as styles, and styles passed as functions are automatically evaluated. https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-bar/helper-methods.js#L31

There's ways we could get around this, but it would be a breaking change. I'll have to discuss the best approach to this with @boygirl and then I'll get back to you.

**Comment by boygirl** [comment]
@chrisbolin we've decided that this is a wont fix given that it would be a breaking change, and methods with dangerous side effects existing within a data object seems like an extreme edge case

**Comment by chrisbolin** [comment]
@DerekMaffett @boygirl is it documented? if not, it might be a good idea, just to give people a heads up that any methods on `data` are being evaluated
