### ISSUE TITLE
Is there a way to render a chart without axis?

### ISSUE THREAD

**Issue by bali182** [FormidableLabs/victory#462]
Without specifying any axis like this:

```
<VictoryChart>
  <VictoryLine data={data} x='date', y='value' interpolation='basis' />
</VictoryChart>
```

Image here just for context:

![screenshot from 2017-01-02 13-05-10](https://cloud.githubusercontent.com/assets/3879181/21589719/9de944a2-d0ec-11e6-811e-90f754585419.png)

I get a chart that renders both axis. Is there a way to get rid of them completely?

**Comment by boygirl** [comment]
@bali182 If you just want a line by itself, you can just omit the chart wrapper, and ` <VictoryLine data={data} x='date', y='value' interpolation='basis' />` will render a line. If you want to keep multiple components synched up, you can use the `VictoryGroup` wrapper rather than `VictoryChart`. It will still reconcile the domain / scale etc of all its children, but without rendering any axes.

**Comment by bali182** [comment]
Cool thank you!
