### ISSUE TITLE
Cannot load any Victory Chart in ie10

### ISSUE THREAD

**Issue by lele85** [FormidableLabs/victory#474]
Hi there, in the current states if i try to render any Victory Component in ie10 i get these kind of errors:

`TypeError: Unable to get property 'props' of undefined or null reference`

It may be related to the dist build using some unfriendly babel configuration but it's very difficult to debug on my side.

You can test the behaviour in any of the provided jsfiddle:

https://jsfiddle.net/5g20p8vd/6/

P.S. Even the doc website does not load in ie10.

**Comment by lele85** [comment]
I spent some time to setup the project locally downloading and building the following repos:

`victory`
`victory-pie`
`victory-core`

I setted up a small example and i discovered that the problem is somewhere in:

`getComponentProps` in `victory-core/src/victory-util/add-events.js`

Looks like the first parameter in ie10 is always `undefined`. The setup was quite difficult due to the multi repository configuration. Could anybody help me to debug that?

P.S.
In order to debug the demo application from a windows VM i had to change the webpack config in `builder-victory-component/config/webpack/demo/webpack.config.dev.js` and add `host` to the dev server configuration:

```
devServer: {
    host: "0.0.0.0",
    contentBase: "./demo",
    noInfo: false
 }
```

Without doing that is only possible to access the served demo app on the local machine and not from another one using a direct ip.

Please tell me if this issues has priority because i would like to understand if you consider solving it. I understand that you have a lot of work going on, even a simple reply is highly appreciated.

**Comment by ryan-roemer** [comment]
@lele85 -- Thanks for your investigation! If it helps, the easiest thing is to just use the core victory package dev build (`dist/victory.js`) available from npm or https://unpkg.com/victory@0.15.0/dist/victory.js

If you can point to something in there, we can easily fix it in the corresponding underlying repo...

**Comment by mrestine** [comment]
I don't know how much investigating has happened since this was opened, but it's still open, and I've done some digging. I'm looking at 0.21.3, using the findings by @lele85 as a starting point and debugging using my project's node_modules/dist/victory.js.

That first parameter of add-events is the component. I worked backwards to `renderGridAndTicks` inside `victory-chart/src/victory-axis.js`. I noticed that  `props` passed in were much different in IE10 compared to Chrome. 

`renderGridAndTicks` `props` object keys in IE10
`dependentAxis, style, tickFormat, height, polar, theme, width, origin, animate, padding, standalone, categories, domain, range, scale, colorScale`

`renderGridAndTicks`, `props` object keys in Chrome
`dependentAxis, style, tickFormat, axisComponent, axisLabelComponent, tickLabelComponent, tickComponent, gridComponent, scale, standalone, theme, tickCount, containerComponent, groupComponent, fixLabelOverlap, height, polar, width, origin, animate, padding, startAngle, endAngle, innerRadius, domain, tickValues, offsetY, offsetX, crossAxis, orientation, colorScale`

Stepping back even further, I I found the only caller of `renderGridAndTicks` is `render`. I likewise looked at the keys of `this.props` inside render and found that they were the same as the above `props` object, only they were missing `colorScale`.

I don't suspect that this is an issue with `victory-axis`, and that it only shows here because it's called first when rendering a chart (a line chart, in my case). It looks as though the default props are not getting applied. I'll keep digging tomorrow.

**Comment by Errorific** [comment]
I've hit this, yay.
I don't have a working solution to this yet but I'm fairly certain it's a build chain problem.
I think we're hitting [this react bug](https://github.com/facebook/react/issues/6929) which is from [this babel problem](https://github.com/babel/babel/pull/3527) and is detailed in the [babel faq's about IE10 and class inheritance](https://babeljs.io/docs/usage/caveats/#internet-explorer). The solution should just be adding those babel transformations with loose turned on, but I'm failing at making that work in my typescript project which is probably more attributable to me failing with setting up all the layers of webpack loaders correctly.

**Comment by muiradams** [comment]
Any update on this. Is Victory incompatible with IE10 and below?

**Comment by muiradams** [comment]
I found a solution that hopefully will be helpful to others who are running into this problem in IE10. My solution is specific to create-react-app.  First you'll have to eject create-react-app to get access to the webpack config. Then `npm install --save babel-plugin-transform-proto-to-assign`. Inside the webpack.config.dev.js file add `path.resolve(paths.appNodeModules, 'victory')` and `plugins: ["transform-proto-to-assign"]`. After adding those two lines it should then look like: 
```
// Process JS with Babel.
          {
            test: /\.(js|jsx|mjs)$/,
            include: [
              paths.appSrc,
              path.resolve(paths.appNodeModules, 'victory'),
            ],
            loader: require.resolve('babel-loader'),
            options: {
              plugins: [
                "transform-proto-to-assign",
              ],

              // This is a feature of `babel-loader` for webpack (not Babel itself).
              // It enables caching results in ./node_modules/.cache/babel-loader/
              // directory for faster rebuilds.
              cacheDirectory: true,
            },
          },
```
After that it worked for me in IE10. Hope that helps!
