### ISSUE TITLE
How do i create a histogram?

### ISSUE THREAD

**Issue by yashcr07** [FormidableLabs/victory#560]
Is there any way to create a histogram? Right now what ever value we give to the 'x' prop in the VictoryBar will render a bar on that point, if i increase the width of the bar - to make it look like a histogram- the center of the bar represents the 'x' value, though i could set the x value as the mean of the start and end values, but i was wondering if there is any other way we can create a histogram, by giving a class interval ?

**Comment by boygirl** [comment]
@yashcr07 you would have to pre-bin your data. You can then use `VictoryBar` or `VictoryArea` with `interpolation="step"` I think the VictoryArea is easier for histograms that don't have evenly spaced bins.

**Comment by thousight** [comment]
The thing with `VictoryBar` is that the spaces between the bars change if the number of data on x-axis changes. For `VictoryArea` with `interpolation="step"` the issue is the bars on the left and right ends don't have the same width with the rest of the bars. So I hope there will be a better implementation for this where all the bars have the same width and they stick together.
