### ISSUE TITLE
VictoryLine gradient

### ISSUE THREAD

**Issue by icd2k3** [FormidableLabs/victory#575]
Hey there - loving this project!

So far it has hit all my use cases... except one. I have a design requirement for a single line graph where the path changes color based on the current position

ex: _highest_ points of the graph would be green and _lowest_ would be red. 

Closest example I could find of what I'm going for [outlined here](http://www.d3noob.org/2013/01/applying-colour-gradient-to-graph-line.html)
![gradient-line](http://3.bp.blogspot.com/-kx22pbzVhrI/UOTn8eoiaOI/AAAAAAAAAao/oZpoSHZB42U/s1600/gradient-3.png)

I couldn't find anything about this in the docs so I'm assuming this is a feature request.

Thanks!

**Comment by joshuahenson** [comment]
I'm sure someone else can come up with something better but have a look at this [JSFiddle](https://jsfiddle.net/hwho1gjf/) for some ideas.

**Comment by icd2k3** [comment]
@joshuahenson this is perfect - thanks so much for your help! Closing this issue

**Comment by rjz** [comment]
This is awesome--thanks, @joshuahenson, @icd2k3!

One small note to anyone else referencing this ticket: since a stroked horizontal line has no height, a `linearGradient` using `objectBoundingBox` geometry (default) [won't render](https://stackoverflow.com/q/13223636/1040371). If your dataset may include flat values, consider setting [`gradientAttributes='userSpaceOnUse'`](https://www.w3.org/TR/SVG/pservers.html#LinearGradients) instead.
