### ISSUE TITLE
VictoryVoronoiContainer bug with voronoiPadding prop

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#584]
https://jsfiddle.net/boygirl/z00r6h45/

**Comment by boygirl** [comment]
This bug is being caused by incorrect calculation of either the voronoi bounds / extent
https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/voronoi-helpers.js#L10

https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/voronoi-helpers.js#L79

Or by label positioning:
https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/victory-voronoi-container.js#L119

**Comment by Prioritized** [comment]
This seems to be an issue with VictoryLabel.

Without the VictoryLabel, this cursor implementation works fine: [https://jsfiddle.net/u5a77npo/](https://jsfiddle.net/u5a77npo/)

However, the addition of the VictoryLabel adds a couple points that VictoryVoronoiContainer picks up and causes it to render differently due to this line: https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/victory-voronoi-container.js#L111

An example of the VictoryLabel creating points: [https://jsfiddle.net/1f0nbvjw/](https://jsfiddle.net/1f0nbvjw/).

Of course this would be better implemented using #514.
