### ISSUE TITLE
VictoryGraph with VictoryZoomContainer reverts to old values if updated after zoom

### ISSUE THREAD

**Issue by johnhydroware** [FormidableLabs/victory#597]
https://jsfiddle.net/qk8w84of/2/

When started 1) zoom in the graph 2) Click "All" button. New dataset is shown. 3) Click in the graph. The old dataset is now shown.

**Comment by boygirl** [comment]
@johnhydroware thank you for the reproduction.

**Comment by chrisbolin** [comment]
we can see a very similar behavior on http://formidable.com/open-source/victory/guides/brush-and-zoom/. the zoomed seems to "forget" about actions from brush.

**Comment by chrisbolin** [comment]
just a quick update -- making progress on this. It looks like there are two distinct bugs:
1. ZoomContainer doesn't respect outside `zoomDomain` changes (well it does, until you zoom again). This is best seen in the JSfiddle if you zoom, then click "Part", then zoom again. I've been able to fix this bug.
2. ZoomContainer only calculates the `originalDomain` once. This is a theory for now; still investigating. This bug is best seen in the JSfiddle if you zoom, then click "All", then zoom again.

**Comment by chrisbolin** [comment]
fixed (1) bug, ZoomContainer doesn't respect outside `zoomDomain` changes. PR https://github.com/FormidableLabs/victory-chart/pull/475. look for it in a release in the near future.

**Comment by chrisbolin** [comment]
another bug still lingers: ZoomContainer only calculates the `originalDomain` once. This is fine for many cases, but if new data is added (as in the JSFiddle example) the ZoomContainer won't recognize it.

@boygirl how should a _container_ calculate its actually full domain (meaning what it can be zoomed out to)? I looked around `victory-core`, but wasn't sure what path to take.

**Comment by chrisbolin** [comment]
fixed (2) bug, ZoomContainer only calculates the originalDomain once; therefore if new data is added the ZoomContainer wouldn't recognize it. PR https://github.com/FormidableLabs/victory-chart/pull/476
