### ISSUE TITLE
Domain forced to 0 when adding a scatter point

### ISSUE THREAD

**Issue by s-a-hawkins** [FormidableLabs/victory#614]
Hello,

I am trying to add a single scatter on to a line chart but the domain is being forced to 0

![screen shot 2017-06-07 at 11 11 50](https://user-images.githubusercontent.com/29250953/26873845-2d714d26-4b73-11e7-86c8-0ccead2dd11c.png)

The problem is with this code https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/domain.js#L219-L222

if i remove the problem code i get
![screen shot 2017-06-07 at 11 13 52](https://user-images.githubusercontent.com/29250953/26874143-636dd7a4-4b74-11e7-95fc-daa88f2ac679.png)

**Comment by boygirl** [comment]
@s-a-hawkins the bit of code you point out is necessary in order for single data charts to work in isolation. The domain always needs two unique values in order to plot correctly. What's going wrong here is that `VictoryChart` asks all of it's children for a domain, and then takes the maximum extent. So, it sounds like I either need to add an exception in how `VictoryChart` reconciles domains, or make single point domain calculations return something more like `[point - verySmallNumber, point + verySmallNumber]` 

You can temporarily work around this issue by setting a domain in your `VictoryScatter` component. It can be programatically set, something like this: https://jsfiddle.net/boygirl/trsje9nv/

**Comment by s-a-hawkins** [comment]
Thanks that works great
