### ISSUE TITLE
Decoupling zoom & voronoi

### ISSUE THREAD

**Issue by chris-cooper** [FormidableLabs/victory#631]
Hi,

How do I adapt this example so that it zooms on both axes without loosing the tooltip?  If I comment out `dimension='x'` I can zoom in Y but I loose the tooltip.

https://jsfiddle.net/58c7r8xL/

Thanks!

**Comment by boygirl** [comment]
@chris-cooper I ended up removing the custom label component, and it's working okay with `VictoryTooltip`. https://jsfiddle.net/boygirl/xyq0uwb8/
I do notice some offset oddities on the zoomed in tooltip, though.

Also, if you're wanting cursor labels you can make a zoom + cursor hybrid like so: https://jsfiddle.net/boygirl/f7vxocqd/

**Comment by chris-cooper** [comment]
Thanks @boygirl.  Sorry it looks like I forgot to link to [the mutli-point tooltips example](https://formidable.com/open-source/victory/guides/tooltips/#mutli-point-tooltips-with-victoryvoronoicontainer).  I'm actually after all of these in one chart...

* the label stacking in [the multi-point example](https://formidable.com/open-source/victory/guides/tooltips/#mutli-point-tooltips-with-victoryvoronoicontainer)
* a vertical cursor
* zoom in both axes 
* preferably with full control and customisation of the label

https://jsfiddle.net/oho1v1qt/

My current thinking is to try adapting your second zoom + cursor hybrid example with a custom `cursorLabelComponent` and use the x value to lookup all the values I need and form my own fully custom multi-value label.

**Comment by chris-cooper** [comment]
e.g. something like this:

https://jsfiddle.net/djdxo45p/

Seems non ideal though with the data lookups etc.  Also, any ideas what is causing the small offset?

**Comment by chrisbolin** [comment]
@chris-cooper brilliant hack with `cursorLabelComponent`! I didn't foresee that :)

You can fix the offset with `cursorLabelOffset={0}`, which sets the offset for `cursorLabelComponent` ([cursorLabelOffset docs](https://formidable.com/open-source/victory/docs/victory-cursor-container#cursorlabeloffset))

**Comment by chrisbolin** [comment]
example of the above fix: https://jsfiddle.net/chrisbolin/jf6047m6/1/

**Comment by chrisbolin** [comment]
@chris-cooper here's a demo that I _think_ gets you what you want:

![jul-03-2017 13-12-57 - zoom cursor](https://user-images.githubusercontent.com/2822048/27791294-97e7698e-5ff4-11e7-8d9c-a2e5ffb0339d.gif)

https://jsfiddle.net/chrisbolin/jf6047m6/4/

We need to document the prop I used, cursorComponent. That issue is here: https://github.com/FormidableLabs/victory-docs/issues/379

We also have a silly issue with the x-axis when using negative data and zooming: https://github.com/FormidableLabs/victory/issues/635

And finally, I'm following up on the bugs @boygirl mentioned when using `createContainer` here: https://github.com/FormidableLabs/victory/issues/634

**Comment by chris-cooper** [comment]
Ah thanks for the cleanup and extra info @chrisbolin!  I'll head down this route for now.  And thanks for reporting those other issues, I'll keep an eye on them.

**Comment by chrisbolin** [comment]
for bookkeeping, I'm going to go ahead and close this issue. we have other issues we're tracking the bugs with, and i think we might have found a suitable approach for a cursor-that-has-voronoi-features :) 

feel free to still use this thread though
