### ISSUE TITLE
Code: Refactor `export default {}` objects to one-off exports.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/victory#650]
### Background

Tree shaking relies on named specific exports and can't pick from mega objects. Throughout our victory repos code we have patterns like:

```js
export default {
  circle(x, y, size) {
    // CODE
  },

  square(x, y, size) {
    // CODE
  },

  plus(x, y, size) {
    // CODE
  },

  star(x, y, size) {
    // CODE
  }
};
```

which we should refactor to:

```js
export const circle = (x, y, size) => {
  // CODE
};

export const square = (x, y, size) => {
  // CODE
};

export const plus = (x, y, size) => {
  // CODE
};

export const star = (x, y, size) => {
  // CODE
};
```

### Task

- [ ] Identify all `export default {}` that are actually individual objects / vars we should individually export
- [ ] Leave things like prop objects or legitimate first class objects that should be exported as a whole.

**Comment by ryan-roemer** [comment]
@beccanelson and I were chatting Victory + Lodash + tree-shaking today, and in checking out https://unpkg.com/browse/victory-core@35.9.0/es/victory-util/helpers.js I noticed a huge default export that can't be tree-shaken:

```

**Comment by beccanelson** [comment]
@ryan-roemer @boygirl I can re-open this issue - it looks like there are several files in `victory-util` that will need to be updated.

Based on the initial research I have done, it sounds like we can namespace these files, and still support tree-shaking. This means that instead of `import Helpers from './helpers'` we can use `import * as Helpers from './helpers'`. https://stackoverflow.com/a/45746950

As far as I know, we can also use `@babel/plugin-proposal-export-namespace-from` to `export * as Helpers from './helpers'` in the index so we can still `import { Helpers } from 'victory-core'`. 

Other than changing a few imports (and adding function exports to the utils), this shouldn't require many changes to the code itself. Does this sound reasonable?

**Comment by boygirl** [comment]
@beccanelson That sounds like a good course of action. Thank you!
