### ISSUE TITLE
Tool tip breaks with zoom dimension set to "y" 

### ISSUE THREAD

**Issue by prestond123** [FormidableLabs/victory#667]
Have noticed a couple of issues with the tooltip when the dimension is set to "y" only.

Here is a fiddle.  
https://jsfiddle.net/wxpvvLob/1/
https://jsfiddle.net/se90Ldkg/4/

**Comment by boygirl** [comment]
@prestond123 this is definitely very weird looking, but what's going on here, is that you're trying to make a tooltip that displays all the points that have the same y-value, and your data happens to be a horizontal line, so that's something like 50 data points with all the same y value. The tooltip ends up looking crazy, but this is the expected behavior for voronoi tooltips with dimension="y"

**Comment by boygirl** [comment]
The padding on the tooltip definitely not correct though. I will look into that separately.
