### ISSUE TITLE
Custom Tooltip Demo broken

### ISSUE THREAD

**Issue by Utzel-Butzel** [FormidableLabs/victory#672]
The Pie Chart Behavior has changed (transform added to Pie elements) and the Custom Tooltip Label Demo is broken. The Tooltip is no longer centered, it is in the top-left corner now.

http://formidable.com/open-source/victory/gallery/custom-tooltip-labels

<img width="384" alt="bildschirmfoto 2017-07-25 um 14 19 37" src="https://user-images.githubusercontent.com/3281586/28571680-5276d16c-7144-11e7-9a90-f1f05b626ad2.png">

Why did it has changed?

**Comment by boygirl** [comment]
@Utzel-Butzel labels for `VictoryPie` are now given correct `x` and `y` props rather than being translated along with slice elements. This was changed so that labels for `VictoryPie` would be correctly positioned when rendered in `VictoryPortal`, and so that label positioning behavior would be more consistent between components. The demo you link to uses absolutely positioned labels, that _used_ to be translated along with the pie group. I will correct the absolute positioning in that demo. Opening a new issue in `victory-docs`

**Comment by Utzel-Butzel** [comment]
@boygirl I think it would be also useful to have access to the width and (calculated) height of the svg Element to be able to center anything correctly.
