### ISSUE TITLE
Default axes show up when VictoryAxis contained in wrapper

### ISSUE THREAD

**Issue by Gallinaryoso** [FormidableLabs/victory#689]
VictoryChart has default axes that fit the data when no axes are provided. When a VictoryAxis is contained within a wrapper, VictoryChart [includes the default axis anyways](https://jsfiddle.net/Gallinaryoso/gcqbx75e/) as opposed to axes [not contained in a wrapper](https://jsfiddle.net/Gallinaryoso/yzvLa5k6/). I'm ideally looking to avoid having the wrapper extend VictoryAxis as @boygirl [suggested](https://gitter.im/FormidableLabs/victory?at=595d3eb82723db8d5edf62eb). Is there any other way to work around this besides providing extra empty axes in VictoryChart to prevent the default axes from showing up?

**Comment by boygirl** [comment]
@Gallinaryoso you can also alter the `defaultAxes` prop in `VictoryChart` like so: 
`defaultAxes={{ dependent: <g/>, independent: <g/> }}` but you will get a warning about unknown props supplied to `<g/>` tag. You need to provide _some_ component, because `VictoryChart` expects to use `React.cloneElement`. To avoid the warning, you could just create a dumb component that renders nothing.
