### ISSUE TITLE
Props missing in Victory Legend groupComponent in 0.21.3

### ISSUE THREAD

**Issue by jeffreypriebe** [FormidableLabs/victory#692]
Using a Vicotry Legend and passing a groupComponent may fail, since it gets different props in 0.21.3 than 0.21.2 (and previous). Example failure:
```
<VictoryLegend
        data={legendData}
        standalone={false}
        groupComponent={<LegendGroupTest />}
/>
```

In 0.21.3, the `LegendGroupTest` will have `width` and `height` props of '0' instead of actual values.

The same code in 0.21.2 will get valid `width` and `height` values.

PR with test showing failure coming.

**Comment by boygirl** [comment]
The change from 0.21.2 to 0.21.3 enforced consistency between VictoryLegend and other Victory components.

The props passed to containerComponent are specifically excluded from groupComponent. Most passed props cause a warning (unexpected prop x supplied to g... ) Though width and height don't cause this error, they also don't have any effect because, svg <g> elements don't have explicit height and width attributes, they auto size to whatever they contain.

So, this test should fail. Can you tell me more about your use case?

(p.s. If you're writing a custom groupComponent, and you'd like access to the props that are usually passed to your containerComponent you can add static role = "container"; to your groupComponent)
