### ISSUE TITLE
Bug: VictoryLabel with array format style prop

### ISSUE THREAD

**Issue by soulwu** [FormidableLabs/victory#694]
Code to reproduce the problem
```
<VictoryChart>
  <VictoryLabel
    text={['aaa', 'bbb']}
    x={100}
    y={100}
    style={[{fill: '#f00'}, {fill: '#ff0'}]}
  />
</VictoryChart>
```

Expect two labels, red `aaa` and yellow `bbb`
Actual only default style apply to them.

When I debug into the code, I found that the `style` prop will be converted to `{0: {fill: '#f00'}, 1: {fill: '#ff0'}}`
I thought `style` maybe a special prop in React?
If rewrite `VictoryLabel` like below:

```
export default class extends VictoryLabel {
  getStyles(props) {
    return Array.isArray(props.styles) ?
      props.styles.map((style) => this.getStyle(props, style)) : [this.getStyle(props, props.styles)];
  }
}
```

the problem solved.

**Comment by boygirl** [comment]
@soulwu 

This was actually happening only for labels that were children of wrapper components like `VictoryStack` and `VictoryChart`, because those components were trying to merge their styles with the label styles, resulting in an object when there should have been an array. 

The fix for this issue will be released early next week Thanks for pointing it out!
