### ISSUE TITLE
Charts in flexbox-items don't adapt to their container's size

### ISSUE THREAD

**Issue by Nimelrian** [FormidableLabs/victory#698]
I'm trying out Victory for one of our web apps right now. I have a flex container with a fixed width and height (200px), flexing in column direction. Inside I have one child with a fixed height (38px). The second child should be a victory area chart, taking the remainder of the container's height. Now, when I just pop in a <VictoryArea /> it overflows the container. According to the docs the charts should be responsive, under which I understand that they should fill the space of their container.

Here's a short snippet to reproduce the problem ([codesandbox link for a quick look](https://codesandbox.io/s/kRGPgMVzX)):
```jsx
import React from "react";
import { render } from "react-dom";
import { VictoryArea, VictoryChart } from "victory";

const styles = {
  fontFamily: "sans-serif",
  display: "flex",
  flexDirection: "column",
  height: 200,
  width: 800,
  border: "1px solid black"
};

const headerStyles = {
  display: "flex",
  alignItems: "center",
  paddingLeft: 7,
  flexShrink: 0,
  height: 38,
  width: 800,
  borderBottom: "1px solid black"
};

const chartContainerStyles = {
  flex: "1 0 0px"
};


const App = () =>
  <div style={styles}>
    <div style={headerStyles}>I'm the header</div>
    <div style={chartContainerStyles}>
      <VictoryChart>
        <VictoryArea />
      </VictoryChart>
    </div>
  </div>;

render(<App />, document.getElementById("root"));
```

How can I make it fit inside the chart container (sibling of header-div)?

**Comment by SamSimmons** [comment]
Hey, I'm not a victory contributor or anything, and I can't answer your question properly 😂

But I had a similar problem recently and solved it by using `flex-flow: row wrap` on the container and setting the header to have a `flex-basis` of `100%` so it would push the body container down below.

Then you can set the height to be calc(100% - the size of your header)

```
const styles = {
  fontFamily: "sans-serif",
  display: "flex",
  flexFlow: "row wrap",
  height: 200,
  width: 800,
  border: "1px solid black"
};

const headerStyles = {
  display: "flex",
  alignItems: "center",
  paddingLeft: 7,
  flexShrink: 0,
  height: 38,
  width: 800,
  borderBottom: "1px solid black"
};

const chartContainerStyles = {
  flex: '1 1 auto',
  height: 'calc(100% - 38px)'
};
```

Would work in your example, it's bit hacky and relies on you knowing the height of the header.

I'm pretty sure there'd be a cleaner way to make this work though, but I think the problem might be flexbox columns working with having heights and widths set, rather than a problem with victory.

**Comment by david-davidson** [comment]
Hi @Nimelrian,

I think @SamSimmons is on the right track in looking at the flexbox setup itself! I've seen some similar problems having to do with the fact that flex items, by default, don't shrink below their minimum content size. What we want is for `chartContainerStyles` (flex item) to force the chart (min content size) smaller; what we get is the chart forcing `chartContainerStyles` larger.

To test that possibility, try adding `minHeight: 0` to `chartContainerStyles` in your app -- that appears to fix the sandbox:
```
const chartContainerStyles = {
  flex: "1 0 0px",
  minHeight: 0
};
```  
It works because:
> By default, flex items won’t shrink below their minimum content size (the length of the longest word or fixed-size element). To change this, set the min-width or min-height property.

(from https://www.w3.org/TR/css-flexbox-1/)

So, the important thing isn't necessarily that the min height be 0 -- it's that a min height be set _at all_. (Could be a different value makes sense for your use case.)

Give it a try!

**Comment by boygirl** [comment]
I'm closing this one, but making a note to add something similar to the docs https://github.com/FormidableLabs/victory-docs/issues/380

**Comment by astone2014** [comment]
> Hi @Nimelrian,
> 
> I think @SamSimmons is on the right track in looking at the flexbox setup itself! I've seen some similar problems having to do with the fact that flex items, by default, don't shrink below their minimum content size. What we want is for `chartContainerStyles` (flex item) to force the chart (min content size) smaller; what we get is the chart forcing `chartContainerStyles` larger.
> 
> To test that possibility, try adding `minHeight: 0` to `chartContainerStyles` in your app -- that appears to fix the sandbox:
> 
> ```
> const chartContainerStyles = {
>   flex: "1 0 0px",
>   minHeight: 0
> };
> ```
> 
> It works because:
> 
> > By default, flex items won’t shrink below their minimum content size (the length of the longest word or fixed-size element). To change this, set the min-width or min-height property.
> 
> (from https://www.w3.org/TR/css-flexbox-1/)
> 
> So, the important thing isn't necessarily that the min height be 0 -- it's that a min height be set _at all_. (Could be a different value makes sense for your use case.)
> 
> Give it a try!

.... WHY DOES THIS WORK!?!
