### ISSUE TITLE
Axis trouble; warning

### ISSUE THREAD

**Issue by janusch** [FormidableLabs/victory#72]
Hey,
it is really nice that you put in warnings for cases that are not doable (yet)!!!

I have a question regarding one warning: 
`Only one VictoryAxis component of each axis type is allowed when using the VictoryChart wrapper. Only the first axis will be used. Please compose multi-axis charts manually`

What exactly do you mean by `Please compose multi-axis charts manually`
That it should be done outside the VictoryChart component in an svg, or could it be in another VictoryChart wrapper component?

And what exactly is an "axis type"? Is the type defined by the `orientation` prop?

Generally, it is a bit trouble some to get rid of the default axis for me. Is it right now possible to have an axis at the right and at the top without the other two?

Somehow I also cannot manage to set tickValue to something independent of x or y, should that be doable?

Lastly, I recognized two things about axis, they somehow influence each other sometime, e.g. left and bottom and order of VictoryAxis components matters.

I highly appreciate your work on this project and hope to be able to contribute in a more constructive way than pinpointing oddities and asking questions.

Thanks in advance if you get the time to reply to the questions.
Have a nice weekend!

**Comment by boygirl** [comment]
@janusch thanks for your detailed questions. Fresh eyes really help make the API more understandable. 

`Please compose charts manually` means it should be done outside of chart. [Here's an example](https://github.com/FormidableLabs/victory-examples/blob/master/demo/app.jsx) of composing a chart with three axes in an svg. 

The VictoryAxis component has a concept of independent / dependent axes (defined by the `dependent` prop) that is separate from orientation (`top`, `bottom`, `left`, `right`). We are working on supporting horizontal bar charts and other flipped axis scenarios, so we needed to distinguish independent/dependent from orientation. 

If you're using VictoryChart, there are default independent and dependent axes, but if you provide an axis component it will replace the default. You should only ever end up with two axes if you are using VictoryChart. So for your scenario of having top and right oriented axes, your chart code would look like:
```
<VictoryChart>
  <VictoryAxis orientation="top"/>
  <VictoryAxis dependent orientation="right"/>
  ...
</VictoryChart>
```
The order of the two axes shouldn't matter that much, but since everything is svg, the order will determine which axis is drawn on top. Axis components don't explicitly know about each other at all, VictoryChart acts as a coordinator, and passes additional props like `offsetX` to its axis children so that they line up correctly.

I'm not sure I understand your question about `tickValues`... Those should come in as an array of values like `[1, 2, 3]`, or `["cats", "dogs", "birds"]`. The `tickFormat` prop determines how `tickValues` will be displayed, and it can either be an array of equal length, or a function to be applied to each values in the array, like so:
```
tickValues={[1, 2, 3]}
tickFormat={(x) => x.toPrecision(2)}
// resulting ticks displayed on the axis => "1.0", ""2.0", "3.0"
```

I hope that answered your questions. Let me know if I missed anything.

**Comment by janusch** [comment]
@boygirl thank you very much for answering my questions with such a detail!
Most is clear for me now, and I got a working chart with 5 axis. 
What made it work is by specifying the values for the ticks in the tickFormat prop, which I hadn't thought of before, and the naming confused me.
I also moved the graph out of the VictoryChart component and composing many axis became possible.

Maybe it would make sense to mention the limitations of the VictoryChart component in the docs. I understood it as a general wrapper for charts. Also starting with a svg and composing charts into that should be highlighted in the docs, the way I see it is that that's where the real power of victory lays.

I can imagine that it must be quite hard to write documentation for this project because of the features of the underlying d3 library. It could make sense to link to some of the d3 documentations, for props like scale, domain, range etc.  

I am going to open another issue about some problems I am having with styling of different components.

The victory chart I made will hopefully soon go in production, yay!

Keep up the excellent work!

**Comment by coopy** [comment]
> `Please compose charts manually` means it should be done outside of chart.

@boygirl, Is this still true? Can one now add more than 2 `<VictoryAxis/>` components to `<VictoryChart/>`, or is the intent for `<VictoryChart/>` to always represent a 2-dimensional plot?

> Maybe it would make sense to mention the limitations of the VictoryChart component in the docs. I understood it as a general wrapper for charts.

This sounds reasonable to me. @janusch Looking at http://victory.formidable.com/docs/victory-chart/, do you have any ideas for improving the docs?

**Comment by janusch** [comment]
@coopy Yea, I do. I think as you already point out would be good to clarify the purpose right at the top.
Furthermore, it would be great to have an exhaustive list of props and especially prop values that can get passed into the component. For me the example values were the most valuable in the documentation, the ones in the table describing the different props. I just think that there are a few missing, e.g. on the style prop the names of things that can get style could be mentioned.

Generally I do not understand the value of adding default values, for me they have been more in the way. I understand that it is nice to have for some examples, but when would anybody ever need a default chart? It would be nice if that could be an opt-in feature.

Concerning the axis component, I was already thinking of forking the existing one to create one that is not that intelligent. In my case the Y-axis was supposed to be on the right side, so it got the prop orentation="right". That did move the axis to the right and to my surprise also switched the whole graph going the other direction. I would not have expected that the y-axis would be able to do something like this. Having a "dumb" axis that can just get thrown in when you need an extra one would be useful for this.
I got to say that I am not sure if it is intended by victory or if d3 does funky things like this, or if it is my own implementation that resulted in this. And I am fully aware that victory is still alpha ware therefore did not want to bother the developers with unnecessary issues that might not be issues or bugs at all.

Trying to answer your question, I would render everything in an svg. just set the VictoryChart component to `standalone={false}` and you can combine many of those and add axes as you go. I am sure that many of those little issues will resolve. Have fun trying victory!
