### ISSUE TITLE
Styles not mandatory should not be hard-coded

### ISSUE THREAD

**Issue by ylacaute** [FormidableLabs/victory#721]
Hi !

Note that this issue is directly linked to this closed one : #559

Why a new issue ?
What are doing modern web developpers ? They do JS, make a chart and custimze it in SASS/LESS (especially for colors). That is the real life. How a so beautiful and complex framework could not manage a so basic use case ? Separating the style from the content is still mandatory even if framework like react allow to do special stuff.

@timhwang21 asked 

> How to disable default inline styles?

@boygirl response : 

> You can't, if you want to customize colors in CSS you have to copy past components source code  or define your own custom `dataComponent` (which can just extends existing one etc). 

Sorry if I didn't undesrtand well, I am just discovering this framework and was immedialty stopped because I coudn't customize it with SASS. I don't like the the idea of immediatly doing "custom things"...

Currently we can use !important in SASS with some ugly rules like "svg svg g:nth-child(3) g path" to just get a specific line for example... Ugly because we can't set a class name either, to anything.

What we could do :
1) A theme is enabled by default. We can change it by setting an other. But if you explicitely set "none" or null or whatever, you don't use any theme/inline style and it is the responsability of the user to positionnate element correctly
2) Add a property "className" to all elements, it could make happy all those people writing some rules in CSS avoiding ugly rules as above :)

What do you think about that ?

**Comment by boygirl** [comment]
Hi @ylacaute 

Thank your for trying Victory! Fortunately, the issue you reference is very old, and the library improved a lot since then.

Victory _already_ supports adding a `className` to any `dataComponent`, `labelComponent` etc. Use this functionality like `dataComponent={<Bar className="myBar"/>}` 

If you don't want to use any styles from themes, you can pass in an empty object like `theme={{}}`

I'm going to close this issue, but let me know if you're still finding it too difficult to work with Victory + CSS.  Victory is opinionated about inline styles, and so much more is possible with inline styles (like functional styles), but we don't want to force users to abandon CSS.

**Comment by ylacaute** [comment]
Thank you for your answer !

Concerning theme, when you pass {} as theme the framework still defines some styles especially black stroke. So there is still a kind of "default black theme" for me. **I don't see any good reason to put some colors inline style (and even any other inline styles) when you explicitely ask to do not.**

I can imagine there are technical limitation due to the opinionated about inline but I still believe the workaround of reading default values when style values is not defined should not be so hard.

Anyway ! I am also opend to anyworkaround, but I don't undertand dataComponent :)

Here is a simple test graph, let's say we want a CSS class for each tag, how you do that with dataComponent ??

```
        <VictoryChart domainPadding={0} theme={ezVictoryTheme}>
          <VictoryAxis
            tickValues={[1, 3, 5, 7]}
            tickFormat={(x, i) => x}
          />
          <VictoryAxis
            dependentAxis
            tickFormat={(x) => (`${x} SP`)}
          />
          <VictoryLine
            className="plannedVelocity"
            data={plannedVelocity}
            x="date"
            y="storyPoints"
          />
          <VictoryLine
            className="currentVelocity"
            data={currentVelocity}
            x="date"
            y="storyPoints"
          />
        </VictoryChart>
```

**Comment by boygirl** [comment]
@ylacaute 

Even if you don't add any styles to an svg path element, it will render with a black fill, and a line element without any styles applied will render with a black stroke. These are not hard-coded values in Victory. 

Victory _does_ and will continue to have defaults that affect layout and positioning of elements because we believe in sensible defaults and want charts to render and look like charts with a minimum of user information. 

Something I think you are misunderstanding is the relationship between Victory tags and rendered elements. 

`VictoryLine` is not a rendered element. Instead it coordinates logic for rendering simple elements `Curve` and `VictoryLabel` when appropriate. (Seems a little weird for line, but makes a lot of sense for things like `VictoryBar` and `VictoryScatter` that render several `Bar` and `Point` components respectively.) This is done so that users can customize simple components without having to replicate all the logic that goes into correctly positioning elements in a chart. 

To get classNames on your rendered elements, you will want to add them to your simple elements. No need to write any custom elements, Victory exports all the primitive components like `Curve`, `Bar` etc that you would need. Your code would look like so:

```
<VictoryChart>
  <VictoryAxis
    tickValues={[1, 3, 5, 7]}
    tickFormat={(x, i) => x}
    axisComponent={<Line className="axisLine"/>}
    tickLabelComponent={<VictoryLabel className="tickLabel"/>}
  />
  <VictoryAxis
    dependentAxis
    tickFormat={(x) => (`${x} SP`)}
    axisComponent={<Line className="dependentAxisLine"/>}
    tickLabelComponent={<VictoryLabel className="tickLabel"/>}
  />
  <VictoryLine
    data={plannedVelocity}
    dataComponent={<Curve className="curve1"/>}
    x="date"
    y="storyPoints"
  />
  <VictoryLine
    data={currentVelocity}
    dataComponent={<Curve className="curve2"/>}
    x="date"
    y="storyPoints"
  />
</VictoryChart>
```

**Comment by boygirl** [comment]
Most components have `dataComponent` and `labelComponent`.  `VictoryAxis` has different named components. You can read about them here: https://formidable.com/open-source/victory/docs/victory-axis.

Any prop that ends in `Component` like `axisComponent` will be something that is actually rendered. The docs will also tell you what the default value is for each of these props, so that you don't have to guess when you're wanting to add props to one of the primitive components.

**Comment by ylacaute** [comment]
I think you wrong about SVG : it doesn't introduce inline style inside HTML, what Victory does. Since inline styles have the highest priority, it forces to use `!important` in any styles defined in CSS (and this is the exact reason inline styles should only be used in last resort, otherwise it kills CSS features). If you were rights, that would mean we always have to use `!important` in CSS, which is definitevely not the case.

Thank you anyway for your code answer :) Sorry, but this workaround is not really beautiful :D It forces the user to already use strange custom things for a very basic chart... All this for a className property, the most important attribute for an HTML tag.

For now, I prefer stick with the native way of doing and use !important in SASS. For example :

```
.widget.burndownchart svg {
  svg {
    g:nth-child(1) line,  // MAIN VERTICAL AXIS
    g:nth-child(2) line { // MAIN HORIZONTAL AXIS
      stroke: $color-chart-burndown-tick !important;
      stroke-dasharray: none !important;
    }
    g:nth-child(1) g line,  // VERTICAL AXIS TICKS
    g:nth-child(2) g line { // HORIZONTAL AXIS TICKS
      stroke: $color-chart-burndown-tick !important;
      stroke-dasharray: none !important;
    }
   ...
}
```
I would prefer use cass class but it's ok ;)

**Comment by boygirl** [comment]
Victory is meant to work with inline styles. This is not an arbitrary decision. In data visualization, the style of an element and the data it represents are inherently coupled, and we believe it makes sense to work with them as a unit. Victory provides a lot of tools to allow _data_ to drive style choices. For example, something like `fill: (datum, active) => active || datum.y  > 3 ? "red" : "blue"` is possible using inline styles in Victory. 

The concept of themes was introduced to help people who wanted to extract shared styles in a more classical separation of concerns. Styles provided in themes are merged with those on the style prop, so that all are actually applied inline, and you don't end up with naming or specificity headaches. 

Finally, we also added support for `className` for folks who really wanted to use some CSS. This makes a lot of sense for someone who might want to apply existing site-wide text styles to labels on their charts and things like that. But, as you say, it is not the most beautiful solution for styling data within a chart, as it requires jumping through the hoops I mention above. 

Easier / more elegant support for styling Victory via CSS is not a priority, as I believe the issue comes down to philosophical differences. That said, if you find something that is _impossible_ to do in Victory I will work to make it possible (if slightly annoying) so long as it doesn't compromise or complicated other functionality in Victory.

**Comment by ylacaute** [comment]
What you are saying make sense, I understand that in some complex charts/graphs, the style is very dependent of the data. I can imagine the separation of concern can be a very hard challange. In basic chart, it should be easier :)

You example is interesting :
`(datum, active) => active || datum.y > 3 ? "red" : "blue"`
Why it make sense to colorize in red some active data or datum.y > 3 ? Why did you choose the same color ? The answer is your className.

In most cases, no need to search to much, we could simplify like this :
`className = {(datum, active) => active || datum.y > 3 ? "active" : "inactive"}`

Happy you took time to answered me, it was interesting. Apart from the inline style, I have to say Victory is intuitive with a quick and easy integration in React app, at least for the first step of a newbie ! I tryed some different graph frameworks, I had problem I didnt got with Victory :)

**Comment by boygirl** [comment]
@ylacaute I'm glad you're enjoying Victory. If you get a chance, give it a try with inline styles. No need to abandon CSS entirely, but for something like coloring a line, I think you'll find it a much, much nicer experience.
