### ISSUE TITLE
Same values

### ISSUE THREAD

**Issue by kserjey** [FormidableLabs/victory#734]
Unexpected ordinate value if data have same values. Also I need only integer values on axises. How can I handle this?

```javascript
<VictoryChart>
  <VictoryAxis/>
  <VictoryAxis dependentAxis/>
  <VictoryLine 
    /* fetched data from API */
    data={[{ id: 502, count: 1 }]} 
    y='count'
  />
</VictoryChart>
```

![image](https://user-images.githubusercontent.com/19753880/29933535-a1e83688-8e80-11e7-9db5-b2de5064475c.png)

**Comment by boygirl** [comment]
@kserjey This is happening because you have no `x` value either in your data object, or specified via the `x` prop. Victory is seeing only a `y` value, and thinks you might be trying to plot a function, so it has cleverly (not-so-cleverly) provided you with some x values to plot over. You can fix this by providing an `x` value (in your case `x="id"`). You might also wish to provide a domain if you're only expecting a single data point, or you will run into more default behavior that will attempt to center single data points. 

In order to have integer axis values, you can just format your ticks to display rounded values like `tickFormat={(tick) => Math.round(tick)}`. This prop goes with `VictoryAxis`

**Comment by kserjey** [comment]
Ok, can I set x as data index?

**Comment by kserjey** [comment]
Well, I think I fiqure it out.
