### ISSUE TITLE
orientation="right" renders data rtl

### ISSUE THREAD

**Issue by Morriz** [FormidableLabs/victory#739]
Why is data direction not configurable too? I read a hacky suggestion somewhere about offset changes, but this is too crude and unwieldy. Plus, Victory won't let me render the axis invertedly.

**Comment by boygirl** [comment]
@Morriz The `offsetX` and `offsetY` props are what `VictoryChart` uses to move axes around, and this is the recommended way to manually position axes. Setting `orientation` is intended to flip the direction of your data. That's the current expected behavior. Can you explain what you would think the expected behavior _should_ be?

**Comment by Morriz** [comment]
I understand, but am asking for another property to make the data go its own direction. So no dirty hacks are needed.

**Comment by boygirl** [comment]
@Morriz 

If I understand correctly your request is: 
1) `orientation` should set only the location of axes and not alter the domain
2) a new prop, something like `invertDomain` should be a flag that inverts the domain

I think this is a reasonable request, but it will be a breaking change for the API, so implementation will be delayed.

`offsetX` and `offsetY` are supported, documented props. This community values precision of language and constructive feedback. Referring to a design decision as a "dirty hack" is not constructive.

**Comment by Morriz** [comment]
No, we can keep it as is. And then just add extra prop to invert domain. No breaking change needed ;)

**Comment by krugar** [comment]
i would very much like the current documentation text for [victory-axis](https://formidable.com/open-source/victory/docs/victory-axis) on orientation to explicitely point out that it also flips data direction, because at least one person did have to throw "orientation" into the issue tracker to find out what it actually does ^^

> orientation
> The orientation prop specifies the position and orientation of your axis. Options are "top", "bottom", "left", and "right".

and +1 to Morriz suggestion of a "don't flip the data"-toggle that can be tacked onto the current behaviour as a non-breaking change (ie: without the new prop, both axis and data get flipped, but if the prop is present, only the axis is flipped).
