### ISSUE TITLE
performance decline for voronoi + zoom containers

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#744]
from @prestond123
Performance noticeably declines between victory versions `0.21.2` and `0.21.5`.

**Comment by prestond123** [comment]
Hi Lauren,

I can reproduce this with the below two fiddles.
The only difference is the version of Victory: 0.21.2 -> 0.21.5

Load them into two separate browser window instances, rather than separate tabs, if you want to do side by side.

There are a lot of datapoints (~22k I've filtered some out), but I have seen this with fewer ( >= 8k)

Ensure the mouse does not enter the chart area while the FiddleJs is loading.

Once the chart is displayed (may take a little time), put the mouse over it.

For me, on 0.21.2 it takes about 3 seconds for the tooltip to appear. if you try to interact with the JavaScript in the JS panel it is not available for another 2-3 seconds, the browser is too busy.

On 0.21.5, when i put the mouse over the chart, the browser never recovers.

I've been doing this in chrome mainly, but can also reproduce in firefox.
(IE11 doesn't draw the charts in the fiddle, not sure why)

0.21.2: https://jsfiddle.net/u1dt32bq/3/

0.21.5: https://jsfiddle.net/zhoyxeze/2/

Thanks

**Comment by prestond123** [comment]
0.21.5: https://jsfiddle.net/wovvss1c/8/
notice performance issue when over 500 data point +  3000 locks browser up

021.3 https://jsfiddle.net/wovvss1c/6/
over 2000 datapoints is OK - 300 + dosnt lock browsers
