### ISSUE TITLE
too many tooltips when zooming on Y

### ISSUE THREAD

**Issue by prestond123** [FormidableLabs/victory#756]
I've mentioned this before, and it was explained to me why it happens, but I don't think this is right.  I dont think that the tool tip should appear like this when zooming on Y only.  It is not useful.

![tooltips on yzoom](https://user-images.githubusercontent.com/26113279/30697326-7e6f322c-9ed6-11e7-919f-48242b3354b9.png)

**Comment by boygirl** [comment]
@prestond123 
I'm guessing about why this is happening, so please tell me if I'm getting it wrong: 

I think this is happening because you are using `createContainer` to make a hybrid zoom + voronoi container. You are only zooming in the y dimension, so you have `dimension="y"` set on your hybrid container. Unfortunately, this also adds the `dimension="y"` behavior for voronoi containers. The solution would be to give the dimension prop a unique name for each container so that these behaviors can be separated. Something like `zoomDimension` `voronoiDimension` etc. 

This will be a breaking change, but an important one.

**Comment by prestond123** [comment]
Yes that is exactly what I'm doing, creating a hybrid, exactly like you described. Thanks

**Comment by boygirl** [comment]
Released in `victory@0.23.0`
