### ISSUE TITLE
Tooltip bigger than height of grid on stacked chart

### ISSUE THREAD

**Issue by prestond123** [FormidableLabs/victory#757]
There are 11 datasets stacked in the below chart/image.  When zoom is set to Y, the voronoi tool tip expands till it is much bigger than the display area, and has a lot padding above and below the values.
Before zoom:
![voronoi-tooltips on yzoom1](https://user-images.githubusercontent.com/26113279/30699073-a0a8a7ba-9edb-11e7-86d6-6709cf8d5342.png)

After zoom:
![voronoi-tooltips on yzoom](https://user-images.githubusercontent.com/26113279/30698904-2d651518-9edb-11e7-941a-5c837b6ac10e.png)

Also, during zoom the CPU maxed out for several seconds

**Comment by boygirl** [comment]
@prestond123 this is actually happening because our `TextSize` utility is overestimating height. With this many lines of text, each small overestimation adds up. Unfortunately we are _approximating_ rather than measuring text size, so some discrepancy is to be expected. I'll see what I can do to improve the estimation, though.

**Comment by boygirl** [comment]
I can't reproduce the issue you're seeing on zoom, however.

**Comment by prestond123** [comment]
I'll try to create a fiddle to reproduce, probably next weeks. Thanks.

**Comment by boygirl** [comment]
This issue is fixed is greatly improved in `victory@35.0.0` which includes improvements to the text size approximation we use to calculate tooltip dimensions.
