### ISSUE TITLE
Add `alignment` prop for VictoryBar

### ISSUE THREAD

**Issue by corradio** [FormidableLabs/victory#764]
Hi,

First of all, thanks for the great work here.
Looking at https://formidable.com/open-source/victory/docs/victory-bar, I could not find a way to position the bars such that they start and end at the ticks, instead of being centred around the ticks.
Any way to do this?

Best workaround I've found is to use a VictoryLine using stepAfter, but this prohibits setting a colour by bar, as the colour affects the whole path.

Best,

Olivier

**Comment by boygirl** [comment]
@corradio @djmax currently you can add a transform to either your bar primitive or your group component. 
I'm also considering adding an `alignment` prop for VictoryBar since this feature has seen reasonable demand. I've resisted this idea for a long time since it has the potential to create inaccurate charts.

**Comment by boygirl** [comment]
Proposal: 

Add `alignment` prop to `VictoryBar` and `Bar` primitive. This prop would only alter the path

**Comment by jmjpro** [comment]
I think we also need to add the alignment prop to the VictoryBar typescript interface.
