### ISSUE TITLE
Animating Circular Progress Bar issues in 0.23.0

### ISSUE THREAD

**Issue by bhellman1** [FormidableLabs/victory#773]
Hello, the following example does not work in 0.23.0: 

https://formidable.com/open-source/victory/gallery/animating-circular-progress-bar

My downgrading to v0.22.2 I was able to get the example to work as expected. 

The issue is w 0.23.0, the percentage % renders and animates but the actual progress bar never appears.

**Comment by boygirl** [comment]
@bhellman1 you're too fast for me! I haven't yet updated the docs for `victory@0.23.0`. There were several breaking changes that you can read about here: https://github.com/FormidableLabs/victory/blob/master/CHANGELOG.md

The example you mention can be fixed by adding `standalone={false}` to `VictoryPie`. The change that breaks this example is that Victory containers now render divs as the outermost element rather than svgs

**Comment by alansutherland** [comment]
@boygirl still broke
