### ISSUE TITLE
VictoryBar with one bar moves y axis in the middle of x axis

### ISSUE THREAD

**Issue by igaidai4uk** [FormidableLabs/victory#777]
Additionally _domainPadding_ is not getting applied.
Do I miss something?

<img width="671" alt="screenshot 2017-10-03 20 03 14" src="https://user-images.githubusercontent.com/2185483/31140901-2ef03f4e-a876-11e7-9f8b-603bbe397737.png">

**Comment by boygirl** [comment]
@igaidai4uk automatic centering by a very small number is the expected behavior for a single data point. You can get around this by providing your own domain. Also, domain padding as you've used it would create symmetric padding. You can read more about domainPadding here: https://formidable.com/open-source/victory/docs/common-props#domainpadding.

I'm going to close this issue for now, but if you have more questions, or requests for how single data points should operate, please open another issue and reference this one is the comment.
