### ISSUE TITLE
Can't display two different dataset in VictoryLine and VictoryLine 

### ISSUE THREAD

**Issue by danieldelouya** [FormidableLabs/victory#787]
So I have two dataset. One with large numbers (e.g 2000, 3000, 3000) and another data set with small numbers (0.2, 0.3, 0.4, 0.5). 

If i put the the small dataset into a VictoryLine, and the large dataset into a VictoryBar, then the chart Y axis uses the large numbers, meaning that the VictoryLine almost becomes invisible due to its small numbers. 

I want to achieve the exact opposite. I want the VictoryBar to be small and the VictoryLine to be of normal scale. 

I can't seem to figure it out. Help we be greatly appreciated, thanks. 

My code looks like this: 

	```
	<VictoryChart >
					<VictoryAxis
						style={{tickLabels: {fontSize: 10}}}
						dependentAxis={true}
						tickCount={10}
						tickFormat={(t) => `${t.toFixed(2)}`}
					/>

					<VictoryLine
						style={{data: { stroke: Colors.color.limeGreen, strokeWidth: 3}}}
						y="price"
						data={this.state.data} // dataset with large numbers
					/>

					<VictoryBar
						style={{data: { fill: Colors.color.limeGreen }}}
						y="y"
						standalone={true}
						height={10}
						data={
							  [
							 { x: 1, y: 5},
							 { x: 2, y: 3},
							 { x: 3, y: 5},
							 { x: 4, y: 4},
							 { x: 5, y: 6},
							 { x: 6, y: 3},
							{ x: 7, y: 7},
							{ x: 8, y: 2},
							 { x: 9, y: 5},
						 ]}
					  />
				</VictoryChart>
```

**Comment by boygirl** [comment]
@danieldelouya This is expected behavior for VictoryChart. It will determine a domain that includes all the data values of its children. If you have two extreme datasets on the same chart, you should expect one of them to appear quite compressed. To get around this, I would suggest normalizing your data. You can then re-scale your axis labels. Here's an example that might help you https://formidable.com/open-source/victory/gallery/multiple-dependent-axes

**Comment by danieldelouya** [comment]
Thanks :)
