### ISSUE TITLE
Jumping domain after zoomeed

### ISSUE THREAD

**Issue by azizmuradovar** [FormidableLabs/victory#789]
![jumping domain](https://user-images.githubusercontent.com/22165930/31494708-369170fe-af5d-11e7-8d36-9e24801ded65.gif)

**Comment by denniseijpe** [comment]
I have the exact same issue. For me, setting `zoomActive` on the container fixed it.

**Comment by azizmuradovar** [comment]
@denniseijpe i try it) but dont work

**Comment by ecnaidar** [comment]
@azizmuradovar I think the issue is in having the custom `zoomDomain` and `minimumZoom` together
In theory, manually controlling your domain size should work in this case and you should be able to manually write logic for the zoom related properties such as `minimumZoom` and `zoomDimension`. 
Sounds good, does not work. See https://stackblitz.com/edit/react-tqjzj8
It is possible to observe that `brushDomain` stops shrinking while referring to same values as `zoomDomain` but the zooming is still possible and if you add the logic to lock `zoomDimension` by only changing `x` in `handleZoom` function it won't affect zooming with scroll either.

**Comment by kbrgl** [comment]
Any update on this? Were you able to fix your issue?

Oddly enough, the problem is present in the official documentation as well: https://formidable.com/open-source/victory/docs/victory-zoom-container/.

Try zooming in all the way, and take note of the X-axis.

**Comment by kbrgl** [comment]
Hi @boygirl!

Was this bug fixed? If not, I think the issue should still remain open—the [official docs](https://formidable.com/open-source/victory/docs/victory-zoom-container/) still contain this bug.

https://user-images.githubusercontent.com/13417496/103506692-5c3b3b00-4e83-11eb-9c76-5ea6a6df35a8.mov

**Comment by ericlo23** [comment]
I have a similar issue. I use `onZoomDomainChange` and `zoomDomain` to control the zoom.
```javascript
const [zoomDomain, setZoomDomain] = useState(null);
```
```jsx
<VictoryZoomVoronoiContainer
  responsive={false}
  onZoomDomainChange={setZoomDomain}
  zoomDomain={zoomDomain}
  zoomDimension="x"
/>
```
I also have a button to reset the zoom.
```jsx
<Button onClick={() => setZoomDomain(null)}>reset</Button>
```

## Steps to reproduce the issue
1. Zoom to 0.0010 ~ 0.0013
2. Click the reset button.
3. Move cursor to another place and zoom.
4. The domain will jump to 0.0010 ~ 0.0013 and start zooming.

The following code sample shows the issue.
https://codesandbox.io/s/friendly-framework-4hvt6b?file=/src/App.tsx
