### ISSUE TITLE
Toggling static/animated

### ISSUE THREAD

**Issue by natefaubion** [FormidableLabs/victory#790]
Toggling `animate` from `null` to some other option results in an error due to a method which is conditionally added for some bizarre reason:

https://github.com/FormidableLabs/victory-chart/blob/7723f00339906fd4d6c82324714d277210d6d55d/src/components/victory-chart/victory-chart.js#L70
https://github.com/FormidableLabs/victory-chart/blob/7723f00339906fd4d6c82324714d277210d6d55d/src/components/victory-chart/victory-chart.js#L81

**Comment by paulyoung** [comment]
I'm not sure if this would be an acceptable fix, but I could contribute a pull request to move `his.setAnimationState = Wrapper.setAnimationState.bind(this);` out of the conditional so that it's always set.

The method already includes a check for `props.animate` anyway: https://github.com/FormidableLabs/victory-chart/blob/7723f00339906fd4d6c82324714d277210d6d55d/src/helpers/wrapper.js#L56
