### ISSUE TITLE
Not possible to set renderInPortal as true for labelComponent in VoronoiContainer

### ISSUE THREAD

**Issue by cbranch101** [FormidableLabs/victory#791]
```
<VictoryVoronoiContainer
    labelComponent={
        <VictoryTooltip
            renderInPortal={true}
        />
    }
/>
```
The victory tool tip in the above code will always receive `renderInPortal` as false

**Comment by parkerziegler** [comment]
@boygirl What do we want the default behavior for `renderInPortal` to be? I believe `VictoryTooltip` defaults to `true`, i.e. it will always render in a portal if no `renderInPortal` prop is specified. Here it was always being coerced to `false` by how `<VictoryVoronoiContainer />` was using it. We could default it to `true` to keep it consistent across components.

**Comment by boygirl** [comment]
Just removing the explicit `renderInPortal={false}` will be enough to correct the behavior, however rendering these labels in the portal causes issues with updating the tooltip. The portal is not re-rendering as expected.

**Comment by parkerziegler** [comment]
Ok I'll have a closer look at it tomorrow and at least correct the false coercion in a PR.

**Comment by parkerziegler** [comment]
We should be able to fix this by just removing [this line](https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/victory-voronoi-container.js#L198). The one hang up is that `VictoryTooltip` will always render in a portal if no `renderInPortal` prop is supplied, due to [this line from `VictoryTooltip`](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-tooltip/victory-tooltip.js#L90). So the user would have to manually specify `labelComponent{<VictoryTooltip renderInPortal={false} />}`. Unless we can think of another workaround. [This PR](https://github.com/FormidableLabs/victory-chart/pull/546) removes the `false` coercion (making the default `renderInPortal` true).

**Comment by wootencl** [comment]
👋 Just checking to see if there's bee any progress on this issue?

**Comment by becca-bailey** [comment]
I'm not sure whether this is still reproducible - this needs more investigation.
