### ISSUE TITLE
Does Victory allow combined charts? (bar + line?)

### ISSUE THREAD

**Issue by jkornblum** [FormidableLabs/victory#795]
I'm new to Victory and I've browsed through the documentation and issues on GitHub and haven't found an answer to this. Is it possible to combine charts in Victory, for example a line and bar charts with multiple y axis?

Something like,
```
<V.VictoryChart>
     <V.VictoryBar
           data={qtys}/>
     <V.VictoryLine
            data={fyields}/>
</V.VictoryChart>
```
It renders only the `VictoryBar`.

**Comment by boygirl** [comment]
Yes, this is possible, and both the line and the bar should show up in the example you give above. The only reason they wouldn't would be if data domains a very different. i.e. y values for VictoryBar in the thousands and y values for VictoryLine more like 1, 2, 3 etc. In this case, your line will not be distinguishable from your x axis. In order to plot extreme values on the same chart, you can normalize your data, and then rescale the labels on your axes. 
Here's an example: https://formidable.com/open-source/victory/gallery/multiple-dependent-axes
