### ISSUE TITLE
Wrapping / refactoring 'containerComponent' loses events / props

### ISSUE THREAD

**Issue by JRGranell** [FormidableLabs/victory#804]
I appreciate this may be an edge case but I am trying to refactor the 'brush' and 'voronoi' containers that are create via `createContainer` into another element in order to put all my brush / tooltip logic in that new element. This allows me to re-use the new element across various charts. I've stripped out much of the code for simplicity.

```
const BrushAndTooltipContainer = createContainer('brush', 'voronoi');

class CustomContainer extends React.PureComponent{
     handleDomainChange(){...}
     render(){
          // Note that props are passed through
          return <BrushAndTooltipContainer {...this.props} onBrushDomainChange=this.handleDomainChange} />
     }
}
```
```
// Then I use the custom container where ever I need it
<VictoryChart containerComponent={CustomContainer}>....</VictoryChart>
```

Unfortunately nothing happens - I suspect it is to do with the targeting of event handles. I've tried hoisting the static `defaultEvents` from the created container, and they fire - but they lack the props that are passed to the combined container - i.e. missing the `onBrushDomainChange` prop.

I also considered a HOC, although this would wrap the component and I would have the same issue. 

Any different approach or work arounds would be appriciated.

**Comment by boygirl** [comment]
@JRGranell 

All Victory containers extend from `VictoryContainer`, and so they also get `static role = "container"` which other Victory components will use to decide which props to pass. You can try adding that static and see how far that gets you

Another consequence is that all of these containers share a render method, and differ in their `renderChildren` methods. The special `createContainer` helper combines the output of these as well: https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/create-container.js#L94

I would suggest reading through the code for `createContainer` and seeing what you can adjust to your own uses. The mixins themselves like `voronoiContainerMixin` are exported, so you should be able to use them directly.

Best of luck!

I'm going to close this as an issue, since it is definitely an edge case that wont be supported by any code changes, but I will continue to answer your questions here and in the gitter channel. Depending on what comes out of this discussion, I could also imagine some addition to the docs with a write up of this use case as a guide or gallery example.

**Comment by bhamme** [comment]
It'd be great if there was a guide for this. I'm trying to do the same thing. Implemented downsampling & some custom events on my container and wanted to factor it into its own component for readability/reusability. I don't think something as ubiquitous as modularization should be considered an edge case.

@JRGranell I was able to get things behaving correctly by shaping my Component as a stateless functional component, and then rendering it by actually calling the function with my props rather than in usual JSX element form:
```
<VictoryChart
    containerComponent={CustomContainer({
        prop1,
        prop2,
        ...
    })}
/>
```

rather than

```
<VictoryChart
    containerComponent={
        <CustomContainer
            prop1
            prop2
            ...
        />
    }
/>
```

Hope that helps

**Comment by JRGranell** [comment]
@bhamme That's a good solution, unfortunately it wont work for me as I need to perform logic that requires access to props and state. But I like the approach.

@boygirl Thanks for the pointer, unfortunately no luck, so I ended up just creating a 'BaseChart' component and passing in the specific chart components such as Axis / Area etc as children.

I did have one more follow up question, relating to clearing the brushed area. I noticed on the demo (https://formidable.com/open-source/victory/docs/victory-brush-container) it's not possible to clear it in any way.

I can clear using a mouse click by using my own `onMouseUp` event base on https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/brush-helpers.js#L232. Our needs are that on clicking outside the brushed area it clears (which I would have thought would be default behaviour)

What I was wondering is how to can clear it programmatically or if I can pass down a specific props props, call a func on refs or something? I've tried passing `brushDomain={{ x: [0,0], y[0,0] }}` but doesn't seem to have the desired effect. 

Perhaps I could return https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/brush-helpers.js#L245 however that would mean I have to implement setting `isSelecting=true` etc. at some point, probably by copying  https://github.com/FormidableLabs/victory-chart/blob/master/src/components/containers/brush-helpers.js#L113 and implementing my own `onMouseDown` event which would seemed duplicitous.

Any thoughts would be appreciated.

Thanks,

**Comment by wootencl** [comment]
A bit late to the discussion here but going to have to agree with @bhamme. Something as common as root components to consolidate common props seems like a not unreasonable request. The fact that the below _will_ work:
```
<VictoryAxis
   ... // some props
   />
```
And the below _will_ not is a bit perplexing:
```
const Axis = props => 
   <VictoryAxis  
      ... // common props
      {...props} />

// Using in `VictoryChart`
<Axis
   ... // specific props 
   />
```

Fairly positive this is the same issue that's seen/mentioned in #938.

**Comment by Guillaume-Docquier** [comment]
I've had the same use case as @wootencl and I was (and still am) very confused about it. 

I'm trying to make reusable parts to my graphs, notably the axis, but nothing scales correctly unless I use it as a function instead of using it like an actual component (which I want it to be).

Is there really no way to make a component that renders a VictoryComponent work properly ?

**Comment by aditya1711** [comment]
> I've had the same use case as @wootencl and I was (and still am) very confused about it.
> 
> I'm trying to make reusable parts to my graphs, notably the axis, but nothing scales correctly unless I use it as a function instead of using it like an actual component (which I want it to be).
> 
> Is there really no way to make a component that renders a VictoryComponent work properly ?

Was anyone able to figure something on this? Trying to write a custom container component with custom labels, tooltip and flyout

**Comment by Maribhuvan** [comment]
> 
while creating common component like below
const Axis = props => 
   <VictoryAxis  
      ... // common props
      {...props} />

// Using in `VictoryChart`
<Axis
   ... // specific props 
   />
   this is not working correctly. when i pass data to that component it will not render .
