### ISSUE TITLE
Interactive Victory Tooltip... is this possible?

### ISSUE THREAD

**Issue by michaeljpetter** [FormidableLabs/victory#815]
Is there any known way to have an interactive VictoryTooltip?  Every example I've seen (even with HTML content and custom flyouts) still works around the fundamental principle that the tooltip is only shown while the mouse is over the data element.

What we are looking for here is a flow as such:
1) User mouses over (or maybe clicks?) a data item on a chart (e.g., Scatter in this case).
2) A tooltip pops up with some interactive content.
3) User moves the mouse into the tooltip and interacts with the content.  The mouse is no longer over the data item, but the tooltip does not close.
4) The user mouses out of the tooltip (or maybe clicks an 'X') and the tooltip disappears.

The scenario here is that we've got a time-condensed graph, where one visual data point may actually represent several real data points.  We'd like the user to be presented with a tooltip for each visual data point, which allows them to view and navigate the real data points, e.g., with left/right arrows (please, forgive the crude ASCII art):
```
      *
_____/\___________________________
| [<<]  Data XXX (3 of 5)  [>>]  |
|    ... some details ...        |
|________________________________|
```

Is something like this even possible?  Any suggestions on how to do this?  We've struggled with this for the better part of a day, and come up empty-handed.

**Comment by boygirl** [comment]
@michaeljpetter This is possible in Victory, but it will require that you dig into the event system rather than relying on the default events provided by Victory tooltip. 

I've put together a little example of an alternative tooltip interaction, that is triggered only onClick. Here's a fiddle: https://jsfiddle.net/boygirl/4w5vo8vd/

Here's more information on the event system: https://formidable.com/open-source/victory/guides/events

You will also need to create some custom tooltip component to get interaction / updating text. I would recommend simple events (i.e. directly attached to your rendered flyout component rather than using Victory's event system) for that interaction, since it won't need to operate between elements. 

Here's a guide on custom components: https://formidable.com/open-source/victory/guides/custom-components

I'm going to close this issue, but please let me know if you have more questions. I'd love to see a gif of this working. It sounds cool!

**Comment by timBm10c** [comment]
Hi @boygirl 

The jsfiddle doesn't seem to be working and I tried doing this sort of thing with no luck. I'm trying to create an interactive tooltip to allow the user to add annotaitons on the chart, exactly like this: https://demo.baremetrics.com/stats/mrr

Would appreciate if you could share details on how this can be done with Victoryjs? I have made a custom tooltip, but the button on it doesn't work and also when you hover over the tooltip while it's also over a line it will move, so impossible to click the button in some instances. I need to keep the tooltip open while the mouse is hovering over it.
