### ISSUE TITLE
Graphs are not working in EDGE HTML 14 version

### ISSUE THREAD

**Issue by Girish-K** [FormidableLabs/victory#822]
Hi,

I am using Victory charts and found out an issue while testing in EDGE HTML 14 version. Application details are mentioned below clearly.

Details:
1. We are rendering a sample graph in material UI dialog.
2. When I open the dialog for 10th or 11th time, the graph is breaking.
3. But, when I place the victory line in an SVG component, it works perfectly.

Application link: [](https://sims3.knolskape.com/gt/#/)

One more note, Graphs are working perfectly EDGE 15 and above versions.

Can you please respond with the fix as early as possible.

Thanks for the awesome library,
Girish.

**Comment by jerrith** [comment]
I too encounter an issue when using a Victory PieChart rendered in Edge.
I have a VictoryContainer element that contains a PieChart and legend, but when the component renders in Edge the viewbox is missing from the generates SVG component.
When opening the exact same application in chrome or Edge Chromium the graph renders perfectly and the viewbox property is set.
The missing viewbox property on Edge causes the graph to not be rendered completely, because the containing DIV does not resize for the needed size and the graph is clipped, so in practice only half the pie is visible.
I also posted a question with the react code on Spectrum community:

https://spectrum.chat/victory/general/viewbox-property-is-not-set-on-the-svg-component-in-microsoft-edge-ie~fa7d42e7-6301-44c4-afce-f19a16a3606c
