### ISSUE TITLE
add `allowSelection` prop for `VictorySelectionContainer`

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#846]
true by default.
@mbilokonsky please and any additional comments about how you'd want this prop to operate.

**Comment by mbilokonsky** [comment]
Could also name it something like `disable` or `enable` - basically the problem is that if I combine the selection container with the zoom container I'd like to be able to specify the mousedown behavior - it should either select or pan, depending on how the props are configured.

Right now, though, while zoomContainer does allow me to disable `allowPan`, there's no similar control in the selectionContainer.

**Comment by boygirl** [comment]
`allowSelection` added in `victory-chart@24.3.1`
