### ISSUE TITLE
Tooltip component replaces color strings with rgb values

### ISSUE THREAD

**Issue by cdimitroulas** [FormidableLabs/victory#851]
For example - if the label for a data point is "Black" then the tooltip will render the string as "rgb(0,0,0)".

**Comment by kale-stew** [comment]
@cdimitroulas I'm looking for a little more information to reproduce (& hopefully fix) this bug. What is the context surrounding the instance you ran into this? Have you had issues with it since? Could you take a screenshot or share the code for your `<VictoryTooltip />`? 

I have tried a few different demos as well as our editable source online and have yet to run into this bug.

**Comment by cdimitroulas** [comment]
Hmm I'm sorry I don't have the code for this bug anymore, I found another way forward without using the tooltip in the end.
