### ISSUE TITLE
VictoryBar overflows if chart width is too large

### ISSUE THREAD

**Issue by alexthebake** [FormidableLabs/victory#920]
Hey,

I'm new to victory, and I've been trying to make some wide bar charts using only `VictoryChart` and `VictoryBar`. For some reason, as the width the chart increases, the bars start to overflow out of the axes. I've been looking through the docs and old issues, but I haven't found this problem exactly.

**Screenshot**
![screen shot 2018-02-05 at 12 44 02 pm](https://user-images.githubusercontent.com/1433616/35822559-47efe7ac-0a72-11e8-91cd-3ff7000737dc.png)

**Code**
https://jsfiddle.net/2vktLdnh/2/
```jsx
<VictoryChart width={WIDTH} height={HEIGHT} domainPadding={24}>
  <VictoryBar data={data} style={{ data: { fill: 'red' } }} />
</VictoryChart>
```

Also, I noticed that this didn't seem to be a problem before? I was playing with a [JSFiddle](https://jsfiddle.net/jzvvL1y8/) which was using version 0.18.0, and the bars weren't overflowing (although the bars are also thinner).

**Comment by boygirl** [comment]
@alexthebake this is expected behavior. The domain of the chart is calculated without taking any stylistic attributes (such as bar width) into account. You can mitigate this issue in one fo the following ways:

1) manually set a domain like `domain={{ x: [ 3,  30] }}`
2) set a domain padding (this may be the best option for changing datasets. It's roughly pixel based, so you can set it to match your bar width `domainPadding={{ x: myBarWidth / 2 }} `
3) If you need your first bar to start exactly at the axis, you can set the `alignment` prop on `VictoryBar`. Options are "start", "middle" and "end"

**Comment by alexthebake** [comment]
@boygirl thanks for the quick response!

**Comment by ChrisBlueStone** [comment]
Hate to dig up an old issue, but why is this expected behavior? I'd expect the chart to be contained within its bounds without needing to manually adjust it with magic numbers or magic calculations.
