### ISSUE TITLE
when the label is a color like "red" it renders "rgb(255,0,0)

### ISSUE THREAD

**Issue by lonelydatum** [FormidableLabs/victory#928]
Hello and thanks for the great library!

I've reproduced the issue here but I need the animation so what solution?: 
https://codesandbox.io/s/k062y8l13v

the fix is to comment out the animate property 
 <VictoryPie
     // animate={{ duration: 500, easing: "cubicOut" }}
      colorScale={colors}
      data={data}
      height={500}
      width={500}
      y={datum => datum._percent}
      labelRadius={110}
      labelComponent={<PieLabel />}
    />

**Comment by jthetzel** [comment]
I suspect prop strings like `red` and `blue` are being interpolated to rgb() strings in https://github.com/FormidableLabs/victory-core/blob/master/src/victory-animation/util.js .

**Comment by jthetzel** [comment]
Related: d3/d3-interpolate#42

**Comment by jthetzel** [comment]
Related PR: d3/d3-interpolate#43

**Comment by 1e1f** [comment]
+1, in my case it was "Chocolate", lol.

**Comment by DingoEatingFuzz** [comment]
I ran into this today too: https://codesandbox.io/s/xjz0l4wwj4

I wonder if it's worth waiting for d3-interpolate? That PR has been open for a year an a half at this point.

**Comment by jacobkossman** [comment]
Any update to this? Really annoying, converting the word 'Azure' to it's RGB info...

**Comment by Fil** [comment]
From [victory-animation.js](https://github.com/FormidableLabs/victory-core/blob/master/src/victory-animation/victory-animation.js#L8) it seems that this code is trying to interpolate the data, instead of interpolating only values passed as visual parameters.

With the current code base the following workaround helps make sure that the data labels are "not interpolable":
data={data.map(d => Object.assign({},d, {name: d.name + "\x03"}))}

\x03 is ascii for "end of text", but several other values work too. (Workaround tested on https://codesandbox.io/s/xjz0l4wwj4 )

**Comment by beccanelson** [comment]
As discussed in other comments, Victory uses `d3-interpolate` in order to animate data, and this is related to the way `d3-interpolate` handles color interpolation with rgb values. This [d3-interpolate issue](https://github.com/d3/d3-interpolate/issues/42) suggests excluding keys from the interpolated object, and Victory does provide a way to do this via the `animationWhitelist` prop. 

https://formidable.com/open-source/victory/docs/victory-transition#animationwhitelist


```js
 <VictoryChart style={style}>
          <VictoryBar
            animate={{
              animationWhitelist: ["data"]
            }}
            data={this.state.data}
            style={{
              data: this.state.style
            }}
          />
    </VictoryChart>
```

This prop allows you to select which attributes are included in the animation, and any excluded components will not be interpolated. By default, every Victory component includes this as a static property, so you can check out the source for examples of the properties you would include. If there are not other `style` properties you would want to animate, you can leave `style` out of this list to prevent `victory-interpolate` from updating the fill color. 

https://github.com/FormidableLabs/victory/blob/844109cfe4e40b23a4dcb565e551a5a98015d0c0/packages/victory-scatter/src/victory-scatter.js#L27

I'm going to close this issue for now, since I don't believe further action is required on Victory's side, but let me know if this doesn't work and we need to re-open to discuss alternate solutions.
