### ISSUE TITLE
Victory Tooltip for very low data

### ISSUE THREAD

**Issue by gokulramesh71** [FormidableLabs/victory#939]
When i'm using victory tooltip in a bar chart, it doesn't pop up for very low data. Even though the value is comparatively lower than the other values, i should be able to get the data in the tooltip.

**Comment by boygirl** [comment]
@gokulramesh71 If your data values are very small, it may be that the target bar element is not easily hoverable. It might be overlapped by the axis line? You might try re-ordering you `VictoryBar` and `VictoryAxis` components so that the bars are rendered on top. If that doesn't solve your issue, you might try using `VictoryVoronoiContainer` to trigger your tooltips. You can read about it here: https://formidable.com/open-source/victory/docs/victory-voronoi-container/
