### ISSUE TITLE
Zero value not showing on line chart

### ISSUE THREAD

**Issue by ShaikhKabeer** [FormidableLabs/victory#951]
I'm just starting out in Victory and I'm just making a victory line chart. When I have a zero value it doesn't show the zero line on the dependent axis.

**Comment by boygirl** [comment]
I think what you want is to change the `crossAxis` prop on `VictoryAxis`. By default, zero value ticks are removed so that they don't overlap each other at the origin. You can turn this behavior off with the `crossAxis` prop. You can read about it here: https://formidable.com/open-source/victory/docs/victory-axis/#crossaxis
