### ISSUE TITLE
Dynamic Width/Height calculation examples

### ISSUE THREAD

**Issue by maherbeg** [FormidableLabs/victory#96]
Is Victory able to calculate width and height dynamically based on the container it is rendering in?

I see that there are default values for width and height which makes me inclined that it isn't feasible at the moment.

**Comment by neverfox** [comment]
You can always use something like react-dimensions. Works perfectly.

**Comment by boygirl** [comment]
That's not something we're doing yet, and I'm pretty wary these components getting any sort of parent context that isn't explicitly passed down in props. The fact that they're so nicely self contained makes composition really straight forward.

**Comment by maherbeg** [comment]
@boygirl I'm generally in agreement here. I love that everything is built through composition. One thing that could be done is to have a specific wrapper for allowing dimensions to be calculated that would contain the charts themselves. Another option is to do the simplest thing and have an example pattern of how to do this. I imagine a lot of users would actually like this functionality and having proper guidance/best practices would be very valuable.

Super excited for Victory :) Can't wait for tooltip and legend support!

**Comment by boygirl** [comment]
@maherbeg good idea. Mind if I change the title of this issue to "Dynamic Width/Height calculation example" ?

**Comment by neverfox** [comment]
I agree also, which is why I brought up react-dimensions. Unfortunately, that project has some key fixes that are on master but not released on npm (and it requires a build step that keeps it from being installed via github), so you have to run on a fork. It's a good example though of how it's done and could serve as a template for a `victory-dimensions`.

**Comment by maherbeg** [comment]
@boygirl Please do! Thank you!

@neverfox Sweet, good to know. Will definitely use that for our current graphing needs and hopefully make use of it when we can use Victory.

**Comment by neverfox** [comment]
Feel free to use the build branch of my fork, which is up-to-date and will work as an npm install from GitHub because it contains the built JS file. You might want to make your own fork since I cannot guarantee I won't change it.

**Comment by maherbeg** [comment]
@neverfox Much appreciated! Will take a look into using it as our wrapper layer.

Thanks all for being so responsive and helpful!

**Comment by knowbody** [comment]
@maherbeg have a look at the JSFiddle I've just created https://jsfiddle.net/knowbody/scxm342c/1/

that's how I would do it, you can use either [`offsetHeight`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight) or [`clientHeight`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight) depending on your needs.

@boygirl let me know what you think about it, if this is okay we could add FAQ section to the docs and include snippets like this one there

**Comment by boygirl** [comment]
@knowbody we have an (out of date) victory-examples repo, but I think fiddles are more accessible. +1 for a FAQ section for now, but I think this might expand to the point that something a little more organized / searchable would be nice.

**Comment by exogen** [comment]
If you just want to scale the entire SVG up (including text sizes, etc.), you could consider taking advantage of SVG's `viewBox` attribute. Using this method, Victory still renders to a fixed coordinate system, but the entire image is scaled up.

It depends on whether you'd like the chart dimensions to be scaled up while keeping its elements (like text, bar width, etc.) the same size, or if you're just trying to scale up the whole image in order to fill available space.

Demo: https://jsfiddle.net/scxm342c/2/

**Comment by maherbeg** [comment]
Both examples are stellar and easily show the extensibility of the system. +1

**Comment by hourliert** [comment]
Thanks @exogen . Didn't know the `viewBox` attribute. You save my day!

**Comment by boygirl** [comment]
Closing in favor of https://github.com/FormidableLabs/victory/issues/235
