### ISSUE TITLE
VictoryBar Not Changing Color

### ISSUE THREAD

**Issue by Ericky14** [FormidableLabs/victory#980]
# Bugs and Questions

### Checklist

* [v] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [v] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [v] I am using the latest version of Victory

* [v] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have 2 VictoryBars inside a VictoryGroup inside a VictoryChart.
I set the color of the bars by doing ```style={{ data: { fill: colors[i] || colors.base } }}```
So far it works normal when I toggle one of the VictoryBar component and the whole chart transitions to having only 1 bar series.
However, if I hover over any bar first (which triggers the hover event and mutates the color opacity on the bar), when toggling a bar series, the color for that bar will not properly transition.

<img width="683" alt="screen shot 2018-04-18 at 7 11 15 pm" src="https://user-images.githubusercontent.com/21248862/38963050-2af0980e-433e-11e8-9f4c-601d328ab9b7.png">
<img width="704" alt="screen shot 2018-04-18 at 7 11 19 pm" src="https://user-images.githubusercontent.com/21248862/38963072-2ed124de-433e-11e8-9166-8b6133b6a8f9.png">

### Reproduction

* Have 2 VictoryBars in a VictoryGroup.
* Have events attached to the VictoryBars which mutate their color onMouseOver and onMouseOut.
* Hover over a few of the bars.
* Toggle off one of the bar series by a button or something like that.

**Comment by boygirl** [comment]
@Ericky14 Mutations from Victory's event system mask any props that would normally control the rendering of your bars. Because Victory's event system needs to work with animations etc, it has no concept of time, and does not cache anything like the original props for your elements, so it can't know when they've changed. In order to make changes to your chart both via Victory's event system and via some external trigger, you can use the `externalEventMutations` prop described here: https://formidable.com/open-source/victory/guides/events/#external-event-mutations. It works very similarly to the usual `events` prop. Here's an example that should help: https://codesandbox.io/s/304686nk21
