### ISSUE TITLE
Victory Tooltip for grouped chart

### ISSUE THREAD

**Issue by gokulramesh71** [FormidableLabs/victory#989]
I am using Victory group to render a group of charts. The charts include several combination of victory line and victory bar. In some cases, a **single data point is a part of multiple charts**. While, trying to view data through the tooltip, several tooltip boxes are popping up. Is there any way to deal with the tooltip for **coinciding data points** or **data points which are very close to each other**?

**Comment by boygirl** [comment]
@gokulramesh71 you can use `VictoryVoronoiContainer` to ensure that only a single point is activated for a given mouse position, or add a `voronoiDimension` prop to allow several points with the same x position, for example, to be activated at once, and create a single tooltip with several values displayed.

**Comment by gokulramesh71** [comment]
Yes, we are already using VictoryVoronoiContainer. Our aim is to create tooltip for each charts rather than combining all the data into a single tooltip.
**Let me explain my scenario.**
Let's say i have a bar and a line with the same data point. It would look somewhat like this:
![gok1](https://user-images.githubusercontent.com/33889242/39294481-7eeacf12-4959-11e8-8ddb-dfda39279ec1.png)

But what i want is if i **hover over the point**, i should be able to get the **tooltip for line** and if i **hover over other spaces inside bar,** the **tooltip of bar** should be displayed.

**Comment by boygirl** [comment]
@gokulramesh71 Got it. In that case, you _should not_ use `VictoryVoronoiContainer`. Instead, provide `labelComponent={<VictoryTooltip/>}` directly to your `VictoryScatter` and `VictoryBar` components. That way, the targets for each tooltip will be the rendered elements themselves. By the way, you will want to use `VictoryScatter` rather than `VictoryLine` for adding tooltips, even if you use transparent scatter points over your line. This is because `VictoryLine` only renders a single element, so there will not be individual points to target for your tooltips otherwise.
