### ISSUE TITLE
assign className to Victory component

### ISSUE THREAD

**Issue by mmurkidjanian** [FormidableLabs/victory#99]
I've tried to assign a class to a victory component (e.g. VictoryChart) using the className attribute, but the class isn't assigned.

**Comment by contra** [comment]
@boygirl Why closed? This seems to still be an issue - the className prop isn't passed through to the DOM

**Comment by boygirl** [comment]
I can be convinced to re-open this issue since individually rendered elements are now extracted into their own components like `Point`, `Bar` etc. I don't think it's appropriate for Victory components like `VictoryChart` to pass className attributes down to their children. This strikes me as complicated (it could lead to needing to reconcile classNames) and unnecessary (these components don't actually render anything directly). I will support adding classNames to `dataComponent`, `labelComponent` etc like so: 

```
<VictoryBar
  dataComponent={<Bar className="foo"/>}
/>
```
@contra does that seem like a good solution to you? If you have more feedback about how classNames ought to operate, I'd love to hear it. Victory was definitely written with inline styles in mind. I would like to do as much as I can to support other uses without altering how styles are currently applied.

**Comment by contra** [comment]
@boygirl I'm only interested in giving a className to the top-level element, I don't think it makes sense to do it on any of the non-dom rendering components.

**Comment by boygirl** [comment]
@contra Then following the same pattern, adding a className to top level elements would like like:

```
<VictoryChart
  containerComponent={<VictoryContainer className="foo"/>}
>
...
</VictoryChart>
```

**Comment by contra** [comment]
Yeah, that seems reasonable I guess given the way things are structured.

**Comment by boygirl** [comment]
This should be a minimal change. I can get this out for you ~ tonight for the web version of Victory, and probably by the weekend for Victory Native.

**Comment by contra** [comment]
@boygirl Thanks!
