### ISSUE TITLE
Tooltip on stacked bar graph only displays if mousing-over the top-most bar

### ISSUE THREAD

**Issue by LMojica** [FormidableLabs/victory#997]
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I have a stacked bar graph. I would like a tooltip to appear any time that I mouse-over any of the blocks that make up a single bar. The current behavior only renders the tooltip if I mouse-over the top-most block within a bar. This also causes a bigger problem when the top-most block within a bar has a value of 0. In that case, it won't ever render the tooltip.

### Reproduction
Here is a forked sandbox. https://codesandbox.io/s/vm36p67qn7
In case that doesn't work, this is the code I'm running:
```
<VictoryStack labels={["a", "b", "c"]} labelComponent={<VictoryTooltip />}>
        <VictoryBar
          data={[{ x: "a", y: 2 }, { x: "b", y: 3 }, { x: "c", y: 5 }]}
        />
        <VictoryBar
          data={[{ x: "a", y: 1 }, { x: "b", y: 4 }, { x: "c", y: 5 }]}
        />
        <VictoryBar
          data={[{ x: "a", y: 0 }, { x: "b", y: 2 }, { x: "c", y: 6 }]}
        />
</VictoryStack>
```
What you will notice is that as you mouse-over each of the bars, the tooltip won't render until you have your mouse over the top-most block in each of the 3 bars. Also, the left-most bar won't even render the tooltip because it's top-most block has a value of 0.

**Comment by younitee** [comment]
you could try labels and labelComponent on each VictoryBar instead

**Comment by boygirl** [comment]
The issue you're running into is that labels on `VictoryStack` are designed to only add labels to the top most bar in the stack so that they appear to reference the whole stack rather than individual elements within it. 

If you want each bar element to have its own tooltip, you should do as @younitee suggests. If you want each stack to have only a single label, you can have a nicer hover experience if you use `VictoryVoronoiContainer`. The `voronoiDimension` prop will let you select all the data matching the mouse position in a given dimension (stacks). You can read more about it here: https://formidable.com/open-source/victory/docs/victory-voronoi-container/
